### ISSUE TITLE
Mix process crashing in tests

### ISSUE THREAD

**Issue by lukaszsamson** [elixir-lsp/elixir-ls#100]
### Environment

* Elixir & Erlang versions (elixir --version): 1.9.x, 1.10-rc.0
* Operating system: macos, linux

### Crash report template

Running tests result in one of mix application processes crashing. It looks like the tests put mix in some illegal state.

elixir 1.10-rc.0
```
12:36:34.397 [error] GenServer Mix.ProjectStack terminating
** (FunctionClauseError) no function clause matching in anonymous fn/1 in Mix.ProjectStack.recur/1
    (mix 1.10.0-rc.0) lib/mix/project_stack.ex:183: anonymous fn([]) in Mix.ProjectStack.recur/1
    (mix 1.10.0-rc.0) lib/mix/project_stack.ex:268: Mix.ProjectStack.handle_call/3
    (stdlib 3.11) gen_server.erl:661: :gen_server.try_handle_call/4
    (stdlib 3.11) gen_server.erl:690: :gen_server.handle_msg/6
    (stdlib 3.11) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message (from #PID<0.92.0>): {:update_stack, #Function<21.19485960/1 in Mix.ProjectStack.recur/1>}
State: {[], []}
Client #PID<0.92.0> is alive

    (stdlib 3.11) gen.erl:167: :gen.do_call/4
    (elixir 1.10.0-rc.0) lib/gen_server.ex:1020: GenServer.call/3
    (mix 1.10.0-rc.0) lib/mix/project_stack.ex:180: Mix.ProjectStack.recur/1
    (mix 1.10.0-rc.0) lib/mix/cli.ex:82: Mix.CLI.run_task/2
    (elixir 1.10.0-rc.0) src/elixir_compiler.erl:75: :elixir_compiler.dispatch/4
    (elixir 1.10.0-rc.0) src/elixir_compiler.erl:60: :elixir_compiler.compile/3
    (elixir 1.10.0-rc.0) src/elixir_lexical.erl:14: :elixir_lexical.run/3
    (elixir 1.10.0-rc.0) src/elixir_compiler.erl:18: :elixir_compiler.quoted/3
    (elixir 1.10.0-rc.0) lib/code.ex:917: Code.require_file/2
    (elixir 1.10.0-rc.0) lib/kernel/cli.ex:549: Kernel.CLI.wrapper/1
    (elixir 1.10.0-rc.0) lib/enum.ex:1396: Enum."-map/2-lists^map/1-0-"/2
    (elixir 1.10.0-rc.0) lib/kernel/cli.ex:76: Kernel.CLI.process_commands/1
    (elixir 1.10.0-rc.0) lib/kernel/cli.ex:30: anonymous fn/2 in Kernel.CLI.main/1
    (elixir 1.10.0-rc.0) lib/kernel/cli.ex:124: anonymous fn/3 in Kernel.CLI.exec_fun/2
```

elixir 1.9.1
```
00:20:15.427 [error] GenServer Mix.ProjectStack terminating
** (FunctionClauseError) no function clause matching in anonymous fn/1 in Mix.ProjectStack.recur/1
    (mix) lib/mix/project_stack.ex:210: anonymous fn(%{cache: %{}, post_config: [], stack: []}) in Mix.ProjectStack.recur/1
    (elixir) lib/agent/server.ex:27: Agent.Server.handle_cast/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: {:"$gen_cast", {:cast, #Function<23.36738168/1 in Mix.ProjectStack.recur/1>}}
State: %{cache: %{}, post_config: [], stack: []}
```

**Comment by lukaszsamson** [comment]
This no longer happens
