### ISSUE TITLE
Dialyzer write manifest crashes on CI on elixir 1.7

### ISSUE THREAD

**Issue by lukaszsamson** [elixir-lsp/elixir-ls#101]
### Environment

* Elixir & Erlang versions (elixir --version): 1.7, otp 20.3
* Operating system: linux

### Crash report template

```
00:20:55.080 [error] Task #PID<0.1544.0> started from #PID<0.1232.0> terminating
** (ArgumentError) argument error
    (stdlib) :ets.select_trap({#Reference<0.1221418905.1456340993.57541>, 2003, 0, #Reference<0.1221418905.1456340994.55827>, [{{Logger, :enable, 1}, {{:c, :atom, [:ok], :unknown}, [:any]}}, {{:erl_types, :t_map_def_key, 2}, {:any, [{:c, :opaque, [{:opaque, :erl_types, :erl_type, [], {:c, :union, [{:c, :atom, [:any, :none, :unit], :unknown}, :none, :none, :none, :none, :none, {:c, :tuple, [{:c, :atom, [:c], :unknown}, {:c, :atom, :any, :unknown}, :any, {:c, :union, [{:c, :atom, [:float, :integer, :nonempty, :pid, :port, ...], :unknown}, :none, :none, :none, :none, :none, {:c, :tuple, ...}, :none, :none, ...], :unknown}], {4, {:c, :atom, [:c], :unknown}}}, :none, :none, :none], :unknown}}], :unknown}, {:c, :union, [{:c, :atom, [:universe], :unknown}, :none, :none, :none, {:c, :list, [{:c, :opaque, [{:opaque, :erl_types, :erl_type, [], {:c, :union, [{:c, :atom, [:any, :none, :unit], :unknown}, :none, :none, :none, :none, :none, {:c, :tuple, [{:c, :atom, ...}, {:c, ...}, :any, ...], {4, {...}}}, :none, :none, :none], :unknown}}], :unknown}, {:c, nil, [], :unknown}], :unknown}, :none, :none, :none, :none, :none], :unknown}]}}, {{:file, :path_eval, 3}, {{:c, :tuple_set, [{2, [{:c, :tuple, [{:c, :atom, [:error], :unknown}, {:c, :union, [{:c, :atom, :any, :unknown}, :none, :none, :none, :none, :none, {:c, :tuple, [{:c, :union, [:none, :none, :none, :none, :none, {:c, :number, {:int_rng, ...}, :integer}, {:c, :tuple, [...], ...}, :none, :none, :none], :unknown}, {:c, :atom, :any, :unknown}, :any], {3, :any}}, :none, :none, :none], :unknown}], {2, {:c, :atom, [:error], :unknown}}}, {:c, :tuple, [{:c, :atom, [:ok], :unknown}, :any], {2, {:c, :atom, [:ok], :unknown}}}]}], :unknown}, [{:c, :list, [{:c, :union, [{:c, :atom, :any, :unknown}, {:c, :binary, [8, 0], :unknown}, :none, :none, {:c, :list, [{:c, :union, [{:c, :atom, :any, :unknown}, :none, :none, :none, {:c, :list, [:any, {:c, nil, [], :unknown}], :unknown}, {:c, :number, {:int_rng, 0, 1114111}, :integer}, :none, :none, :none, :none], :unknown}, {:c, nil, [], :unknown}], :unknown}, :none, :none, :none, :none, :none], :unknown}, {:c, nil, [], :unknown}], :unknown}, {:c, :union, [{:c, :atom, :any, :unknown}, {:c, :binary, [8, 0], :unknown}, :none, :none, {:c, :list, [{:c, :union, [{:c, :atom, :any, :unknown}, :none, :none, :none, {:c, :list, [:any, {:c, nil, [], :unknown}], :unknown}, {:c, :number, {:int_rng, 0, 1114111}, :integer}, :none, :none, :none, :none], :unknown}, {:c, nil, [], :unknown}], :unknown}, :none, :none, :none, :none, :none], :unknown}, :any]}}, {{:digraph, :add_vertex, 1}, {:any, [{:c, :opaque, [{:opaque, :digraph, :graph, [], {:c, :tuple, [{:c, :atom, [:digraph], :unknown}, {:c, :union, [{:c, :atom, :any, :unknown}, :none, :none, :none, :none, :none, :none, :none, {:c, :opaque, [{:opaque, :ets, :tid, [], {:c, ...}}], :unknown}, :none], :unknown}, {:c, :union, [{:c, :atom, :any, :unknown}, :none, :none, :none, :none, :none, :none, :none, {:c, :opaque, [{:opaque, :ets, :tid, [], {...}}], :unknown}, :none], :unknown}, {:c, :union, [{:c, :atom, :any, :unknown}, :none, :none, :none, :none, :none, :none, :none, {:c, :opaque, [{:opaque, :ets, :tid, [], ...}], :unknown}, :none], :unknown}, {:c, :atom, [false, true], :unknown}], {5, {:c, :atom, [:digraph], :unknown}}}}], :unknown}]}}, {{Registry, :start_link, 3}, {{:c, :tuple_set, [{2, [{:c, :tuple, [{:c, :atom, [:error], :unknown}, :any], {2, {:c, :atom, [:error], :unknown}}}, {:c, :tuple, [{:c, :atom, [:ok], :unknown}, {:c, :identifier, [:pid], :unknown}], {2, {:c, :atom, [:ok], :unknown}}}]}], :unknown}, [{:c, :atom, [:duplicate, :unique], :unknown}, {:c, :atom, :any, :unknown}, {:c, :list, [{:c, :tuple_set, [{2, [{:c, :tuple, [{:c, :atom, [:keys], :unknown}, {:c, :atom, [:duplicate, :unique], :unknown}], {2, {:c, :atom, [:keys], :unknown}}}, {:c, :tuple, [{:c, :atom, [:listeners], :unknown}, {:c, :list, [{:c, :atom, :any, :unknown}, {:c, nil, [], :unknown}], :unknown}], {2, {:c, :atom, [:listeners], :unknown}}}, {:c, :tuple, [{:c, :atom, [:meta], :unknown}, {:c, :list, [{:c, :tuple, [:any, :any], {2, :any}}, {:c, nil, [], :unknown}], :unknown}], {2, {:c, :atom, [:meta], :unknown}}}, {:c, :tuple, [{:c, :atom, [:name], :unknown}, {:c, :atom, :any, :unknown}], {2, {:c, :atom, [:name], :unknown}}}, {:c, :tuple, [{:c, :atom, [:partitions], :unknown}, {:c, :number, {:int_rng, 1, :pos_inf}, :integer}], {2, {:c, :atom, [:partitions], :unknown}}}]}], :unknown}, {:c, nil, [], :unknown}], :unknown}]}}, {{:hipe_arm_cfg, :init, 1}, {{:c, :tuple, [{:c, :atom, [:cfg], :unknown}, {:c, :opaque, [{:opaque, :gb_trees, :tree, [:any, :any], {:c, :tuple, [{:c, :number, {:int_rng, 0, :pos_inf}, :integer}, {:c, :union, [{:c, :atom, [nil], :unknown}, :none, :none, :none, :none, :none, {:c, :tuple, [:any, :any, :any, :any], {4, :any}}, :none, :none, :none], :unknown}], {2, :any}}}], :unknown}, {:c, :tuple, [{:c, :atom, [:cfg_info], :unknown}, {:c, :tuple, [:any, :any, :any], {3, :any}}, {:c, :number, {:int_rng, 0, :pos_inf}, :integer}, {:c, :atom, [false, true], :unknown}, {:c, :union, [{:c, :atom, [:none], :unknown}, :none, :none, :none, :none, {:c, :number, {:int_rng, 0, 255}, :integer}, :none, :none, :none, :none], :unknown}, {:c, :atom, [false, true], :unknown}, {:c, :list, [:any, {:c, nil, [], :unknown}], :unknown}, {:c, :list, [:any, {:c, nil, [], :unknown}], :unknown}], {8, {:c, :atom, [:cfg_info], :unknown}}}, {:c, :tuple, [{:c, :opaque, [{:opaque, :dict, :dict, [:any, :any], {:c, :tuple, [:any, :any, :any, :any, :any, :any, :any, :any, :any], {9, :any}}}], :unknown}, {:c, :list, [:any, {:c, nil, [], :unknown}], :unknown}, {:c, :number, {:int_rng, 0, :pos_inf}, :integer}], {3, :any}}], {4, {:c, :atom, [:cfg], :unknown}}}, [{:c, :tuple, [{:c, :atom, [:defun], :unknown}, {:c, :tuple, [{:c, :atom, :any, :unknown}, {:c, :atom, :any, :unknown}, {:c, :number, {:int_rng, 0, 255}, :integer}], {3, :any}}, :any, :any, {:c, :tuple, [{:c, :opaque, [{:opaque, :dict, :dict, [:any, :any], {:c, :tuple, [{:c, :atom, [:dict], :unknown}, {:c, :number, {:int_rng, 0, :pos_inf}, :integer}, {:c, :number, {:int_rng, 0, :pos_inf}, :integer}, {:c, :number, {:int_rng, 0, :pos_inf}, :integer}, {:c, :number, {:int_rng, 0, ...}, :integer}, {:c, :number, {:int_rng, ...}, :integer}, {:c, :number, {...}, ...}, {:c, :tuple, ...}, {:c, ...}], {9, {:c, :atom, [:dict], :unknown}}}}], :unknown}, {:c, :list, [{:c, :number, {:int_rng, 0, :pos_inf}, :integer}, {:c, nil, [], :unknown}], :unknown}, {:c, :number, {:int_rng, 0, :pos_inf}, :integer}], {3, :any}}, {:c, :atom, [false, true], :unknown}, {:c, :atom, [false, true], :unknown}, :any, :any], {9, {:c, :atom, [:defun], :unknown}}}]}}, {{IO, :module_info, 1}, {:any, [:any]}}, {{:hipe_ppc_specific_fp, :def_use, 2}, {{:c, :tuple, [{:c, :list, [:any, {:c, nil, [], :unknown}], :unknown}, {:c, :list, [:any, {:c, nil, [], :unknown}], :unknown}], {2, :any}}, [:any, :any]}}, {{:erl_posix_msg, :message, 1}, {:any, [:any]}}, {{Kernel.LexicalTracker, :remote_dispatch, 5}, {{:c, :atom, [:ok], :unknown}, [{:c, :union, [{:c, :atom, :any, :unknown}, :none, :none, {:c, :identifier, [:pid], :unknown}, :none, :none, {:c, :tuple_set, [{2, [{:c, :tuple, [{:c, :atom, :any, :unknown}, :any], {2, :any}}]}, {3, [{:c, :tuple, [{:c, :atom, [:via], :unknown}, :any, :any], {3, {:c, :atom, [:via], :unknown}}}]}], :unknown}, :none, :none, :none], :unknown}, {:c, :atom, :any, :unknown}, :any, :any, :any]}}, {{:group, :interfaces, 1}, {{:c, :list, [{:c, :tuple_set, [{2, [{:c, :tuple, [{:c, :atom, [:shell], :unknown}, :any], {2, {:c, :atom, [:shell], :unknown}}}, {:c, :tuple, [{:c, :atom, [:user_drv], :unknown}, :any], {2, {:c, :atom, [:user_drv], :unknown}}}]}], :unknown}, {:c, nil, [], :unknown}], :unknown}, [:any]}}, {{Registry, :unregister_match, 4}, {{:c, :atom, [:ok], :unknown}, [{:c, :union, [{:c, :atom, :any, :unknown}, :none, :none, :none, :none, :none, :none, :none, {:c, :opaque, [{:opaque, :ets, :tid, [], {:c, :identifier, [:reference], :unknown}}], :unknown}, :none], :unknown}, :any, :any, {:c, :list, [:any, {:c, nil, [], :unknown}], :unknown}]}}, {{:cerl, :call_module, 1}, {:any, [{:c, :tuple, [{:c, :atom, [:c_call], :unknown}, :any, :any, :any, :any], {5, {:c, :atom, [:c_call], :unknown}}}]}}, {{:elixir_lexical, :module_info, 1}, {:any, [:any]}}, {{:hipe_x86_specific_x87, :breadthorder, 2}, {{:c, :list, [:any, {:c, nil, [], :unknown}], :unknown}, [{:c, :tuple, [{:c, :atom, [:cfg], :unknown}, {:c, :opaque, [{:opaque, :gb_trees, :tree, [:any, :any], {:c, :tuple, [{:c, :number, {:int_rng, 0, :pos_inf}, :integer}, {:c, :union, [{:c, :atom, ...}, :none, :none, ...], :unknown}], {2, :any}}}], :unknown}, {:c, :tuple, [{:c, :atom, [:cfg_info], :unknown}, {:c, :tuple, [{:c, :atom, :any, :unknown}, {:c, :atom, :any, :unknown}, {:c, :number, {:int_rng, 0, 255}, :integer}], {3, :any}}, {:c, :number, {:int_rng, 0, :pos_inf}, :integer}, {:c, :atom, [false, true], :unknown}, {:c, :union, [{:c, :atom, [:none], :unknown}, :none, :none, :none, :none, {:c, :number, ...}, :none, :none, ...], :unknown}, {:c, :atom, [false, true], :unknown}, {:c, :list, [:any, {:c, nil, [], :unknown}], :unknown}, {:c, :list, [:any, {:c, nil, [], ...}], :unknown}], {8, {:c, :atom, [:cfg_info], :unknown}}}, {:c, :tuple, [{:c, :opaque, [{:opaque, :dict, :dict, [:any, :any], {:c, :tuple, [{:c, ...}, {...}, ...], {9, ...}}}], :unknown}, {:c, :list, [{:c, :number, {:int_rng, 0, :pos_inf}, :integer}, {:c, nil, [], :unknown}], :unknown}, {:c, :number, {:int_rng, 0, :pos_inf}, :integer}], {3, :any}}], {4, {:c, :atom, [:cfg], :unknown}}}, :any]}}, {{RuntimeError, :__struct__, 1}, {:any, [:any]}}, {{:hipe_ppc, :pseudo_fmove_src, 1}, {:any, [{:c, :tuple, [{:c, :atom, [:pseudo_fmove], :unknown}, :any, :any], {3, {:c, :atom, [:pseudo_fmove], :unknown}}}]}}, {{:proplists, :lookup, 2}, {{:c, :union, [{:c, :atom, [:none], :unknown}, :none, :none, :none, :none, :none, {:c, :tuple, :any, {:any, :any}}, :none, :none, :none], :unknown}, [:any, {:c, :list, [:any, :any], :unknown}]}}, {{Supervisor, :delete_child, 2}, {:any, [{:c, :union, [{:c, :atom, :any, :unknown}, :none, :none, {:c, :identifier, [:pid], :unknown}, :none, :none, {:c, :tuple_set, [{2, [{:c, :tuple, [{...}, ...], {...}}]}, {3, [{:c, :tuple, [...], ...}]}], :unknown}, :none, :none, :none], :unknown}, :any]}}, {{:dets_utils, :find_allocated, 4}, {:any, [{:c, :tuple, :any, {:any, :any}}, {:c, :number, :any, :unknown}, {:c, :number, :any, :unknown}, :any]}}, {{:binary, :matches, 2}, {:any, [:any, :any]}}, {{BadBooleanError, :__info__, 1}, {:any, [{:c, :atom, [:attributes, :compile, :deprecated, :functions, :macros, :md5, :module], :unknown}]}}, {{:cerl, :string_val, 1}, {:any, [{:c, :tuple, [{:c, :atom, [:c_literal], :unknown}, :any, :any], {3, {:c, :atom, [:c_literal], :unknown}}}]}}, {{System, :endianness, 0}, {{:c, :atom, [:big, :little], :unknown}, []}}, {{Kernel, :"MACRO-defmacro", 3}, {{:c, :tuple, [{:c, :tuple, [{:c, :atom, [:.], :unknown}, {:c, nil, [], :unknown}, {:c, :list, [{:c, :atom, [...], ...}, {:c, nil, ...}], :nonempty}], {3, {:c, :atom, [:.], :unknown}}}, {:c, nil, [], :unknown}, {:c, :list, [:any, {:c, nil, [], :unknown}], :nonempty}], {3, :any}}, [{:c, :union, [:none, :none, :none, :none, :none, :none, {:c, :tuple, [:any, {...}], {2, ...}}, :none, :none, {:c, :map, ...}], :unknown}, :any, :any]}}, {{:hipe_amd64_specific, :is_spill_move, 2}, {{:c, :atom, [false, true], :unknown}, [:any, :any]}}, {{:hipe_llvm, :adj_stack_register, 1}, {:any, [{:c, :tuple, [{:c, :atom, [:llvm_adj_stack], :unknown}, :any, :any, :any], {4, {:c, :atom, [:llvm_adj_stack], :unknown}}}]}}, {{:hipe_sparc_ra_ls, :module_info, 0}, {:any, []}}, {{:proc_lib, :hibernate, 3}, {:any, [{:c, :atom, :any, :unknown}, {:c, :atom, :any, :unknown}, {:c, :list, [:any, :any], :unknown}]}}, {{:gen, :reply, 2}, {{:c, :tuple, [:any, :any], {2, :any}}, [{:c, :tuple, [:any, :any], {2, :any}}, :any]}}, {{Task, :start, 3}, {{:c, :tuple, [{:c, :atom, [:ok], :unknown}, {:c, :identifier, [:pid], :unknown}], {2, {:c, :atom, [:ok], :unknown}}}, [:any, :any, :any]}}, {{:hipe_ppc_cfg, :branch_preds, 1}, {{:c, :list, [{:c, :tuple, [:any, {:c, ...}], {2, :any}}, {:c, nil, [], :unknown}], :unknown}, [{:c, :tuple_set, [{1, [{:c, ...}]}, {2, [{...}, ...]}, {3, [...]}, {5, ...}], :unknown}]}}, {{Access, :__info__, 1}, {:any, [{:c, :atom, [:attributes, :compile, :deprecated, :functions, ...], :unknown}]}}, {{Stream, :dedup_by, 2}, {{:c, :map, {[{{:c, :atom, ...}, :mandatory, {...}}, {{:c, ...}, :mandatory, ...}, {{...}, ...}, {...}], :any, :any}, :unknown}, [:any, :any]}}, {{:hipe_llvm, :mk_indirectbr, 3}, {{:c, :tuple, [{:c, :atom, [...], ...}, :any, :any, :any], {4, {:c, ...}}}, [:any, :any, :any]}}, {{:cerl, :atom_lit, 1}, {{:c, :list, [{:c, :union, ...}, {:c, ...}], :nonempty}, [{:c, :tuple, [{...}, ...], {...}}]}}, {{:disk_log_1, :chunk, 5}, {{:c, :tuple, [:any, :any], {2, ...}}, [:any, :any, :any, :any, ...]}}, {{:erts_debug, :map_info, 1}, {:any, [:any]}}, {{Version.InvalidVersionError, :__struct__, 0}, {{:c, :map, {...}, ...}, []}}, {{:application, :get_application, 0}, {{:c, :union, ...}, []}}, {{String.Chars.Version, :__impl__, 1}, {{:c, ...}, [...]}}, {{Inspect.Port, :module_info, ...}, {:any, ...}}, {{:hipe_icode, ...}, {...}}, {{...}, ...}, {...}, ...], 2760})
    (stdlib) ets.erl:736: :ets.tab2list/1
    (language_server) lib/language_server/dialyzer/manifest.ex:43: anonymous fn/6 in ElixirLS.LanguageServer.Dialyzer.Manifest.write/6
    (elixir) lib/task/supervised.ex:89: Task.Supervised.do_apply/2
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Function: #Function<7.78335674/0 in ElixirLS.LanguageServer.Dialyzer.Manifest.write/6>
    Args: []
```

Works fine on newer elixir and otp combinations

**Comment by lukaszsamson** [comment]
I noticed a similar crash on elixir 1.10 otp 23 combo. I'm not sure it's exactly the same as log is truncated.
```
06:22:52.755 [error] Task #PID<0.31922.1> started from #PID<0.32423.1> terminating
332** (ArgumentError) argument error
333    (stdlib 3.13) :ets.select_trap({#Reference<0.1546473763.543555585.67839>, 10722, 0, 
```

**Comment by lukaszsamson** [comment]
Closing as elixir 1.7 is no longer supported
