### ISSUE TITLE
Crash in 0.18.0 with elixir 1.14.0-otp-24

### ISSUE THREAD

**Issue by evan-sse** [elixir-lsp/elixir-ls#1043]
### Environment

* Elixir & Erlang versions (elixir --version): `Elixir 1.14.0 (compiled with Erlang/OTP 24)`
* Elixir Language Server version: `ElixirLS v0.18.0`
* Operating system: `macOS 13.6.3 (22G436)`
* Editor or IDE name (e.g. Emacs/VSCode): `VSCode 1.85.1`
* Editor Plugin/LSP Client name and version: ?

### Current behavior

Since upgrading to 0.18.0, the language server is continually crashing and restarting. See the log messages below.

Here's a [minimal repo](https://github.com/evan-sse/elixir-ls-crash-test) that reliably reproduces the issue for me. It's just a new mix project with a single undefined module for ElixirLS to notice.

<details>
<summary>ElixirLS extension logs...</summary>

```
Running /Users/evan/.vscode/extensions/jakebecker.elixir-ls-0.18.0/elixir-ls-release/launch.sh
Preferred shell is zsh, relaunching
Looking for ASDF install
ASDF install found in /usr/local/opt/asdf/libexec/asdf.sh, sourcing
Installing ElixirLS release v0.18.0
Running in /Users/evan/Code/errtest
Could not find Hex, which is needed to build dependency true
Shall I install Hex? (if running non-interactively, use "mix local.hex --force")
* creating /Users/evan/.asdf/installs/elixir/1.14.0-otp-24/.mix/archives/hex-2.0.6
Install complete
Could not find Hex, which is needed to build dependency true
Shall I install Hex? (if running non-interactively, use "mix local.hex --force")
* creating /Users/evan/.asdf/installs/elixir/1.14.0-otp-24/.mix/archives/hex-2.0.6
[Info  - 2:59:35 PM] Started ElixirLS v0.18.0
[Info  - 2:59:35 PM] Running in /Users/evan/Code/errtest
[Info  - 2:59:35 PM] ElixirLS built with elixir "1.14.0" on OTP "24"
[Info  - 2:59:35 PM] Running on elixir "1.14.0 (compiled with Erlang/OTP 24)" on OTP "24"
[Info  - 2:59:35 PM] Protocols are not consolidated
[Warn  - 2:59:35 PM] OTP compiled without EEP48 documentation chunks. Language features for erlang modules will run in limited mode. Please reinstall or rebuild OTP with appropriate flags.
[Info  - 2:59:35 PM] Elixir sources not found (checking in /home/build/elixir). Code navigation to Elixir modules disabled.
[Info  - 2:59:35 PM] Received client configuration via workspace/configuration
%{"additionalWatchedExtensions" => [], "autoBuild" => true, "autoInsertRequiredAlias" => false, "dialyzerEnabled" => true, "dialyzerFormat" => "dialyxir_long", "dialyzerWarnOpts" => [], "enableTestLenses" => false, "envVariables" => %{}, "fetchDeps" => false, "languageServerOverridePath" => "", "mixEnv" => "test", "mixTarget" => "", "projectDir" => "", "signatureAfterComplete" => true, "suggestSpecs" => false, "trace" => %{"server" => "off"}}
[Info  - 2:59:36 PM] Registering for workspace/didChangeConfiguration notifications
[Info  - 2:59:36 PM] client/registerCapability succeeded
[Info  - 2:59:36 PM] Registering for workspace/didChangeWatchedFiles notifications
[Info  - 2:59:36 PM] Starting build with MIX_ENV: test MIX_TARGET: host
[Info  - 2:59:36 PM] client/registerCapability succeeded
Parsing file:///Users/evan/Code/errtest/lib/errtest.ex immediately: languageId elixir
file:///Users/evan/Code/errtest/lib/errtest.ex already parsed
[Info  - 2:59:36 PM] Loaded DETS databases in 272ms
Compiling 1 file (.ex)
[Warn  - 2:59:37 PM] warning: Nothing.something/0 is undefined (module Nothing is not available or is yet to be defined)
  lib/errtest.ex:18: Errtest.hello/0

Generated errtest app
[Info  - 2:59:37 PM] Compile took 377 milliseconds
[Info  - 2:59:37 PM] [ElixirLS Dialyzer] Checking for stale beam files
[Info  - 2:59:37 PM] [ElixirLS Dialyzer] Found 1 changed files in 2 milliseconds
[Error - 2:59:37 PM] Terminating Elixir.ElixirLS.LanguageServer.Server: an exception was raised:
    ** (FunctionClauseError) no function clause matching in Regex.run/3
        (elixir 1.14.0) lib/regex.ex:335: Regex.run(~r/line (\d+)/u, ["Nothing.something/0", " is undefined (module ", "Nothing", " is not available or is yet to be defined)"], [])
        (language_server 0.18.0) lib/language_server/diagnostics.ex:400: ElixirLS.LanguageServer.Diagnostics.get_related_information_message/3
        (language_server 0.18.0) lib/language_server/diagnostics.ex:321: anonymous fn/4 in ElixirLS.LanguageServer.Diagnostics.publish_file_diagnostics/4
        (elixir 1.14.0) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
        (language_server 0.18.0) lib/language_server/diagnostics.ex:301: ElixirLS.LanguageServer.Diagnostics.publish_file_diagnostics/4
        (language_server 0.18.0) lib/language_server/server.ex:1633: anonymous fn/5 in ElixirLS.LanguageServer.Server.publish_diagnostics/1
        (elixir 1.14.0) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
        (language_server 0.18.0) lib/language_server/server.ex:1589: ElixirLS.LanguageServer.Server.publish_diagnostics/1
        (language_server 0.18.0) lib/language_server/server.ex:1459: ElixirLS.LanguageServer.Server.handle_build_result/3
        (language_server 0.18.0) lib/language_server/server.ex:262: ElixirLS.LanguageServer.Server.handle_cast/2
        (stdlib 3.17.2) gen_server.erl:695: :gen_server.try_dispatch/4
        (stdlib 3.17.2) gen_server.erl:771: :gen_server.handle_msg/6
        (stdlib 3.17.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
[Info  - 2:59:37 PM] [ElixirLS Dialyzer] Analyzing 0 modules: []
[Info  - 2:59:37 PM] [ElixirLS Dialyzer] Analysis finished in 12 milliseconds
[Info  - 2:59:37 PM] [ElixirLS Dialyzer] Writing manifest...
[Info  - 2:59:37 PM] [ElixirLS Dialyzer] Done writing manifest in 742 milliseconds.
[Error - 2:59:39 PM] Server process exited with code 1.
[Info  - 2:59:39 PM] Connection to server got closed. Server will restart.
```
</details>

### Workaround

In VSCode, I was able to go to "Install another version..." and roll back to `0.17.10`. After rolling back, the plugin works as expected.

Updating `.tool-versions` to use the latest `elixir 1.16.0-otp-26` also appears to work fine with `ElixirLS v0.18.0` in this test project. In my case, this isn't helpful since my real project is on `elixir 1.14.0-otp-24` right now.

**Comment by lukaszsamson** [comment]
Already fixed on master in https://github.com/elixir-lsp/elixir-ls/commit/e5cbf690fca3bd0a60d8ac2bbd154f6d440a23db, expect v0.18.1 release soon
