### ISSUE TITLE
Mix.install failed with ** (Mix.Error) Command "git --git-dir=.git checkout --quiet v0.21.0-dev" failed with reason: error: pathspec 'v0.21.0-dev' did not match any file(s) known to git

### ISSUE THREAD

**Issue by anildigital** [elixir-lsp/elixir-ls#1085]
### Environment

* Elixir & Erlang versions (elixir --version): 
elixir 1.14.4-otp-25
erlang 25.2.3

* Elixir Language Server version: `8486de473a219dcdb72408702f8d56d0227c7366`

* Operating system: macOS 14.4.1 (23E224)
* Editor or IDE name: Emacs 
* Editor Plugin/LSP Client name and version: LSP :: lsp-mode 20240422.334, Emacs 30.0.50, darwin

### Current behavior

```bash
elixir-ls (master) [1]> sh release/language_server.sh
Running /Users/anil/Code/elixir-ls/release/launch.sh
Preferred shell is fish, launching launch.fish
Looking for ASDF install
ASDF install found in /opt/homebrew/opt/asdf/libexec/asdf.fish, sourcing
Installing ElixirLS release v0.21.0-dev
Running in /Users/anil/Code/elixir-ls
* Updating elixir_ls (https://github.com/elixir-lsp/elixir-ls.git - v0.21.0-dev)
Mix.install failed with ** (Mix.Error) Command "git --git-dir=.git checkout --quiet v0.21.0-dev" failed with reason: error: pathspec 'v0.21.0-dev' did not match any file(s) known to git

    (mix 1.14.4) lib/mix.ex:513: Mix.raise/2
    (mix 1.14.4) lib/mix/scm/git.ex:136: Mix.SCM.Git.checkout/2
    (elixir 1.14.4) lib/file.ex:1607: File.cd!/2
    (mix 1.14.4) lib/mix/dep/fetcher.ex:61: Mix.Dep.Fetcher.do_fetch/3
    (mix 1.14.4) lib/mix/dep/converger.ex:213: Mix.Dep.Converger.all/9
    (mix 1.14.4) lib/mix/dep/converger.ex:146: Mix.Dep.Converger.all/7
    (mix 1.14.4) lib/mix/dep/converger.ex:95: Mix.Dep.Converger.all/4
    (mix 1.14.4) lib/mix/dep/converger.ex:74: Mix.Dep.Converger.converge/4

Retrying Mix.install with force: true
Installing ElixirLS release v0.21.0-dev
Running in /Users/anil/Code/elixir-ls
* Getting elixir_ls (https://github.com/elixir-lsp/elixir-ls.git - v0.21.0-dev)
** (Mix.Error) Command "git --git-dir=.git checkout --quiet v0.21.0-dev" failed with reason: error: pathspec 'v0.21.0-dev' did not match any file(s) known to git

    (mix 1.14.4) lib/mix.ex:513: Mix.raise/2
    (mix 1.14.4) lib/mix/scm/git.ex:136: Mix.SCM.Git.checkout/2
    (elixir 1.14.4) lib/file.ex:1607: File.cd!/2
    (mix 1.14.4) lib/mix/dep/fetcher.ex:64: Mix.Dep.Fetcher.do_fetch/3
    (mix 1.14.4) lib/mix/dep/converger.ex:213: Mix.Dep.Converger.all/9
    (mix 1.14.4) lib/mix/dep/converger.ex:146: Mix.Dep.Converger.all/7
    (mix 1.14.4) lib/mix/dep/converger.ex:95: Mix.Dep.Converger.all/4
    (mix 1.14.4) lib/mix/dep/converger.ex:74: Mix.Dep.Converger.converge/4
```

Latest elixir-ls with git commit sha `8486de473a219dcdb72408702f8d56d0227c7366`

### Expected behavior

It should just start properly.

**Comment by lukaszsamson** [comment]
Please use a released version. If you want to contribute please head to Readme for instructions
