### ISSUE TITLE
Unable to autocomplete/hover macro in Phoenix Project 

### ISSUE THREAD

**Issue by u4d3rc0v3r** [elixir-lsp/elixir-ls#1124]
The project is running in VSCode devcontainer

* Elixir & Erlang versions (elixir --version): 
elixir "1.17.3" on OTP "27"
* Elixir Language Server version: 
ElixirLS v0.24.1
* Operating system: 
MacOS
* Editor or IDE name (e.g. Emacs/VSCode): 
VSCode

### Elixir-LS Log
```
[Warn  - 11:24:37 AM] Unable to expand macro Phoenix.Endpoint.__before_compile__/1: ** (ArgumentError) could not call Module.get_attribute/2 because the module AppWeb.Endpoint is already compiled. Use the Module.__info__/1 callback or Code.fetch_docs/1 instead
    (elixir 1.17.3) lib/module.ex:2350: Module.assert_not_compiled!/3
    (elixir 1.17.3) lib/module.ex:1954: Module.get_attribute/7
    (phoenix 1.7.14) expanding macro: Phoenix.Endpoint.__before_compile__/1
    nofile: AppWeb.Endpoint (module)
```

### Reproduction steps
1. install elixir-ls in VSCode
2. Create fresh project using `mix phx.new app`

**Comment by lukaszsamson** [comment]
Which macros are you trying to hover on? In which files is autocomplete not working?

**Comment by u4d3rc0v3r** [comment]
> Which macros are you trying to hover on? In which files is autocomplete not working?

`:controller` this file is under lib/controllers/page_controller.ex in a fresh Phoenix project

**Comment by Ridtt** [comment]
Unable to expand macro Phoenix.Component.Declarative.__pattern__!/2: ** (ArgumentError) could not call Module.delete_attribute/2 because the module MyAppWeb.MyViewLive.FormComponent is already compiled
    (elixir 1.17.3) lib/module.ex:2365: Module.assert_not_readonly!/2
    (elixir 1.17.3) lib/module.ex:1641: Module.delete_attribute/2
    (phoenix_live_view 0.20.17) lib/phoenix_component/declarative.ex:1028: Phoenix.Component.Declarative.pop_slots/1
    (phoenix_live_view 0.20.17) lib/phoenix_component/declarative.ex:707: Phoenix.Component.Declarative.register_component!/4
    (phoenix_live_view 0.20.17) expanding macro: Phoenix.Component.Declarative.__pattern__!/2
    
I can't make it working for any macro accessing attributes/compile time properties of module in using and before_compile functions.
  
Started ElixirLS v0.24.1
ElixirLS built with elixir "1.17.3" on OTP "27"  

Using last version of elixir (1.17.3-otp-27) and OTP (27.1.2) installed via asdf. 

im trying to work with elixir-ls lsp from zed editor.
