### ISSUE TITLE
ElixirLS 0.26 Cannot using format document in Phoenix Project

### ISSUE THREAD

**Issue by realhaidinh** [elixir-lsp/elixir-ls#1150]
### Environment

* Elixir & Erlang versions (elixir --version): 
`Erlang/OTP 27 [erts-15.2] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit:ns] Elixir 1.18.0 (compiled with Erlang/OTP 27)`
* Elixir Language Server version: ElixirLS v0.26.0
* Operating system: Windows 11
* Editor or IDE name (e.g. Emacs/VSCode):  VSCode

### Current behavior
Format document function is broken

### ElixirLS logs
```
[Warn  - 1:37:53 AM] Unable to get formatter options for c:\dev\blog\lib\blog_web\router.ex: ** (Protocol.UndefinedError) protocol Enumerable not implemented for type Atom

Got value:

    :ok

    (elixir 1.18.0) lib/enum.ex:1: Enumerable.impl_for!/1
    (elixir 1.18.0) lib/enum.ex:166: Enumerable.reduce/3
    (elixir 1.18.0) lib/enum.ex:4511: Enum.reduce/3
    (language_server 0.26.0) lib/language_server/mix_tasks/format.ex:339: Mix.Tasks.ElixirLSFormat.load_plugins/2
    (language_server 0.26.0) lib/language_server/mix_tasks/format.ex:436: Mix.Tasks.ElixirLSFormat.formatter_for_file/2
    (language_server 0.26.0) lib/language_server/source_file.ex:282: ElixirLS.LanguageServer.SourceFile.formatter_for/3
    (language_server 0.26.0) lib/language_server/providers/formatting.ex:14: ElixirLS.LanguageServer.Providers.Formatting.format/4
    (language_server 0.26.0) lib/language_server/server.ex:1270: anonymous fn/3 in ElixirLS.LanguageServer.Server.handle_request_async/2
```
### Reproduction steps

1. Install elixir-ls v0.26.0 in VSCode
2. Create fresh project using `mix phx.new`

**Comment by lukaszsamson** [comment]
Fixed in v0.26.1
