### ISSUE TITLE
When hitting save inside of VS Code, formatter can not be found.

### ISSUE THREAD

**Issue by zorn** [elixir-lsp/elixir-ls#1151]
### Environment

* Elixir & Erlang versions (elixir --version): 1.18.0
* Elixir Language Server version: v0.26.0
* Operating system: macOS 14.5 (23F79)
* Editor or IDE name (e.g. Emacs/VSCode): VS Code
* Editor Plugin/LSP Client name and version: jakebecker.elixir-ls, 0.26.0, Last Updated 2024-12-30, 13:14:34

### Current behavior

Working on my side project and updating a bunch of dependencies and Elixir itself.

When I use `mix format` on the command line, things work, but when I hit save inside of of VS Code (with the ElixirLS extension installed) it does not find the formatter. I get this output from `ElixirLS`:

```
Running /Users/zorn/.vscode/extensions/jakebecker.elixir-ls-0.26.0/elixir-ls-release/launch.sh
Preferred shell is fish, launching launch.fish
Looking for ASDF install
ASDF install found in /Users/zorn/.asdf/asdf.fish, sourcing
Installing ElixirLS release v0.26.0
Running in /Users/zorn/ProjectRepos/flick
Install complete
[Info  - 1:50:30 PM] Started ElixirLS v0.26.0
[Info  - 1:50:30 PM] Running in /Users/zorn/ProjectRepos/flick
[Info  - 1:50:30 PM] ElixirLS built with elixir "1.18.0" on OTP "27"
[Info  - 1:50:30 PM] Running on elixir "1.18.0 (compiled with Erlang/OTP 27)" on OTP "27"
[Info  - 1:50:30 PM] Protocols are not consolidated
[Info  - 1:50:30 PM] Elixir sources not found (checking in /home/runner/work/elixir/elixir). Code navigation to Elixir modules disabled.
[Info  - 1:50:30 PM] Received client configuration via workspace/configuration
%{"additionalWatchedExtensions" => [], "autoBuild" => true, "autoInsertRequiredAlias" => false, "dialyzerEnabled" => true, "dialyzerFormat" => "dialyxir_long", "dialyzerWarnOpts" => [], "enableTestLenses" => false, "envVariables" => %{}, "fetchDeps" => false, "incrementalDialyzer" => true, "languageServerOverridePath" => "", "mixEnv" => "test", "mixTarget" => "", "projectDir" => "", "signatureAfterComplete" => true, "suggestSpecs" => false, "trace" => %{"server" => "off"}, "useCurrentRootFolderAsProjectDir" => false}
[Info  - 1:50:30 PM] Registering for workspace/didChangeConfiguration notifications
[Info  - 1:50:30 PM] Starting build with MIX_ENV: test MIX_TARGET: host
[Info  - 1:50:30 PM] client/registerCapability succeeded
[Info  - 1:50:30 PM] Registering for workspace/didChangeWatchedFiles notifications
[Info  - 1:50:30 PM] client/registerCapability succeeded
Compiling 29 files (.ex)
Generated flick app
[Info  - 1:50:31 PM] Compile took 931 milliseconds
[Info  - 1:50:31 PM] [ElixirLS WorkspaceSymbols] Indexing...
[Info  - 1:50:32 PM] [ElixirLS WorkspaceSymbols] Module discovery complete
[Info  - 1:50:32 PM] Updating incremental PLT
[Info  - 1:50:32 PM] [ElixirLS WorkspaceSymbols] 435 symbols added to index in 15ms
Received $/cancelRequest for unknown request id: 4
Received $/cancelRequest for unknown request id: 3
Received $/cancelRequest for unknown request id: 6
[Info  - 1:50:38 PM] Incremental PLT updated in 7054ms, changed 4 modules, analyzed 18, 2 warnings found
[Info  - 1:50:39 PM] Loaded PLT info in 816ms
[Info  - 1:50:39 PM] Dialyzer analysis is up to date
[Warn  - 1:50:49 PM] Unable to get formatter options for /Users/zorn/ProjectRepos/flick/lib/flick/ranked_voting.ex: ** (Protocol.UndefinedError) protocol Enumerable not implemented for type Atom

Got value:

    :ok

    (elixir 1.18.0) lib/enum.ex:1: Enumerable.impl_for!/1
    (elixir 1.18.0) lib/enum.ex:166: Enumerable.reduce/3
    (elixir 1.18.0) lib/enum.ex:4511: Enum.reduce/3
    (language_server 0.26.0) lib/language_server/mix_tasks/format.ex:339: Mix.Tasks.ElixirLSFormat.load_plugins/2
    (language_server 0.26.0) lib/language_server/mix_tasks/format.ex:436: Mix.Tasks.ElixirLSFormat.formatter_for_file/2
    (language_server 0.26.0) lib/language_server/source_file.ex:282: ElixirLS.LanguageServer.SourceFile.formatter_for/3
    (language_server 0.26.0) lib/language_server/providers/formatting.ex:14: ElixirLS.LanguageServer.Providers.Formatting.format/4
    (language_server 0.26.0) lib/language_server/server.ex:1270: anonymous fn/3 in ElixirLS.LanguageServer.Server.handle_request_async/2

[Info  - 1:50:49 PM] Starting build with MIX_ENV: test MIX_TARGET: host
Compiling 1 file (.ex)
Generated flick app
[Info  - 1:50:50 PM] Compile took 723 milliseconds
[Info  - 1:50:50 PM] [ElixirLS WorkspaceSymbols] Updating index...
[Info  - 1:50:50 PM] [ElixirLS WorkspaceSymbols] 1 modules need reindexing
[Info  - 1:50:50 PM] [ElixirLS WorkspaceSymbols] 18 symbols added to index in 4ms
[Info  - 1:50:50 PM] Updating incremental PLT
[Info  - 1:50:55 PM] Incremental PLT updated in 5310ms, changed 1 modules, analyzed 7, 2 warnings found
[Info  - 1:50:56 PM] Loaded PLT info in 822ms
[Info  - 1:50:56 PM] Dialyzer analysis is up to date
```

I suspect this might need to return an empty list and not `:ok` as of a recent change.

https://github.com/elixir-lsp/elixir-ls/blob/3041b15a1ba49cdcdc0f5fe264d7e15535378795/apps/language_server/lib/language_server/source_file.ex#L275-L279

Figured I'd share my notes. Hope this is helpful.

### Expected behavior

I expect the file to autoformat after I hit save in VS Code.

**Comment by lukaszsamson** [comment]
Fixed in v0.26.1
