### ISSUE TITLE
Unable to launch test task from VS Code

### ISSUE THREAD

**Issue by parry84** [elixir-lsp/elixir-ls#131]
### Environment

* Elixir & Erlang versions (elixir --version): Erlang/OTP 22 [erts-10.6.2] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe] [dtrace]
Elixir 1.10.0 (compiled with Erlang/OTP 22)
* Operating system: macOS Mojave 10.14.6
* Editor or IDE name: VSCode (latest)
* LSP Client name: 
* If using VSCode, are you using "ElixirLS Fork: Elixir support and debugger" (note that it has "Fork" in the name)? yes, the latest available on VSCode marketplace

### Crash report template
I'm starting from a brand new Mix project (generated with mix new_project)
I let VSCode create a launch.json file in order to run the tests.
With the generated Configuration I'm able to run the main task, the issue only applies to the mix test task.

The test mix task descriptor looks fine:
        {
            "type": "mix_task",
            "name": "mix test",
            "request": "launch",
            "task": "test",
            "taskArgs": [
                "--trace"
            ],
            "startApps": true,
            "projectDir": "${workspaceRoot}",
            "requireFiles": [
                "test/**/test_helper.exs",
                "test/**/*_test.exs"
            ]
        }

By then I try to launch the tests, by choosing "mix test" in the debugger and pressing the run button I get the following error:

Started ElixirLS debugger
Elixir version: "1.10.0 (compiled with Erlang/OTP 22)"
Erlang version: "22"
(Debugger) Initialization failed because an exception was raised:
    ** (Mix.NoProjectError) Could not find a Mix.Project, please ensure you are running Mix in a directory with a mix.exs file
        (mix 1.10.0) lib/mix/project.ex:176: Mix.Project.get!/0
        (mix 1.10.0) lib/mix/tasks/compile.ex:89: Mix.Tasks.Compile.run/1
        (mix 1.10.0) lib/mix/task.ex:330: Mix.Task.run_task/3
        (debugger 0.3.0) lib/debugger/server.ex:456: ElixirLS.Debugger.Server.initialize/1

of course the mix.exs is in the right place ...

**Comment by parry84** [comment]
Another info: the crash above doesn't happen with the JakeBecker version of ElixirLS
