### ISSUE TITLE
Error with import MyApp.{ModA, ModB}

### ISSUE THREAD

**Issue by manukall** [elixir-lsp/elixir-ls#16]
### Environment

* Elixir & Erlang versions (elixir --version): Elixir 1.8.0 (compiled with Erlang/OTP 20)
* Operating system: Linux
* Client (editor or IDE): Emacs

When visiting a file that is `using` a module that has a line like `import MyApp.{ModA, ModB}` in it's `__using__` macro, the following error is raised:
```
LSP :: an exception was raised:
    ** (FunctionClauseError) no function clause matching in Code.ensure_loaded/1
        (elixir) lib/code.ex:985: Code.ensure_loaded({{:., [], [ElixirLsTest, :{}]}, [], [ModA, ModB]})
        (elixir_sense) lib/alchemist/helpers/module_info.ex:64: Alchemist.Helpers.ModuleInfo.get_module_funs/1
        (elixir_sense) lib/alchemist/helpers/module_info.ex:52: Alchemist.Helpers.ModuleInfo.has_function?/2
        (elixir) lib/enum.ex:2948: Enum.find_list/3
        (elixir_sense) lib/elixir_sense/core/introspection.ex:628: ElixirSense.Core.Introspection.find_imported_function/2
        (elixir_sense) lib/elixir_sense/core/introspection.ex:602: ElixirSense.Core.Introspection.actual_mod_fun/4
        (elixir_sense) lib/elixir_sense/providers/docs.ex:12: ElixirSense.Providers.Docs.all/4
        (elixir_sense) lib/elixir_sense.ex:50: ElixirSense.docs/3
```

I've set up a test repo at https://github.com/manukall/elixir_ls_test. When opening the file lib/elixir_ls_test/using.ex I get the above error.

**Comment by axelson** [comment]
Example packet causing error:

```
Content-Length: 211

{"jsonrpc":"2.0","method":"textDocument/signatureHelp","params":{"textDocument":{"uri":"file:///home/jason/dev/forks/elixir_ls_test/lib/elixir_ls_test/using.ex"},"position":{"line":1,"character":0}},"id":10451}
```

**Comment by axelson** [comment]
@manukall does this happen only when ModA and ModB don't actually exist as modules?

**Comment by manukall** [comment]
No, it also happens when they exist. I was just to lazy to create them for
the example app.

Am So., 3. Feb. 2019, 10:21 hat Jason Axelson <notifications@github.com>
geschrieben:

**Comment by axelson** [comment]
Annoyingly, although the error is coming out of elixir_sense I have been completely unable to reproduce it in there. I'm starting to think that the bug is somewhere inside elixir-ls (which makes it harder to test).

**Comment by Trevoke** [comment]
Could it be that it's got to do with how elixir-ls sends the information to
elixir_sense?

**Comment by zachdaniel** [comment]
I didn't have a time to deep dive into this, but it looks like it has to do with a module making it to the metadata_builder without being properly quoted.

Adding this: 

```
+  defp pre({:import, [line: line, column: _column], [{{:., _, [module, :{}]}, _, imports}]} = ast, state) when is_atom(module) do
+    imports_modules = imports |> Enum.map(fn {:__aliases__, _, mods} ->
+      Module.concat([module | mods])
+    end)
+    pre_import(ast, state, line, imports_modules)
+  end
+
   # import without options
   defp pre({:import, meta, [module_info]}, state) do
     pre({:import, meta, [module_info, []]}, state)
```

to elixir_sense resolved that specific warning for me.

**Comment by zachdaniel** [comment]
Basically it is expecting the module in that case to be `{:__aliases__, _, _}` like it normally is, but sometimes it is *not* that and it is only a single module name :)

**Comment by axelson** [comment]
Is anyone able to reproduce this in vscode? I'm only able to reproduce it in Emacs with lsp-mode.

**Comment by lukaszsamson** [comment]
@axelson I'm able to reproduce it in vscode by moving the mouse pointer over first character of the `using.ex`. There's also a similar error with autocomplete suggestion when I add a new line
```
def 
```

```
** (Protocol.UndefinedError) protocol List.Chars not implemented for {{:., [], [ElixirLsTest, :{}]}, [], [ModA, ModB]} of type Tuple
    (elixir) lib/list/chars.ex:1: List.Chars.impl_for!/1
    (elixir) lib/list/chars.ex:17: List.Chars.to_charlist/1
    (elixir) lib/code.ex:240: Code.eval_string/3
    lib/alchemist/helpers/module_info.ex:37: Alchemist.Helpers.ModuleInfo.get_functions/2
    lib/alchemist/helpers/complete.ex:49: anonymous fn/6 in Alchemist.Helpers.Complete.run/2
    (elixir) lib/enum.ex:1948: Enum."-reduce/3-lists^foldl/2-0-"/3
    lib/alchemist/helpers/complete.ex:48: Alchemist.Helpers.Complete.run/2
    lib/elixir_sense/providers/suggestion.ex:132: ElixirSense.Providers.Suggestion.find_hint_mods_funcs/3
```

I was able to isolate it to a testcase in elixir_sense and confirm the bug there (already fixed on master in https://github.com/elixir-lsp/elixir_sense/pull/30)

@zachdaniel the root issue here was fixed in https://github.com/elixir-lsp/elixir_sense/pull/30/files#diff-d6973eae0d57d757480888d565996cefR207 by properly extracting modules from AST node

**Comment by axelson** [comment]
@lukaszsamson Thanks for looking into and fixing the root cause of this issue! I wonder what I was doing wrong when I tried to reproduce. I'll open a PR to update to the latest version of elixir_sense.
