### ISSUE TITLE
DocumentSymbols Provider should be resistant in the face of compilation errors

### ISSUE THREAD

**Issue by axelson** [elixir-lsp/elixir-ls#167]
Currently if you have a compilation error like:
```Elixir
defmodule A do
  def go do
    :world = Hello.hello(
  end
end
```

There will be quite a few errors output in the terminal, when only the error after `== Compilation error in file lib/a.ex ==` should occur/be reported:

```
[Error - 10:27:17 AM] Request textDocument/documentSymbol failed.
  Message: an exception was raised:
    ** (SyntaxError) nofile:3: unexpected token: end. The "(" at line 2 is missing terminator ")"
        (language_server 0.3.2) lib/language_server/providers/document_symbols.ex:35: ElixirLS.LanguageServer.Providers.DocumentSymbols.list_symbols/1
        (language_server 0.3.2) lib/language_server/providers/document_symbols.ex:20: ElixirLS.LanguageServer.Providers.DocumentSymbols.symbols/3
        (language_server 0.3.2) lib/language_server/server.ex:485: anonymous fn/3 in ElixirLS.LanguageServer.Server.handle_request_async/2
  Code: -32000 

10:27:17.835 [error] Process #PID<0.784.0> raised an exception
** (SyntaxError) nofile:3: unexpected token: end. The "(" at line 2 is missing terminator ")"
    (language_server 0.3.2) lib/language_server/providers/document_symbols.ex:35: ElixirLS.LanguageServer.Providers.DocumentSymbols.list_symbols/1
    (language_server 0.3.2) lib/language_server/providers/document_symbols.ex:20: ElixirLS.LanguageServer.Providers.DocumentSymbols.symbols/3
    (language_server 0.3.2) lib/language_server/server.ex:485: anonymous fn/3 in ElixirLS.LanguageServer.Server.handle_request_async/2
[Error - 10:27:17 AM] Request textDocument/formatting failed.
  Message: an exception was raised:
    ** (SyntaxError) nofile:4: unexpected token: end. The "(" at line 3 is missing terminator ")"
        (elixir 1.10.2) lib/code.ex:645: Code.format_string!/2
        (language_server 0.3.2) lib/language_server/providers/formatting.ex:13: ElixirLS.LanguageServer.Providers.Formatting.format/3
        (language_server 0.3.2) lib/language_server/server.ex:485: anonymous fn/3 in ElixirLS.LanguageServer.Server.handle_request_async/2
  Code: -32000 

10:27:17.977 [error] Process #PID<0.785.0> raised an exception
** (SyntaxError) nofile:4: unexpected token: end. The "(" at line 3 is missing terminator ")"
    (elixir 1.10.2) lib/code.ex:645: Code.format_string!/2
    (language_server 0.3.2) lib/language_server/providers/formatting.ex:13: ElixirLS.LanguageServer.Providers.Formatting.format/3
    (language_server 0.3.2) lib/language_server/server.ex:485: anonymous fn/3 in ElixirLS.LanguageServer.Server.handle_request_async/2
Compiling with Mix env test
Compiling 1 file (.ex)

== Compilation error in file lib/a.ex ==
** (SyntaxError) lib/a.ex:4: unexpected token: end. The "(" at line 3 is missing terminator ")"
    (elixir 1.10.2) lib/kernel/parallel_compiler.ex:304: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/7
[Info  - 10:27:18 AM] Compile took 29 milliseconds
```

Probable approach is to rescue the compilation error in the providers and return a default or empty result. But we should also review how/if this is handled in other existing providers/code.

**Comment by axelson** [comment]
This was fixed in https://github.com/elixir-lsp/elixir-ls/pull/186 but could be further improved by #187
