### ISSUE TITLE
Issue on hover while writing an ExUnit test

### ISSUE THREAD

**Issue by axelson** [elixir-lsp/elixir-ls#17]
Got an exception while writing an exunit test:
```
10:25:32.006 [error] Process #PID<0.13311.4> raised an exception
** (MatchError) no match of right hand side value: nil
    (elixir_sense) lib/elixir_sense/core/parser.ex:67: ElixirSense.Core.Parser.fix_parse_error/3
    (elixir_sense) lib/elixir_sense/core/parser.ex:53: ElixirSense.Core.Parser.string_to_ast/3
    (elixir_sense) lib/elixir_sense/core/parser.ex:18: ElixirSense.Core.Parser.parse_string/4
    (elixir_sense) lib/elixir_sense.ex:43: ElixirSense.docs/3
    (language_server) lib/language_server/providers/hover.ex:7: ElixirLS.LanguageServer.Providers.Hover.hover/3
    (language_server) lib/language_server/server.ex:419: anonymous fn/3 in ElixirLS.LanguageServer.Server.handle_request_async/2
```

    test "get_community_groups/1 returns only the groups viewable to the user", do
      #                                                                       ^ cursor

This partially makes sense because the code is in an uncompilable state. The exception actually appears to be within elixir_sense.

**Comment by lukaszsamson** [comment]
@axelson can you still reproduce this crash after elixir_sense update?

**Comment by axelson** [comment]
I am not able to reproduce this any longer, thanks!
