### ISSUE TITLE
Building core Dialyzer Elixir PLT fails on :elixir_erl.dynamic_form/1, but with an odd file reference.

### ISSUE THREAD

**Issue by brianbowden** [elixir-lsp/elixir-ls#303]
After performing an update to Elixir 1.10.3, ElixirLS keeps thrashing in VS Code as it continually tries to build the PLT. Upon looking at the logs, it is failing on a call to `:elixir_erl.dynamic_form/1`, but it also seemed to be attempting to be accessing a file named `/Users/jose/OSS/elixir/lib/iex/lib/iex/remsh.ex`. This seems odd (I am not `jose`) and looks like a potential problem.

### Environment

* Elixir & Erlang versions (elixir --version): Elixir 1.10.3 and Erlang/OTP 21 (installed via Chocolatey)
* Operating system: Windows 10 (10.0.19041)
* Editor or IDE name (e.g. Emacs/VSCode): VS Code
* LSP Client name: "ElixirLS: Elixir support and debugger"
  
### Troubleshooting

VS Code shut down, `.elixir-ls` removed. Issue persists on all projects.

### Logs

```
[Trace - 11:21:11 AM] Received notification 'window/showMessage'.
Params: {
    "message": "Building core Dialyzer Elixir PLT. This will take a few minutes (often 15+) and can be disabled in the settings.",
    "type": 3
}


[Trace - 11:21:57 AM] Received notification 'window/logMessage'.
Params: {
    "message": "\n11:21:57.332 [error] Task #PID<0.121.0> started from #PID<0.122.0> terminating\n** (FunctionClauseError) no function clause matching in :elixir_erl.dynamic_form/1\n    (elixir 1.10.3) src/elixir_erl.erl:146: :elixir_erl.dynamic_form(%{attributes: [], compile_opts: [], definitions: [{{:expand, 1}, :def, [line: 8], [{[line: 8], [{:node, [line: 8], nil}], [], {:fn, [line: 9], [{:->, [line: 9], [[{:e, [line: 9], nil}], {:case, [line: 10], [{{:., [line: 10], [:rpc, :call]}, [line: 10], [{:node, [line: 10], nil}, IEx.Autocomplete, :expand, [{:e, [line: 10], nil}]]}, [do: [{:->, [line: 11], [[badrpc: {:_, [line: 11], nil}], {:{}, [line: 11], [:no, [], []]}]}, {:->, [line: 12], [[{:r, [line: 12], nil}], {:r, [line: 12], nil}]}]]]}]}]}}]}], deprecated: [], file: \"/Users/jose/OSS/elixir/lib/iex/lib/iex/remsh.ex\", line: 1, module: IEx.Remsh, unreachable: []})\n    (elixir 1.10.3) src/elixir_erl.erl:18: :elixir_erl.debug_info/4\n    dialyzer_utils.erl:116: :dialyzer_utils.get_core_from_beam/2\n    (language_server 0.4.0) lib/language_server/dialyzer/utils.ex:7: ElixirLS.LanguageServer.Dialyzer.Utils.dialyzable?/1\n    (language_server 0.4.0) lib/language_server/dialyzer/utils.ex:36: ElixirLS.LanguageServer.Dialyzer.Utils.expand_references/3\n    (language_server 0.4.0) lib/language_server/dialyzer/manifest.ex:130: anonymous fn/1 in ElixirLS.LanguageServer.Dialyzer.Manifest.build_elixir_plt/0\n    (elixir 1.10.3) lib/enum.ex:3343: Enum.flat_map_list/2\n    (elixir 1.10.3) lib/enum.ex:3344: Enum.flat_map_list/2\nFunction: #Function<1.65931225/0 in ElixirLS.LanguageServer.Dialyzer.Manifest.build_new_manifest/0>\n    Args: []",
    "type": 4
}



11:21:57.332 [error] Task #PID<0.121.0> started from #PID<0.122.0> terminating
** (FunctionClauseError) no function clause matching in :elixir_erl.dynamic_form/1
    (elixir 1.10.3) src/elixir_erl.erl:146: :elixir_erl.dynamic_form(%{attributes: [], compile_opts: [], definitions: [{{:expand, 1}, :def, [line: 8], [{[line: 8], [{:node, [line: 8], nil}], [], {:fn, [line: 9], [{:->, [line: 9], [[{:e, [line: 9], nil}], {:case, [line: 10], [{{:., [line: 10], [:rpc, :call]}, [line: 10], [{:node, [line: 10], nil}, IEx.Autocomplete, :expand, [{:e, [line: 10], nil}]]}, [do: [{:->, [line: 11], [[badrpc: {:_, [line: 11], nil}], {:{}, [line: 11], [:no, [], []]}]}, {:->, [line: 12], [[{:r, [line: 12], nil}], {:r, [line: 12], nil}]}]]]}]}]}}]}], deprecated: [], file: "/Users/jose/OSS/elixir/lib/iex/lib/iex/remsh.ex", line: 1, module: IEx.Remsh, unreachable: []})
    (elixir 1.10.3) src/elixir_erl.erl:18: :elixir_erl.debug_info/4
    dialyzer_utils.erl:116: :dialyzer_utils.get_core_from_beam/2
    (language_server 0.4.0) lib/language_server/dialyzer/utils.ex:7: ElixirLS.LanguageServer.Dialyzer.Utils.dialyzable?/1
    (language_server 0.4.0) lib/language_server/dialyzer/utils.ex:36: ElixirLS.LanguageServer.Dialyzer.Utils.expand_references/3
    (language_server 0.4.0) lib/language_server/dialyzer/manifest.ex:130: anonymous fn/1 in ElixirLS.LanguageServer.Dialyzer.Manifest.build_elixir_plt/0
    (elixir 1.10.3) lib/enum.ex:3343: Enum.flat_map_list/2
    (elixir 1.10.3) lib/enum.ex:3344: Enum.flat_map_list/2
Function: #Function<1.65931225/0 in ElixirLS.LanguageServer.Dialyzer.Manifest.build_new_manifest/0>
    Args: []
[Trace - 11:21:57 AM] Received notification 'window/showMessage'.
Params: {
    "message": "Building core Dialyzer Elixir PLT. This will take a few minutes (often 15+) and can be disabled in the settings.",
    "type": 3
}
```

**Comment by lukaszsamson** [comment]
It's crashing deep in elixir code, most likely due to some stale files. There were some similar raports on 1.10. Can you try solutions from https://github.com/elixir-lsp/elixir-ls/issues/92#issuecomment-573426511 and see if fixes your isse?

**Comment by lukaszsamson** [comment]
Closing due to OP's lack of interest
