### ISSUE TITLE
ElixirLS 0.6.0 does not start because it cannot find module "shelljs"

### ISSUE THREAD

**Issue by crbelaus** [elixir-lsp/elixir-ls#372]
### Environment

* Elixir & Erlang versions (elixir --version): 

        Erlang/OTP 23 [erts-11.0.4] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]
        Elixir 1.11.0-rc.0 (48cee5a) (compiled with Erlang/OTP 21)
  
* Operating system: Windows 10 with WSL 2
* Editor or IDE name (e.g. Emacs/VSCode): VSCode
* Editor Plugin/LSP Client name: JakeBecker.elixir-ls

I am running Windows 10 with WSL-2. This morning I've updated ElixirLS from 0.5.0 to 0.6.0 and it stopped working. I've tried to restart the editor and to remove the `.elixir_ls/` directory, but the extension simply does not work. I've also tried to uninstall and reinstall the extension again with no luck.

Opening `View > Output` does not show an option to select `ElixirLS`, so I thought that it may be because the extension is not running. Opening the `Extension host log` shows an error when activating the extension:

```
[2020-10-04 11:21:48.156] [exthost] [error] Activating extension JakeBecker.elixir-ls failed due to an error:
[2020-10-04 11:21:48.159] [exthost] [error] Error: Cannot find module 'shelljs'
Require stack:
- /home/crbelaus/.vscode-server/extensions/jakebecker.elixir-ls-0.6.0/out/extension.js
- /home/crbelaus/.vscode-server/bin/2af051012b66169dde0c4dfae3f5ef48f787ff69/out/vs/loader.js
- /home/crbelaus/.vscode-server/bin/2af051012b66169dde0c4dfae3f5ef48f787ff69/out/bootstrap-amd.js
- /home/crbelaus/.vscode-server/bin/2af051012b66169dde0c4dfae3f5ef48f787ff69/out/bootstrap-fork.js
	at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
	at Function.Module._load (internal/modules/cjs/loader.js:686:27)
	at Function.t._load (/home/crbelaus/.vscode-server/bin/2af051012b66169dde0c4dfae3f5ef48f787ff69/out/vs/server/remoteExtensionHostProcess.js:1070:268)
	at Function.i._load (/home/crbelaus/.vscode-server/bin/2af051012b66169dde0c4dfae3f5ef48f787ff69/out/vs/server/remoteExtensionHostProcess.js:1039:981)
	at Function.n._load (/home/crbelaus/.vscode-server/bin/2af051012b66169dde0c4dfae3f5ef48f787ff69/out/vs/server/remoteExtensionHostProcess.js:1036:303)
	at Module.require (internal/modules/cjs/loader.js:848:19)
	at require (internal/modules/cjs/helpers.js:74:18)
	at Object.<anonymous> (/home/crbelaus/.vscode-server/extensions/jakebecker.elixir-ls-0.6.0/out/extension.js:10:15)
	at Module._compile (internal/modules/cjs/loader.js:955:30)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
	at Module.load (internal/modules/cjs/loader.js:811:32)
	at Function.Module._load (internal/modules/cjs/loader.js:723:14)
	at Function.t._load (/home/crbelaus/.vscode-server/bin/2af051012b66169dde0c4dfae3f5ef48f787ff69/out/vs/server/remoteExtensionHostProcess.js:1070:268)
	at Function.i._load (/home/crbelaus/.vscode-server/bin/2af051012b66169dde0c4dfae3f5ef48f787ff69/out/vs/server/remoteExtensionHostProcess.js:1039:981)
	at Function.n._load (/home/crbelaus/.vscode-server/bin/2af051012b66169dde0c4dfae3f5ef48f787ff69/out/vs/server/remoteExtensionHostProcess.js:1036:303)
	at Module.require (internal/modules/cjs/loader.js:848:19)
	at require (internal/modules/cjs/helpers.js:74:18)
	at Function.s [as __$__nodeRequire] (/home/crbelaus/.vscode-server/bin/2af051012b66169dde0c4dfae3f5ef48f787ff69/out/vs/loader.js:33:604)
	at p._loadCommonJSModule (/home/crbelaus/.vscode-server/bin/2af051012b66169dde0c4dfae3f5ef48f787ff69/out/vs/server/remoteExtensionHostProcess.js:1041:241)
	at p._doActivateExtension (/home/crbelaus/.vscode-server/bin/2af051012b66169dde0c4dfae3f5ef48f787ff69/out/vs/server/remoteExtensionHostProcess.js:939:625)
	at p._activateExtension (/home/crbelaus/.vscode-server/bin/2af051012b66169dde0c4dfae3f5ef48f787ff69/out/vs/server/remoteExtensionHostProcess.js:938:708)
	at Object.actualActivateExtension (/home/crbelaus/.vscode-server/bin/2af051012b66169dde0c4dfae3f5ef48f787ff69/out/vs/server/remoteExtensionHostProcess.js:936:453)
	at h._activateExtension (/home/crbelaus/.vscode-server/bin/2af051012b66169dde0c4dfae3f5ef48f787ff69/out/vs/server/remoteExtensionHostProcess.js:668:731)
	at /home/crbelaus/.vscode-server/bin/2af051012b66169dde0c4dfae3f5ef48f787ff69/out/vs/server/remoteExtensionHostProcess.js:668:409
	at Array.map (<anonymous>)
	at h._activateExtensions (/home/crbelaus/.vscode-server/bin/2af051012b66169dde0c4dfae3f5ef48f787ff69/out/vs/server/remoteExtensionHostProcess.js:668:397)
	at h.activateByEvent (/home/crbelaus/.vscode-server/bin/2af051012b66169dde0c4dfae3f5ef48f787ff69/out/vs/server/remoteExtensionHostProcess.js:665:919)
	at p._activateByEvent (/home/crbelaus/.vscode-server/bin/2af051012b66169dde0c4dfae3f5ef48f787ff69/out/vs/server/remoteExtensionHostProcess.js:937:300)
	at /home/crbelaus/.vscode-server/bin/2af051012b66169dde0c4dfae3f5ef48f787ff69/out/vs/server/remoteExtensionHostProcess.js:946:242
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
```

**Comment by crbelaus** [comment]
This seems to affect only the VSCode extension so I am closing this issue as a duplicate of elixir-lsp/vscode-elixir-ls#145
