### ISSUE TITLE
Server crashing for MatchError about :wx and wx.app (no such file or directory)

### ISSUE THREAD

**Issue by sanjibukai** [elixir-lsp/elixir-ls#387]
### Environment

* Elixir & Erlang versions (elixir --version): Elixir 1.11 Erlang 23.1.1
* Operating system: Linux Alpine 3.12 (Docker image from hexpm `hexpm/elixir:1.11.0-erlang-23.1.1-alpine-3.12.0` )
* Editor or IDE name (e.g. Emacs/VSCode): VSCode 1.50
* Editor Plugin/LSP Client name: vscode-elixir-ls

### Troubleshooting

- [X] Restart your editor (which will restart ElixirLS) sometimes fixes issues

-> Done without success
- [X] Stop your editor, remove the entire `.elixir_ls` directory, then restart your editor
  * NOTE: This will cause you to have to re-run the dialyzer build for your project

-> Done without success

## Comment

I'm using VSCode with Remote Connection to container (`.devcontainer` setup).
But everything was working fine until I updated to this latest image `hexpm/elixir:1.11.0-erlang-23.1.1-alpine-3.12.0`.
Before I was using `elixir:1.10-alpine`.

Does `:wx` actually referring to the UI library?

### Logs

```
[Warn  - 7:11:16 AM] ** (MatchError) no match of right hand side value: {:error, {:wx, {'no such file or directory', 'wx.app'}}}
    (language_server 0.6.0) lib/language_server/cli.ex:9: ElixirLS.LanguageServer.CLI.main/0
    (stdlib 3.13.2) erl_eval.erl:680: :erl_eval.do_apply/6
    (elixir 1.11.0) lib/code.ex:341: Code.eval_string_with_error_handling/3
[Info  - 7:11:16 AM] Connection to server got closed. Server will restart.
[Trace - 7:11:16 AM] Sending request 'initialize - (0)'.
Params: {
    "processId": 153,
    "clientInfo": {
        "name": "vscode",
        "version": "1.50.0"
    },
    "rootPath": "/app",
    "rootUri": "file:///app",
    "capabilities": {
        "workspace": {
            "applyEdit": true,
            "workspaceEdit": {
                "documentChanges": true,
                "resourceOperations": [
                    "create",
                    "rename",
                    "delete"
                ],
                "failureHandling": "textOnlyTransactional"
            },
            "didChangeConfiguration": {
                "dynamicRegistration": true
            },
            "didChangeWatchedFiles": {
                "dynamicRegistration": true
            },
            "symbol": {
                "dynamicRegistration": true,
                "symbolKind": {
                    "valueSet": [
                        1,
                        2,
                        3,
                        4,
                        5,
                        6,
                        7,
                        8,
                        9,
                        10,
                        11,
                        12,
                        13,
                        14,
                        15,
                        16,
                        17,
                        18,
                        19,
                        20,
                        21,
                        22,
                        23,
                        24,
                        25,
                        26
                    ]
                }
            },
            "executeCommand": {
                "dynamicRegistration": true
            },
            "configuration": true,
            "workspaceFolders": true
        },
        "textDocument": {
            "publishDiagnostics": {
                "relatedInformation": true,
                "versionSupport": false,
                "tagSupport": {
                    "valueSet": [
                        1,
                        2
                    ]
                }
            },
            "synchronization": {
                "dynamicRegistration": true,
                "willSave": true,
                "willSaveWaitUntil": true,
                "didSave": true
            },
            "completion": {
                "dynamicRegistration": true,
                "contextSupport": true,
                "completionItem": {
                    "snippetSupport": true,
                    "commitCharactersSupport": true,
                    "documentationFormat": [
                        "markdown",
                        "plaintext"
                    ],
                    "deprecatedSupport": true,
                    "preselectSupport": true,
                    "tagSupport": {
                        "valueSet": [
                            1
                        ]
                    }
                },
                "completionItemKind": {
                    "valueSet": [
                        1,
                        2,
                        3,
                        4,
                        5,
                        6,
                        7,
                        8,
                        9,
                        10,
                        11,
                        12,
                        13,
                        14,
                        15,
                        16,
                        17,
                        18,
                        19,
                        20,
                        21,
                        22,
                        23,
                        24,
                        25
                    ]
                }
            },
            "hover": {
                "dynamicRegistration": true,
                "contentFormat": [
                    "markdown",
                    "plaintext"
                ]
            },
            "signatureHelp": {
                "dynamicRegistration": true,
                "signatureInformation": {
                    "documentationFormat": [
                        "markdown",
                        "plaintext"
                    ],
                    "parameterInformation": {
                        "labelOffsetSupport": true
                    }
                },
                "contextSupport": true
            },
            "definition": {
                "dynamicRegistration": true,
                "linkSupport": true
            },
            "references": {
                "dynamicRegistration": true
            },
            "documentHighlight": {
                "dynamicRegistration": true
            },
            "documentSymbol": {
                "dynamicRegistration": true,
                "symbolKind": {
                    "valueSet": [
                        1,
                        2,
                        3,
                        4,
                        5,
                        6,
                        7,
                        8,
                        9,
                        10,
                        11,
                        12,
                        13,
                        14,
                        15,
                        16,
                        17,
                        18,
                        19,
                        20,
                        21,
                        22,
                        23,
                        24,
                        25,
                        26
                    ]
                },
                "hierarchicalDocumentSymbolSupport": true
            },
            "codeAction": {
                "dynamicRegistration": true,
                "isPreferredSupport": true,
                "codeActionLiteralSupport": {
                    "codeActionKind": {
                        "valueSet": [
                            "",
                            "quickfix",
                            "refactor",
                            "refactor.extract",
                            "refactor.inline",
                            "refactor.rewrite",
                            "source",
                            "source.organizeImports"
                        ]
                    }
                }
            },
            "codeLens": {
                "dynamicRegistration": true
            },
            "formatting": {
                "dynamicRegistration": true
            },
            "rangeFormatting": {
                "dynamicRegistration": true
            },
            "onTypeFormatting": {
                "dynamicRegistration": true
            },
            "rename": {
                "dynamicRegistration": true,
                "prepareSupport": true
            },
            "documentLink": {
                "dynamicRegistration": true,
                "tooltipSupport": true
            },
            "typeDefinition": {
                "dynamicRegistration": true,
                "linkSupport": true
            },
            "implementation": {
                "dynamicRegistration": true,
                "linkSupport": true
            },
            "colorProvider": {
                "dynamicRegistration": true
            },
            "foldingRange": {
                "dynamicRegistration": true,
                "rangeLimit": 5000,
                "lineFoldingOnly": true
            },
            "declaration": {
                "dynamicRegistration": true,
                "linkSupport": true
            },
            "selectionRange": {
                "dynamicRegistration": true
            }
        },
        "window": {
            "workDoneProgress": true
        }
    },
    "trace": "verbose",
    "workspaceFolders": [
        {
            "uri": "file:///app",
            "name": "app"
        }
    ]
}


[Trace - 7:11:17 AM] Received notification 'window/logMessage'.
Params: {
    "message": "\n07:11:17.291 [info]  Application hipe exited: :stopped",
    "type": 4
}



07:11:17.291 [info]  Application hipe exited: :stopped
[Trace - 7:11:17 AM] Received notification 'window/logMessage'.
Params: {
    "message": "** (MatchError) no match of right hand side value: {:error, {:wx, {'no such file or directory', 'wx.app'}}}\n    (language_server 0.6.0) lib/language_server/cli.ex:9: ElixirLS.LanguageServer.CLI.main/0\n    (stdlib 3.13.2) erl_eval.erl:680: :erl_eval.do_apply/6\n    (elixir 1.11.0) lib/code.ex:341: Code.eval_string_with_error_handling/3",
    "type": 2
}


[Warn  - 7:11:17 AM] ** (MatchError) no match of right hand side value: {:error, {:wx, {'no such file or directory', 'wx.app'}}}
    (language_server 0.6.0) lib/language_server/cli.ex:9: ElixirLS.LanguageServer.CLI.main/0
    (stdlib 3.13.2) erl_eval.erl:680: :erl_eval.do_apply/6
    (elixir 1.11.0) lib/code.ex:341: Code.eval_string_with_error_handling/3
[Error - 7:11:17 AM] Connection to server got closed. Server will not be restarted.

```

**Comment by lukaszsamson** [comment]
elixir-ls `:language_server` app depends on OTP `:dialyzer` app which in turn depends on `:wx` OTP app. Similarly `:elixir_ls_debugger` depends on `:debugger` which also depends on `:wx`. Both `:dialyzer` and `:debugger` deps are included in `extra_applications`. While they were not included before, elixir 1.11 started raising warnings about missing dependences. This dependency is a design flaw in OTP itself which is unlikely to be fixed soon. We can look for a way to avoid getting warnings while not starting `:wx` app. Before that happens I suggest running on complete OTP distribution with `:wx` app.

**Comment by altdsoy** [comment]
Thanks for the feedback..

**Comment by altdsoy** [comment]
On my side I tested all the following images (only changing that single line)..
```Dockerfile
# FROM hexpm/elixir:1.11.0-erlang-23.0-alpine-3.12.0
# FROM hexpm/elixir:1.11.0-erlang-22.3.4.11-alpine-3.12.0
# FROM hexpm/elixir:1.10.4-erlang-23.1.1-alpine-3.12.0
# FROM hexpm/elixir:1.10.4-erlang-22.3.4.11-alpine-3.12.0
# FROM hexpm/elixir:1.11.0-erlang-23.0.2-alpine-3.11.6
# FROM hexpm/elixir:1.11.0-erlang-22.3.4.3-alpine-3.11.6
# FROM hexpm/elixir:1.10.4-erlang-23.0.2-alpine-3.11.6
FROM hexpm/elixir:1.10.4-erlang-22.3.4.3-alpine-3.11.6
# FROM elixir:1.10-alpine
```
ElixirLS keeps crashing with that same error mentioned above..
Since I doubt that ElixirLS is broken on all of these images I wonder what is broken elsewhere.. :thinking:
