### ISSUE TITLE
Not possible to build after recent change

### ISSUE THREAD

**Issue by mattiaslundberg** [elixir-lsp/elixir-ls#413]
### Environment

* Elixir & Erlang versions (elixir --version).
```
Erlang/OTP 23 [erts-11.1.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Elixir 1.11.2 (compiled with Erlang/OTP 23)
```
* Operating system: Ubuntu 20.04 
* Editor or IDE name (e.g. Emacs/VSCode): Not relevant
* Editor Plugin/LSP Client name: Not relevant

After merging https://github.com/elixir-lsp/elixir-ls/pull/411 it's no longer possible to build a release of elixir-ls:

```
$ mix elixir_ls.release -o ./bin 
warning: Building with Erlang/OTP 23. Make sure to build with OTP 21 if publishing the compiled packages because modules built with higher versions are not backwards-compatible.

** (ErlangError) Erlang error: {:invalid_status, :compile}
    lib/mix/tasks/archive/build.deps.ex:78: anonymous fn/3 in Mix.Tasks.Archive.Build.Deps.list/1
    (elixir 1.11.2) lib/enum.ex:1399: Enum."-map/2-lists^map/1-0-"/2
    (elixir 1.11.2) lib/enum.ex:1399: Enum."-map/2-lists^map/1-0-"/2
    lib/mix/tasks/archive/build.deps.ex:53: Mix.Tasks.Archive.Build.Deps.build_archives/1
    (mix 1.11.2) lib/mix/task.ex:394: Mix.Task.run_task/3
    lib/mix.tasks.elixir_ls.release.ex:17: Mix.Tasks.ElixirLs.Release.run/1
    (mix 1.11.2) lib/mix/task.ex:394: Mix.Task.run_task/3
    (mix 1.11.2) lib/mix/cli.ex:84: Mix.CLI.run_task/2
```

**Comment by lukaszsamson** [comment]
Have you run `mix deps.get && mix compile`? I'm running releases with no problems. If those steps don't help please try to find out which dependancy fails. You can do that e.g. by adding `IO.inspect` in `deps/mix_task_archive_deps/lib/mix/tasks/archive/build.deps.ex:78`

**Comment by mattiaslundberg** [comment]
Thanks for the quick reply!

I've tried `mix deps.get && mix compile` even after running a `mix deps.clean --all` but still having issues. Adding the debug it looks like it's `stream_data` that fails. The full dependency information looks like this:
```
      %Mix.Dep{
        app: :stream_data,
        deps: [],
        extra: [],
        from: "/home/mattias/.elixir-ls/apps/language_server/mix.exs",
        manager: nil,
        opts: [
          env: :prod,
          repo: "hexpm",
          hex: "stream_data",
          build: "/home/mattias/.elixir-ls/_build/shared/lib/stream_data",
          dest: "/home/mattias/.elixir-ls/deps/stream_data",
          only: :test
        ],
        requirement: "~> 0.5.0",
        scm: Hex.SCM,
        status: {:ok, nil},
        system_env: [],
        top_level: false
      }
 ```

**Comment by mattiaslundberg** [comment]
Hmm, seeing it a second time in the list, in that case `status` is set to `:compile`:
```
  %Mix.Dep{
    app: :stream_data,
    deps: [],
    extra: [],
    from: "/home/mattias/.elixir-ls/apps/language_server/mix.exs",
    manager: :mix,
    opts: [
      lock: {:hex, :stream_data, "0.5.0",
       "b27641e58941685c75b353577dc602c9d2c12292dd84babf506c2033cd97893e",
       [:mix], [], "hexpm",
       "012bd2eec069ada4db3411f9115ccafa38540a3c78c4c0349f151fc761b9e271"},
      env: :prod,
      repo: "hexpm",
      hex: "stream_data",
      build: "/home/mattias/.elixir-ls/_build/shared/lib/stream_data",
      dest: "/home/mattias/.elixir-ls/deps/stream_data",
      only: :test
    ],
    requirement: "~> 0.5.0",
    scm: Hex.SCM,
    status: :compile,
    system_env: [],
    top_level: false
  },
```

**Comment by lukaszsamson** [comment]
Oh I can reproduce it too after `rm -rf deps _build`. It's a bug in https://github.com/JakeBecker/mix_task_archive_deps not respecting `only: :test` on `stream_data`. We'd need to fork that lib and fix it but as a workaround run `mix test` to compile `stream_data`.

**Comment by mattiaslundberg** [comment]
Great find!

As a temporary workaround it's possible to just run compilation for the test environment before building the release: `MIX_ENV=test mix compile` and it builds correctly.
