### ISSUE TITLE
CI occasionally fails due to warnings as errors

### ISSUE THREAD

**Issue by lukaszsamson** [elixir-lsp/elixir-ls#446]
```
2020-12-25T19:47:03.6540235Z Generated language_server app
2020-12-25T19:47:03.6549508Z Excluding tags: [pending: true]
2020-12-25T19:47:03.6550409Z 
2020-12-25T19:47:10.1930898Z ..........................................................................
2020-12-25T19:47:10.1931316Z 
2020-12-25T19:47:10.1935271Z   1) test reports build diagnostics on external resources (ElixirLS.LanguageServer.ServerTest)
2020-12-25T19:47:10.1938473Z ##[error]     test/server_test.exs:988
2020-12-25T19:47:10.1940892Z      Assertion failed, no matching message after 1000ms
2020-12-25T19:47:10.1941578Z      The following variables were pinned:
2020-12-25T19:47:10.1943953Z        error_file = "file:///home/runner/work/elixir-ls/elixir-ls/apps/elixir_ls_utils/test/tmp/ElixirLS.LanguageServer.ServerTest/test%20reports%20build%20diagnostics%20on%20external%20resources/lib/template.eex"
2020-12-25T19:47:10.1945468Z      Showing 1 of 1 message in the mailbox
2020-12-25T19:47:10.1947467Z      code: assert_receive notification("textDocument/publishDiagnostics", %{"uri" => ^error_file, "diagnostics" => [%{"message" => "(SyntaxError) syntax error before: ','" <> _, "range" => %{"end" => %{"line" => 1}, "start" => %{"line" => 1}}, "severity" => 1}]})
2020-12-25T19:47:10.1948667Z      mailbox:
2020-12-25T19:47:10.1950210Z        pattern: notification("textDocument/publishDiagnostics", %{"uri" => ^error_file, "diagnostics" => [%{"message" => "(SyntaxError) syntax error before: ','" <> _, "range" => %{"end" => %{"line" => 1}, "start" => %{"line" => 1}}, "severity" => 1}]})
2020-12-25T19:47:10.1951340Z        value:   %{
2020-12-25T19:47:10.1951731Z                   "id" => 1,
2020-12-25T19:47:10.1952134Z                   "jsonrpc" => "2.0",
2020-12-25T19:47:10.1952569Z                   "result" => %{
2020-12-25T19:47:10.1953029Z                     "capabilities" => %{
2020-12-25T19:47:10.1953602Z                       "codeLensProvider" => %{
2020-12-25T19:47:10.1954220Z                         "resolveProvider" => false
2020-12-25T19:47:10.1954709Z                       },
2020-12-25T19:47:10.1955231Z                       "completionProvider" => %{
2020-12-25T19:47:10.1955882Z                         "triggerCharacters" => [".", "@", "&",
2020-12-25T19:47:10.1956407Z                          "%", "^", ":", "!"]
2020-12-25T19:47:10.1956787Z                       },
2020-12-25T19:47:10.1957317Z                       "definitionProvider" => true,
2020-12-25T19:47:10.1958166Z                       "documentFormattingProvider" => true,
2020-12-25T19:47:10.1959189Z                       "documentOnTypeFormattingProvider" => %{
2020-12-25T19:47:10.1960101Z                         "firstTriggerCharacter" => "\n"
2020-12-25T19:47:10.1960660Z                       },
2020-12-25T19:47:10.1961233Z                       "documentSymbolProvider" => true,
2020-12-25T19:47:10.1962007Z                       "executeCommandProvider" => %{
2020-12-25T19:47:10.1963161Z                         "commands" => ["spec:AHiny5GhpEaUlQSpkzrxOGPUkJR_D-W4"]
2020-12-25T19:47:10.1963867Z                       },
2020-12-25T19:47:10.1964348Z                       "hoverProvider" => true,
2020-12-25T19:47:10.1965024Z                       "implementationProvider" => true,
2020-12-25T19:47:10.1965719Z                       "macroExpansion" => true,
2020-12-25T19:47:10.3549938Z                       "referencesProvider" => true,
2020-12-25T19:47:10.3551356Z                       "signatureHelpProvider" => %{
2020-12-25T19:47:10.3552425Z                         "triggerCharacters" => ["("]
2020-12-25T19:47:10.3553210Z                       },
2020-12-25T19:47:10.3553962Z                       "textDocumentSync" => %{
2020-12-25T19:47:10.3554749Z                         "change" => 2,
2020-12-25T19:47:10.3555497Z                         "openClose" => true,
2020-12-25T19:47:10.3556371Z                         "save" => %{"includeText" => true}
2020-12-25T19:47:10.3557096Z                       },
2020-12-25T19:47:10.3557787Z                       "workspace" => %{
2020-12-25T19:47:10.3558627Z                         "workspaceFolders" => %{
2020-12-25T19:47:10.3559652Z                           "changeNotifications" => false,
2020-12-25T19:47:10.3560623Z                           "supported" => false
2020-12-25T19:47:10.3561303Z                         }
2020-12-25T19:47:10.3561864Z                       },
2020-12-25T19:47:10.3562786Z                       "workspaceSymbolProvider" => true
2020-12-25T19:47:10.3563696Z                     },
2020-12-25T19:47:10.3564339Z                     "serverInfo" => %{
2020-12-25T19:47:10.3565110Z                       "name" => "ElixirLS",
2020-12-25T19:47:10.3565831Z                       "version" => "0.6.2"
2020-12-25T19:47:10.3566432Z                     }
2020-12-25T19:47:10.3566985Z                   }
2020-12-25T19:47:10.3567507Z                 }
2020-12-25T19:47:10.3568111Z      stacktrace:
2020-12-25T19:47:10.3570398Z        test/server_test.exs:994: anonymous fn/1 in ElixirLS.LanguageServer.ServerTest."test reports build diagnostics on external resources"/1
2020-12-25T19:47:10.3572384Z        (elixir 1.11.2) lib/file.ex:1552: File.cd!/2
2020-12-25T19:47:10.3573919Z        (elixir_ls_utils 0.6.2) test/support/mix_test.case.ex:78: ElixirLS.Utils.MixTest.Case.in_fixture/4
2020-12-25T19:47:10.3575442Z        test/server_test.exs:989: (test)
2020-12-25T19:47:10.3575972Z 
2020-12-25T19:47:10.4267330Z ....
2020-12-25T19:47:10.4267899Z 19:47:10.425 [error] Process #PID<0.1642.0> raised an exception
2020-12-25T19:47:10.4268719Z ** (ErlangError) Erlang error: :terminated
2020-12-25T19:47:10.4270268Z     (stdlib 3.8.2.4) :io.put_chars(:standard_io, :unicode, ["\n== Compilation error in file lib/has_error.ex ==\n", ["** (MatchError) no match of right hand side value: {:error, :enoent}", 10, "    (elixir 1.11.2) lib/kernel/parallel_compiler.ex:314: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/7\n"]])
2020-12-25T19:47:10.4272254Z     (elixir 1.11.2) lib/kernel/parallel_compiler.ex:557: Kernel.ParallelCompiler.wait_for_messages/7
2020-12-25T19:47:10.4273547Z     (elixir 1.11.2) lib/kernel/parallel_compiler.ex:149: Kernel.ParallelCompiler.spawn_workers/3
2020-12-25T19:47:10.4274716Z     (mix 1.11.2) lib/mix/compilers/elixir.ex:94: Mix.Compilers.Elixir.compile/6
2020-12-25T19:47:10.4275568Z     (mix 1.11.2) lib/mix/task.ex:394: Mix.Task.run_task/3
2020-12-25T19:47:10.4276388Z     (mix 1.11.2) lib/mix/tasks/compile.all.ex:90: Mix.Tasks.Compile.All.run_compiler/2
2020-12-25T19:47:10.4277471Z     (mix 1.11.2) lib/mix/tasks/compile.all.ex:70: Mix.Tasks.Compile.All.compile/4
2020-12-25T19:47:10.4278552Z     (mix 1.11.2) lib/mix/tasks/compile.all.ex:57: Mix.Tasks.Compile.All.with_logger_app/2
2020-12-25T19:47:10.4279583Z     (mix 1.11.2) lib/mix/tasks/compile.all.ex:35: Mix.Tasks.Compile.All.run/1
2020-12-25T19:47:10.4280362Z     (mix 1.11.2) lib/mix/task.ex:394: Mix.Task.run_task/3
2020-12-25T19:47:10.4281082Z     (mix 1.11.2) lib/mix/tasks/compile.ex:119: Mix.Tasks.Compile.run/1
2020-12-25T19:47:10.4281791Z     (mix 1.11.2) lib/mix/task.ex:394: Mix.Task.run_task/3
2020-12-25T19:47:10.4282855Z     (language_server 0.6.2) lib/language_server/build.ex:199: ElixirLS.LanguageServer.Build.compile/0
2020-12-25T19:47:10.4284643Z     (language_server 0.6.2) lib/language_server/build.ex:29: anonymous fn/3 in ElixirLS.LanguageServer.Build.build/3
2020-12-25T19:47:10.4285975Z     (stdlib 3.8.2.4) timer.erl:166: :timer.tc/1
2020-12-25T19:47:10.4287093Z     (language_server 0.6.2) lib/language_server/build.ex:12: anonymous fn/3 in ElixirLS.LanguageServer.Build.build/3
2020-12-25T19:47:10.4288260Z     (kernel 6.3.1.3) global.erl:430: :global.trans/4
2020-12-25T19:47:10.5569111Z warning: redefining module ElixirLS.LanguageServer.Mixfile (current version defined in memory)
2020-12-25T19:47:10.5583569Z ##[warning]  mix.exs:1
2020-12-25T19:47:10.5587509Z 
2020-12-25T19:47:10.5887785Z 
2020-12-25T19:47:10.5889261Z 
2020-12-25T19:47:10.5891624Z   2) test finds references in non-umbrella project (ElixirLS.LanguageServer.ServerTest)
2020-12-25T19:47:10.5894472Z ##[error]     test/server_test.exs:1035
2020-12-25T19:47:10.5896722Z      ** (CompileError) mix.exs:1: cannot define module ElixirLS.LanguageServer.Mixfile because it is currently being defined in mix.exs:1
2020-12-25T19:47:10.5898411Z      code: in_fixture(__DIR__, "references", fn ->
2020-12-25T19:47:10.5899175Z      stacktrace:
2020-12-25T19:47:10.5900025Z        (elixir 1.11.2) src/elixir_module.erl:326: :elixir_module.build/3
2020-12-25T19:47:10.5901046Z        (elixir 1.11.2) src/elixir_module.erl:101: :elixir_module.compile/5
2020-12-25T19:47:10.5902019Z        (stdlib 3.8.2.4) erl_eval.erl:680: :erl_eval.do_apply/6
2020-12-25T19:47:10.5902904Z        (elixir 1.11.2) src/elixir.erl:280: :elixir.recur_eval/3
2020-12-25T19:47:10.5903841Z        (elixir 1.11.2) src/elixir.erl:265: :elixir.eval_forms/3
2020-12-25T19:47:10.5904858Z        (elixir 1.11.2) src/elixir_compiler.erl:46: :elixir_compiler.eval_forms/3
2020-12-25T19:47:10.5906177Z        (elixir 1.11.2) src/elixir_lexical.erl:15: :elixir_lexical.run/3
2020-12-25T19:47:10.5907255Z        (elixir 1.11.2) src/elixir_compiler.erl:18: :elixir_compiler.quoted/3
2020-12-25T19:47:10.5908267Z        (elixir 1.11.2) lib/code.ex:1172: Code.compile_file/2
2020-12-25T19:47:10.5909693Z        (elixir_ls_utils 0.6.2) test/support/mix_test.case.ex:136: anonymous fn/2 in ElixirLS.Utils.MixTest.Case.restore_project_stack!/1
2020-12-25T19:47:10.5926251Z        (elixir 1.11.2) lib/enum.ex:2181: Enum."-reduce/3-lists^foldl/2-0-"/3
2020-12-25T19:47:10.5927473Z        (elixir_ls_utils 0.6.2) test/support/mix_test.case.ex:130: ElixirLS.Utils.MixTest.Case.restore_project_stack!/1
2020-12-25T19:47:10.5929123Z        (elixir_ls_utils 0.6.2) test/support/mix_test.case.ex:77: ElixirLS.Utils.MixTest.Case.in_fixture/4
2020-12-25T19:47:10.5931245Z        test/server_test.exs:1036: (test)
2020-12-25T19:47:10.5931604Z 
2020-12-25T19:47:10.5960424Z .Compilation failed due to warnings while using the --warnings-as-errors option
2020-12-25T19:47:10.5962380Z warning: Unable to write to the device: :terminated
2020-12-25T19:47:10.5964461Z ##[warning]  (elixir_ls_utils 0.6.2) lib/wire_protocol.ex:23: ElixirLS.Utils.WireProtocol.send/1
2020-12-25T19:47:10.5977668Z   (kernel 6.3.1.3) global.erl:430: :global.trans/4
2020-12-25T19:47:10.5978596Z 
2020-12-25T19:47:16.9133202Z ............................................................................................................................Content-Length: 192
2020-12-25T19:47:16.9133964Z 
2020-12-25T19:53:06.0063810Z {"jsonrpc":"2.0","method":"window/showMessage","params":{"message":"Building core Dialyzer Elixir PLT. This will take a few minutes (often 15+) and can be disabled in the settings.","type":3}}Content-Length: 151
2020-12-25T19:53:06.0064898Z 
2020-12-25T19:53:47.8837870Z {"jsonrpc":"2.0","method":"window/showMessage","params":{"message":"Saved Elixir PLT to /home/runner/.mix/elixir-ls-21.3.8.18_elixir-1.11.2","type":3}}......................
2020-12-25T19:53:47.8839412Z 
2020-12-25T19:53:47.8840428Z Finished in 404.9 seconds
2020-12-25T19:53:47.8841011Z 1 property, 226 tests, 2 failures
2020-12-25T19:53:47.8841380Z 
2020-12-25T19:53:47.8841819Z Randomized with seed 941984
2020-12-25T19:53:47.9075874Z ** (exit) 1
2020-12-25T19:53:47.9082165Z     (mix 1.11.2) lib/mix/tasks/cmd.ex:64: Mix.Tasks.Cmd.run/1
2020-12-25T19:53:47.9084285Z     (mix 1.11.2) lib/mix/task.ex:394: Mix.Task.run_task/3
2020-12-25T19:53:47.9085213Z     (mix 1.11.2) lib/mix/project.ex:352: Mix.Project.in_project/4
2020-12-25T19:53:47.9085905Z     (elixir 1.11.2) lib/file.ex:1552: File.cd!/2
2020-12-25T19:53:47.9086549Z     (mix 1.11.2) lib/mix/task.ex:511: anonymous fn/4 in Mix.Task.recur/1
2020-12-25T19:53:47.9087858Z     (elixir 1.11.2) lib/enum.ex:2181: Enum."-reduce/3-lists^foldl/2-0-"/3
2020-12-25T19:53:47.9088511Z     (mix 1.11.2) lib/mix/task.ex:510: Mix.Task.recur/1
2020-12-25T19:53:47.9089447Z     (mix 1.11.2) lib/mix/project_stack.ex:181: Mix.ProjectStack.recur/1
2020-12-25T19:53:47.9108846Z ##[error]Process completed with exit code 1.
2020-12-25T19:53:47.9202493Z Post job cleanup.
2020-12-25T19:53:48.0347575Z [command]/usr/bin/git version
2020-12-25T19:53:48.0408787Z git version 2.29.2
2020-12-25T19:53:48.0459958Z [command]/usr/bin/git config --local --name-only --get-regexp core\.sshCommand
2020-12-25T19:53:48.0508332Z [command]/usr/bin/git submodule foreach --recursive git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :
2020-12-25T19:53:48.0802101Z [command]/usr/bin/git config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader
2020-12-25T19:53:48.0834082Z http.https://github.com/.extraheader
2020-12-25T19:53:48.0845098Z [command]/usr/bin/git config --local --unset-all http.https://github.com/.extraheader
2020-12-25T19:53:48.0891239Z [command]/usr/bin/git submodule foreach --recursive git config --local --name-only --get-regexp 'http\.https\:\/\/github\.com\/\.extraheader' && git config --local --unset-all 'http.https://github.com/.extraheader' || :
2020-12-25T19:53:48.1250307Z Cleaning up orphan processes
```

**Comment by axelson** [comment]
Is this still an issue? I've been unable to reproduce it recently. #488 fixes all the test problems that I can currently find, both locally and in CI.

**Comment by lukaszsamson** [comment]
I decided to turn this setting off. We can't easily avoid warnings
