### ISSUE TITLE
ElixirLS is crashing on ElixirLS.LanguageServer.Server.handle_notification/2

### ISSUE THREAD

**Issue by gjsduarte** [elixir-lsp/elixir-ls#474]
### Environment

* Elixir & Erlang versions (elixir --version): 
 **Erlang/OTP 23 [erts-11.1.5] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]
 Elixir 1.10.3 (compiled with Erlang/OTP 21)**
* Operating system: 
**Mac OS Big Sur**
* Editor or IDE name (e.g. Emacs/VSCode): 
**VSCode**
* Editor Plugin/LSP Client name:
**ElixirLS**

### Troubleshooting

I'm able to recover by restarting the editor, but this issue repeats every now and then.

### Logs

```
(FunctionClauseError) no function clause matching in anonymous fn/2 in ElixirLS.LanguageServer.Server.handle_notification/2
```

**Comment by doughsay** [comment]
yeah, me too;  just came here to report this.

```elixir
16:25:40.654 [error] GenServer ElixirLS.LanguageServer.Server terminating
** (FunctionClauseError) no function clause matching in anonymous fn/2 in ElixirLS.LanguageServer.Server.handle_notification/2
    (language_server 0.6.4) lib/language_server/server.ex:402: anonymous fn(%{"type" => 2, "uri" => "git:/<redacted>"}, %{"file:///<redacted>" => %ElixirLS.LanguageServer.SourceFile{dirty?: false, text: "<redacted> (truncated)
[Warn  - 4:25:40 PM] ** (exit) exited in: GenServer.call(ElixirLS.LanguageServer.JsonRpc, {:packet, %{"id" => 822, "jsonrpc" => "2.0", "method" => "textDocument/hover", "params" => %{"position" => %{"character" => 0, "line" => 23}, "textDocument" => %{"uri" => "file:///<redacted>"}}}}, 5000)
    ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
    (elixir 1.11.3) lib/gen_server.ex:1017: GenServer.call/3
    (elixir 1.11.3) lib/stream.ex:441: anonymous fn/4 in Stream.each/2
    (elixir 1.11.3) lib/stream.ex:1449: Stream.do_element_resource/6
    (elixir 1.11.3) lib/stream.ex:1609: Enumerable.Stream.do_each/4
    (elixir 1.11.3) lib/stream.ex:649: Stream.run/1
    (stdlib 3.14) erl_eval.erl:680: :erl_eval.do_apply/6
[Info  - 4:25:43 PM] Connection to server got closed. Server will restart.
```

**Comment by fedme** [comment]
It is crashing for me too every 10-15 minutes on WSL2/Ubuntu but I see no logs in the output tab.

Where do you guys see those logs?

**Comment by woolfred** [comment]
@fedme In VSCode Terminal is a _Output_-tab, there you can select ElixirLS in the dropdown on the right <img width="1030" alt="grafik" src="https://user-images.githubusercontent.com/9000002/106721462-fd451f00-6604-11eb-9c9e-b154b84fec7a.png">

**Comment by lukaszsamson** [comment]
@gjsduarte @fedme  @woolfred  Could you please post more logs with elixir stacktrace visible.

@doughsay what is the URI in `%{"type" => 2, "uri" => "git:/<redacted>"}`?
Is it sth like `git://github.com/user/repo.git` or some exotic one like `git:/<path>?{ "path": "<backslashed-windows-path>", "ref": "~" }`? I'm trying to understand why LSP receives file watcher notifications on `git:` scheme. We only expect `file:` scheme notifications.

**Comment by fedme** [comment]
Thanks @woolfred and @lukaszsamson for helping!

It hasn't crashed for me anymore in the last hour. I had some unsaved json files in the editor before, not sure if that was the issue. 

Will report here if it crashes again.

**Comment by woolfred** [comment]
@lukaszsamson looks like you are already working on it. But here another log you asked for:
```
11:30:00.590 [error] GenServer ElixirLS.LanguageServer.Server terminating
** (FunctionClauseError) no function clause matching in anonymous fn/2 in ElixirLS.LanguageServer.Server.handle_notification/2
    (language_server 0.6.4) lib/language_server/server.ex:402: anonymous fn(%{"type" => 2, "uri" => "git:<redacted>"}, %{"file://<redacted>" => %ElixirLS.LanguageServer.SourceFile{dirty?: false, text: "<redacted>", version: 1}}) in ElixirLS.LanguageServer.Server.handle_notification/2
    (elixir 1.11.3) lib/enum.ex:2193: Enum."-reduce/3-lists^foldl/2-0-"/3
    (language_server 0.6.4) lib/language_server/server.ex:402: ElixirLS.LanguageServer.Server.handle_notification/2
    (language_server 0.6.4) lib/language_server/server.ex:164: ElixirLS.LanguageServer.Server.handle_cast/2
    (stdlib 3.14) gen_server.erl:689: :gen_server.try_dispatch/4
    (stdlib 3.14) gen_server.erl:765: :gen_server.handle_msg/6
    (stdlib 3.14) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: {:"$gen_cast", {:receive_packet, %{"jsonrpc" => "2.0", "method" => "workspace/didChangeWatchedFiles", "params" => %{"changes" => [%{"type" => 2, "uri" => "git:<redacted>"}, %{"type" => 2, "uri" => "git:<redacted>"}, %{"type" => 2, "uri" => "git:<redacted>"}, %{"type" => 2, "uri" => "git:<redacted>"}, %{"type" => 2, "uri" => "git:<redacted>"}]}}}}
State: %ElixirLS.LanguageServer.Server{analysis_ready?: false, awaiting_contracts: [], build_diagnostics: [], build_ref: #Reference<0.2047524880.2067005441.193306>, build_running?: true, client_capabilities: %{"textDocument" => %{"codeAction" => %{"codeActionLiteralSupport" => %{"codeActionKind" => %{"valueSet" => ["", "quickfix", "refactor", "refactor.extract", "refactor.inline", "refactor.rewrite", "source", "source.organizeImports"]}}, "dynamicRegistration" => true, "isPreferredSupport" => true}, "codeLens" => %{"dynamicRegistration" => true}, "colorProvider" => %{"dynamicRegistration" => true}, "completion" => %{"completionItem" => %{"commitCharactersSupport" => true, "deprecatedSupport" => true, "documentationFormat" => ["markdown", "plaintext"], "preselectSupport" => true, "snippetSupport" => true, "tagSupport" => %{"valueSet" => [1]}}, "completionItemKind" => %{"valueSet" => [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]}, "contextSupport" => true, "dynamicRegistration" => true}, "declaration" => %{"dynamicRegistration" => true, "linkSupport" => true}, "definition" => %{"dynamicRegistration" => true, "linkSupport" => true}, "documentHighlight" => %{"dynamicRegistration" => true}, "documentLink" => %{"dynamicRegistration" => true, "tooltipSupport" => true}, "documentSymbol" => %{"dynamicRegistration" => true, "hierarchicalDocumentSymbolSupport" => true, "symbolKind" => %{"valueSet" => [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26]}}, "foldingRange" => %{"dynamicRegistration" => true, "lineFoldingOnly" => true, "rangeLimit" => 5000}, "formatting" => %{"dynamicRegistration" => true}, "hover" => %{"contentFormat" => ["markdown", "plaintext"], "dynamicRegistration" => true}, "implementation" => %{"dynamicRegistration" => true, "linkSupport" => true}, "onTypeFormatting" => %{"dynamicRegistration" => true}, "publishDiagnostics" => %{"relatedInformation" => true, "tagSupport" => %{"valueSet" => [1, 2]}, "versionSupport" => false}, "rangeFormatting" => %{"dynamicRegistration" => true}, "references" => %{"dynamicRegistration" => true}, "rename" => %{"dynamicRegistration" => true, "prepareSupport" => true}, "selectionRange" => %{"dynamicRegistration" => true}, "signatureHelp" => %{"contextSupport" => true, "dynamicRegistration" => true, "signatureInformation" => %{"documentationFormat" => ["markdown", "plaintext"], "parameterInformation" => %{"labelOffsetSupport" => true}}}, "synchronization" => %{"didSave" => true, "dynamicRegistration" => true, "willSave" => true, "willSaveWaitUntil" => true}, "typeDefinition" => %{"dynamicRegistration" => true, "linkSupport" => true}}, "window" => %{"workDoneProgress" => true}, "workspace" => %{"applyEdit" => true, "configuration" => true, "didChangeConfiguration" => %{"dynamicRegistration" => true}, "didChangeWatchedFiles" => %{"dynamicRegistration" => true (truncated)
[Info  - 11:30:02 AM] Connection to server got closed. Server will restart.
```

The first `uri` I redacted from the log looks like: `git:local_path_to_file?{"path":"local_path_to_file","ref":"~"}`, while the part after the `?` ist url encoded.

Hope this helps 🤞

**Comment by fedme** [comment]
@lukaszsamson Crashed for me again now, this time on one of those Git compare views that VScode shows you when you click on a staged file in the Git sidebar.

These are the logs:

```
20:01:50.743 [error] GenServer ElixirLS.LanguageServer.Server terminating
** (FunctionClauseError) no function clause matching in anonymous fn/2 in ElixirLS.LanguageServer.Server.handle_notification/2
    (language_server 0.6.4) lib/language_server/server.ex:402: anonymous fn(%{"type" => 2, "uri" => "git:/home/raimaj/code/<REDACTED>/test.exs?%7B%22path%22%3A%22%2Fhome%2Fraimaj%2Fcode%2<REDACTED>troller_test.exs%22%2C%22ref%22%3A%22~%22%7D"}, %{"file:///home/raimaj/code/<REDACTED>_controller.ex" => %ElixirLS.LanguageServer.SourceFile{dirty?: false, text: <REDACTED> (truncated)
[Warn  - 8:01:50 PM] ** (exit) exited in: GenServer.call(ElixirLS.LanguageServer.JsonRpc, {:packet, %{"id" => 1171, "jsonrpc" => "2.0", "method" => "textDocument/documentSymbol", "params" => %{"textDocument" => %{"uri" => "file:///home/raimaj/code/<REDACTED>_test.exs"}}}}, 5000)
    ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
    (elixir 1.11.2) lib/gen_server.ex:1017: GenServer.call/3
    (elixir 1.11.2) lib/stream.ex:441: anonymous fn/4 in Stream.each/2
    (elixir 1.11.2) lib/stream.ex:1449: Stream.do_element_resource/6
    (elixir 1.11.2) lib/stream.ex:1609: Enumerable.Stream.do_each/4
    (elixir 1.11.2) lib/stream.ex:649: Stream.run/1
    (stdlib 3.13.2) erl_eval.erl:680: :erl_eval.do_apply/6
    (elixir 1.11.2) lib/code.ex:341: Code.eval_string_with_error_handling/3
[Info  - 8:02:35 PM] Connection to server got closed. Server will restart.
[Error - 8:02:35 PM] Request textDocument/documentSymbol failed.
```

**Comment by lukaszsamson** [comment]
Thanks all, #475 should resolve that

**Comment by TheFirstAvenger** [comment]
FYI looks like this issue was introduced in 0.6.3, so rolling back to 0.6.2 should stop the crashing until this fix goes live.
