### ISSUE TITLE
The language_server is crash looping

### ISSUE THREAD

**Issue by AndrewDryga** [elixir-lsp/elixir-ls#476]
### Environment

* Elixir & Erlang versions (elixir --version): 1.11.2
* Operating system: MacOS
* Editor or IDE name (e.g. Emacs/VSCode): VSCode
* Editor Plugin/LSP Client name: VSCode

### Troubleshooting

```
[Info  - 12:45:12 PM] Connection to server got closed. Server will restart.
Started ElixirLS v0.6.4
Elixir version: "1.11.2 (compiled with Erlang/OTP 23)"
Erlang version: "23"
ElixirLS compiled with Elixir 1.11.2 and erlang 23
MIX_ENV: test
MIX_TARGET: 

12:45:16.129 [error] GenServer ElixirLS.LanguageServer.Server terminating
** (FunctionClauseError) no function clause matching in anonymous fn/2 in ElixirLS.LanguageServer.Server.handle_notification/2
    (language_server 0.6.4) lib/language_server/server.ex:402: anonymous fn(%{"type" => 2, "uri" => "git:/Users/andrew/Projects/hammer/mono/mix.exs?%7B%22path%22%3A%22%2FUsers%2Fandrew%2FProjects%2Fhammer%2Fmono%2Fmix.exs%22%2C%22ref%22%3A%22~%22%7D"}, %{"file:///Users/andrew/Projects/hammer/mono/mix.exs" => %ElixirLS.LanguageServer.SourceFile{dirty?: false, text: "defmodule Mono.Mixfile do\n...\nend\n", version: 11}}) in ElixirLS.LanguageServer.Server.handle_notification/2
    (elixir 1.11.2) lib/enum.ex:2181: Enum."-reduce/3-lists^foldl/2-0-"/3
    (language_server 0.6.4) lib/language_server/server.ex:402: ElixirLS.LanguageServer.Server.handle_notification/2
    (language_server 0.6.4) lib/language_server/server.ex:164: ElixirLS.LanguageServer.Server.handle_cast/2
    (stdlib 3.13.2) gen_server.erl:680: :gen_server.try_dispatch/4
    (stdlib 3.13.2) gen_server.erl:756: :gen_server.handle_msg/6
    (stdlib 3.13.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
```

**Comment by AndrewDryga** [comment]
Duplicate of #474
