### ISSUE TITLE
Race conditions on CI

### ISSUE THREAD

**Issue by lukaszsamson** [elixir-lsp/elixir-ls#495]
```
==> language_server
304
Compiling 53 files (.ex)
305
Generated language_server app
306
Excluding tags: [pending: true]
307

308
.................................................................................................................................
309
Error: 9.758 [error] Process #PID<0.1995.0> raised an exception
310
** (ErlangError) Erlang error: :terminated
311
    (stdlib 3.8.2.4) :io.put_chars(:standard_io, :unicode, ["\n== Compilation error in file lib/language_server/providers/code_lens/type_spec.ex ==\n", ["** (MatchError) no match of right hand side value: {:error, :enoent}", 10, "    (elixir 1.11.3) lib/kernel/parallel_compiler.ex:314: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/7\n"]])
312
    (elixir 1.11.3) lib/kernel/parallel_compiler.ex:557: Kernel.ParallelCompiler.wait_for_messages/7
313
    (elixir 1.11.3) lib/kernel/parallel_compiler.ex:149: Kernel.ParallelCompiler.spawn_workers/3
314
    (mix 1.11.3) lib/mix/compilers/elixir.ex:94: Mix.Compilers.Elixir.compile/6
315
    (mix 1.11.3) lib/mix/task.ex:394: Mix.Task.run_task/3
316
    (mix 1.11.3) lib/mix/tasks/compile.all.ex:90: Mix.Tasks.Compile.All.run_compiler/2
317
    (mix 1.11.3) lib/mix/tasks/compile.all.ex:70: Mix.Tasks.Compile.All.compile/4
318
    (mix 1.11.3) lib/mix/tasks/compile.all.ex:57: Mix.Tasks.Compile.All.with_logger_app/2
319
    (mix 1.11.3) lib/mix/tasks/compile.all.ex:35: Mix.Tasks.Compile.All.run/1
320
    (mix 1.11.3) lib/mix/task.ex:394: Mix.Task.run_task/3
321
    (mix 1.11.3) lib/mix/tasks/compile.ex:119: Mix.Tasks.Compile.run/1
322
    (mix 1.11.3) lib/mix/task.ex:394: Mix.Task.run_task/3
323
    (language_server 0.6.5) lib/language_server/build.ex:199: ElixirLS.LanguageServer.Build.compile/0
324
    (language_server 0.6.5) lib/language_server/build.ex:29: anonymous fn/3 in ElixirLS.LanguageServer.Build.build/3
325
    (stdlib 3.8.2.4) timer.erl:166: :timer.tc/1
326
    (language_server 0.6.5) lib/language_server/build.ex:12: anonymous fn/3 in ElixirLS.LanguageServer.Build.build/3
327
    (kernel 6.3.1.3) global.erl:430: :global.trans/4
328
................................................................................................................Content-Length: 192
329

330
{"jsonrpc":"2.0","method":"window/showMessage","params":{"message":"Building core Dialyzer Elixir PLT. This will take a few minutes (often 15+) and can be disabled in the settings.","type":3}}Content-Length: 151
331

332
{"jsonrpc":"2.0","method":"window/showMessage","params":{"message":"Saved Elixir PLT to /home/runner/.mix/elixir-ls-21.3.8.20_elixir-1.11.3","type":3}}
333
Error: 2.144 [error] Task #PID<0.1650.2> started from #PID<0.1336.2> terminating
334
** (ArgumentError) argument error
335
    (stdlib 3.8.2.4) :ets.select_trap({#Reference<0.3124882355.642383874.196698>, 3490, 0, #Reference<0.3124882355.642383874.200898>, [
```

**Comment by lukaszsamson** [comment]
This one happened locally
```
 * test returns code lenses for runnable tests [L#1158]
10:02:45.755 [error] Process #PID<0.911.0> raised an exception
** (Mix.NoProjectError) Could not find a Mix.Project, please ensure you are running Mix in a directory with a mix.exs file
    (mix 1.11.3) lib/mix/project.ex:176: Mix.Project.get!/0
    (mix 1.11.3) lib/mix/tasks/compile.app.ex:396: Mix.Tasks.Compile.App.project_apps/1
    (mix 1.11.3) lib/mix/compilers/application_tracer.ex:168: Mix.Compilers.ApplicationTracer.build_manifest/2
    (mix 1.11.3) lib/mix/compilers/application_tracer.ex:14: Mix.Compilers.ApplicationTracer.init/1
    (mix 1.11.3) lib/mix/compilers/elixir.ex:86: Mix.Compilers.Elixir.compile/6
    (mix 1.11.3) lib/mix/task.ex:394: Mix.Task.run_task/3
    (mix 1.11.3) lib/mix/tasks/compile.all.ex:90: Mix.Tasks.Compile.All.run_compiler/2
    (mix 1.11.3) lib/mix/tasks/compile.all.ex:70: Mix.Tasks.Compile.All.compile/4
    (mix 1.11.3) lib/mix/tasks/compile.all.ex:57: Mix.Tasks.Compile.All.with_logger_app/2
    (mix 1.11.3) lib/mix/tasks/compile.all.ex:35: Mix.Tasks.Compile.All.run/1
    (mix 1.11.3) lib/mix/task.ex:394: Mix.Task.run_task/3
    (mix 1.11.3) lib/mix/tasks/compile.ex:119: Mix.Tasks.Compile.run/1
    (mix 1.11.3) lib/mix/task.ex:394: Mix.Task.run_task/3
    (language_server 0.6.5) lib/language_server/build.ex:199: ElixirLS.LanguageServer.Build.compile/0
    (language_server 0.6.5) lib/language_server/build.ex:29: anonymous fn/3 in ElixirLS.LanguageServer.Build.build/3
    (stdlib 3.14) timer.erl:166: :timer.tc/1
    (language_server 0.6.5) lib/language_server/build.ex:12: anonymous fn/3 in ElixirLS.LanguageServer.Build.build/3
    (kernel 7.2) global.erl:425: :global.trans/4
 ```

**Comment by lukaszsamson** [comment]
```
  * test returns code lenses for runnable tests (184.1ms) [L#1158]
  * test workspace/didChangeWatchedFiles watched open file updated outside, read error (9.8ms) [L#596]
  * test workspace/didChangeWatchedFiles watched file updated outside [L#429]
10:05:45.532 [error] Process #PID<0.1280.0> raised an exception
** (Mix.Error) Could not find an SCM for dependency :forms from ElixirLS.LanguageServer.Mixfile
    (mix 1.11.3) lib/mix.ex:436: Mix.raise/1
    (mix 1.11.3) lib/mix/dep/loader.ex:201: Mix.Dep.Loader.with_scm_and_app/4
    (mix 1.11.3) lib/mix/dep/loader.ex:147: Mix.Dep.Loader.to_dep/3
    (elixir 1.11.3) lib/enum.ex:1411: Enum."-map/2-lists^map/1-0-"/2
    (elixir 1.11.3) lib/enum.ex:1411: Enum."-map/2-lists^map/1-0-"/2
    (mix 1.11.3) lib/mix/dep/loader.ex:364: Mix.Dep.Loader.mix_children/2
    (mix 1.11.3) lib/mix/dep/loader.ex:18: Mix.Dep.Loader.children/0
    (mix 1.11.3) lib/mix/dep/converger.ex:57: Mix.Dep.Converger.all/4
    (mix 1.11.3) lib/mix/dep/converger.ex:51: Mix.Dep.Converger.converge/4
    (mix 1.11.3) lib/mix/dep.ex:193: Mix.Dep.converge/1
    (mix 1.11.3) lib/mix/dep.ex:114: Mix.Dep.load_and_cache/0
    (mix 1.11.3) lib/mix/tasks/deps.loadpaths.ex:25: Mix.Tasks.Deps.Loadpaths.run/1
    (mix 1.11.3) lib/mix/task.ex:394: Mix.Task.run_task/3
    (mix 1.11.3) lib/mix/tasks/loadpaths.ex:37: Mix.Tasks.Loadpaths.run/1
    (mix 1.11.3) lib/mix/task.ex:394: Mix.Task.run_task/3
    (mix 1.11.3) lib/mix/tasks/compile.ex:113: Mix.Tasks.Compile.run/1
    (mix 1.11.3) lib/mix/task.ex:394: Mix.Task.run_task/3
    (language_server 0.6.5) lib/language_server/build.ex:199: ElixirLS.LanguageServer.Build.compile/0
    (language_server 0.6.5) lib/language_server/build.ex:29: anonymous fn/3 in ElixirLS.LanguageServer.Build.build/3
    (stdlib 3.14) timer.erl:166: :timer.tc/1
```

```
  * test returns code lenses for runnable tests (231.8ms) [L#1158]
  * test workspace/didChangeWatchedFiles watched file created outside (0.3ms) [L#420]
  * test workspace/didChangeWatchedFiles watched open file deleted outside (0.4ms) [L#625]
  * test reports build diagnostics on external resources [L#1005]
10:06:48.378 [error] Process #PID<0.1201.0> raised an exception
** (ErlangError) Erlang error: :terminated
    (stdlib 3.14) :io.put_chars(:standard_io, :unicode, ["\n== Compilation error in file lib/language_server/providers/code_lens/test.ex ==\n", ["** (MatchError) no match of right hand side value: {:error, :enoent}", 10, "    (elixir 1.11.3) lib/kernel/parallel_compiler.ex:314: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/7\n"]])
    (elixir 1.11.3) lib/kernel/parallel_compiler.ex:557: Kernel.ParallelCompiler.wait_for_messages/7
    (elixir 1.11.3) lib/kernel/parallel_compiler.ex:149: Kernel.ParallelCompiler.spawn_workers/3
    (mix 1.11.3) lib/mix/compilers/elixir.ex:94: Mix.Compilers.Elixir.compile/6
    (mix 1.11.3) lib/mix/task.ex:394: Mix.Task.run_task/3
    (mix 1.11.3) lib/mix/tasks/compile.all.ex:90: Mix.Tasks.Compile.All.run_compiler/2
    (mix 1.11.3) lib/mix/tasks/compile.all.ex:70: Mix.Tasks.Compile.All.compile/4
    (mix 1.11.3) lib/mix/tasks/compile.all.ex:57: Mix.Tasks.Compile.All.with_logger_app/2
    (mix 1.11.3) lib/mix/tasks/compile.all.ex:35: Mix.Tasks.Compile.All.run/1
    (mix 1.11.3) lib/mix/task.ex:394: Mix.Task.run_task/3
    (mix 1.11.3) lib/mix/tasks/compile.ex:119: Mix.Tasks.Compile.run/1
    (mix 1.11.3) lib/mix/task.ex:394: Mix.Task.run_task/3
    (language_server 0.6.5) lib/language_server/build.ex:199: ElixirLS.LanguageServer.Build.compile/0
    (language_server 0.6.5) lib/language_server/build.ex:29: anonymous fn/3 in ElixirLS.LanguageServer.Build.build/3
    (stdlib 3.14) timer.erl:166: :timer.tc/1
    (language_server 0.6.5) lib/language_server/build.ex:12: anonymous fn/3 in ElixirLS.LanguageServer.Build.build/3
    (kernel 7.2) global.erl:425: :global.trans/4

```

All of them seem to happen during or shortly after `test returns code lenses for runnable tests`
