### ISSUE TITLE
Compatibility with OTP 24

### ISSUE THREAD

**Issue by tcrossland** [elixir-lsp/elixir-ls#503]
The language server terminates repeatedly when using OTP 24 (and elixir master). I've tried compiling elixir-ls with the same version of OTP and Elixir, but compilation fails complaining about the use of `erlang:get_stacktrace/0` which has been removed in OTP 24 (I think that might be an issue with rebar3 in elixir master).

### Environment

* Elixir & Erlang versions (elixir --version): 
  * Erlang/OTP 24 [RELEASE CANDIDATE 1] [erts-12.0] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit] [dtrace]
  * Elixir 1.12.0-dev (compiled with Erlang/OTP 24)
* Operating system: 
  * macOS Big Sur Version 11.2.1
* Editor or IDE name (e.g. Emacs/VSCode): 
  * VSCode 
* Editor Plugin/LSP Client name:
  * ElixirLS

### Troubleshooting

- [x] Restart your editor (which will restart ElixirLS) sometimes fixes issues
- [x] Stop your editor, remove the entire `.elixir_ls` directory, then restart your editor
  * NOTE: This will cause you to have to re-run the dialyzer build for your project

If you're experiencing high CPU usage, it is most likely Dialyzer building the PLTs; after it's done the CPU usage should go back to normal. You could also disable Dialyzer in the settings.

### Logs

```
Started ElixirLS v0.6.5
Elixir version: "1.12.0-dev (compiled with Erlang/OTP 24)"
Erlang version: "24"
ElixirLS compiled with Elixir 1.8.2 and erlang 21
MIX_ENV: test
MIX_TARGET: 
[Info  - 3:56:36 PM] Compile took 1053 milliseconds
[Info  - 3:56:36 PM] [ElixirLS WorkspaceSymbols] Indexing...
[Info  - 3:56:36 PM] [ElixirLS Dialyzer] Checking for stale beam files
[Info  - 3:56:36 PM] [ElixirLS WorkspaceSymbols] Module discovery complete

15:56:37.234 [error] Task #PID<0.349.0> started from #PID<0.315.0> terminating
** (ArithmeticError) bad argument in arithmetic expression
    (language_server 0.6.5) lib/language_server/providers/workspace_symbols.ex:519: ElixirLS.LanguageServer.Providers.WorkspaceSymbols.build_range/1
    (language_server 0.6.5) lib/language_server/providers/workspace_symbols.ex:487: ElixirLS.LanguageServer.Providers.WorkspaceSymbols.build_result/4
    (language_server 0.6.5) lib/language_server/providers/workspace_symbols.ex:397: anonymous fn/4 in ElixirLS.LanguageServer.Providers.WorkspaceSymbols.index/1
    (elixir 1.12.0-dev) lib/enum.ex:2352: Enum."-reduce/3-lists^foldl/2-0-"/3
    (language_server 0.6.5) lib/language_server/providers/workspace_symbols.ex:386: anonymous fn/1 in ElixirLS.LanguageServer.Providers.WorkspaceSymbols.index/1
    (elixir 1.12.0-dev) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir 1.12.0-dev) lib/task/supervised.ex:35: Task.Supervised.reply/5
    (stdlib 3.15) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Function: #Function<32.766573/0 in ElixirLS.LanguageServer.Providers.WorkspaceSymbols.do_process_chunked/2>
    Args: []

15:56:36.909 [error] Task #PID<0.347.0> started from #PID<0.315.0> terminating
** (ArithmeticError) bad argument in arithmetic expression
    (language_server 0.6.5) lib/language_server/providers/workspace_symbols.ex:519: ElixirLS.LanguageServer.Providers.WorkspaceSymbols.build_range/1
    (language_server 0.6.5) lib/language_server/providers/workspace_symbols.ex:487: ElixirLS.LanguageServer.Providers.WorkspaceSymbols.build_result/4
    (language_server 0.6.5) lib/language_server/providers/workspace_symbols.ex:397: anonymous fn/4 in ElixirLS.LanguageServer.Providers.WorkspaceSymbols.index/1
    (elixir 1.12.0-dev) lib/enum.ex:2352: Enum."-reduce/3-lists^foldl/2-0-"/3
    (language_server 0.6.5) lib/language_server/providers/workspace_symbols.ex:386: anonymous fn/1 in ElixirLS.LanguageServer.Providers.WorkspaceSymbols.index/1
    (elixir 1.12.0-dev) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir 1.12.0-dev) lib/task/supervised.ex:35: Task.Supervised.reply/5
    (stdlib 3.15) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Function: #Function<32.766573/0 in ElixirLS.LanguageServer.Providers.WorkspaceSymbols.do_process_chunked/2>
    Args: []
```

**Comment by lukaszsamson** [comment]
Non stable elixir and OTP versions are not supported but we will appreciate a PR fixing that.

**Comment by tcrossland** [comment]
Understood, I wasn't requesting support, just registering the issue in readiness for OTP 24 (rc1 was released last week).

See also: https://github.com/elixir-lang/elixir/issues/10763

Will put together a PR if I manager to figure out how to fix it.
