### ISSUE TITLE
Dialyzer crashes repeatedly

### ISSUE THREAD

**Issue by Sojourn4** [elixir-lsp/elixir-ls#529]
When I open any Elixir file in VSCode Dialyzer starts trying to build the PLT. It eventually crashes with the error I've included at the end here, and tries again in a loop. I wind up with a noisy backlog of notifications about Dialyzer trying to build the PLT.

### Environment

* Elixir & Erlang versions (elixir --version): 
```
Erlang/OTP 22 [erts-10.6.4] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1]

Elixir 1.10.3 (compiled with Erlang/OTP 21)
```

* Operating system: Ubuntu 20.04.2 LTS, running on WSL
* Editor or IDE name (e.g. Emacs/VSCode): VSCode
* Editor Plugin/LSP Client name: ElixirLS: Elixir support and debugger

### Troubleshooting

- [x] Restart your editor (which will restart ElixirLS) sometimes fixes issues
- [x] Stop your editor, remove the entire `.elixir_ls` directory, then restart your editor
  * NOTE: This will cause you to have to re-run the dialyzer build for your project

If you're experiencing high CPU usage, it is most likely Dialyzer building the PLTs; after it's done the CPU usage should go back to normal. You could also disable Dialyzer in the settings.

### Logs

On my computer this is reproducible in an empty project. Here is the error from the ElixirLS output log:

```
15:01:57.576 [error] Task #PID<0.216.0> started from #PID<0.217.0> terminating
** (MatchError) no match of right hand side value: false
    (elixir 1.10.3) src/elixir_erl_var.erl:14: :elixir_erl_var.translate/4
    (stdlib 3.11.2) lists.erl:1354: :lists.mapfoldl/3
    (stdlib 3.11.2) lists.erl:1355: :lists.mapfoldl/3
    (elixir 1.10.3) src/elixir_erl_pass.erl:257: :elixir_erl_pass.translate/2
    (stdlib 3.11.2) lists.erl:1354: :lists.mapfoldl/3
    (stdlib 3.11.2) lists.erl:1355: :lists.mapfoldl/3
    (elixir 1.10.3) src/elixir_erl_clauses.erl:20: :elixir_erl_clauses.match/3
    (elixir 1.10.3) src/elixir_erl_clauses.erl:28: :elixir_erl_clauses.clause/6
Function: #Function<2.129723316/0 in ElixirLS.LanguageServer.Dialyzer.Manifest.build_new_manifest/0>
    Args: []
```

**Comment by axelson** [comment]
@Sojourn4 I wonder if the problem is that you're using an elixir version compiled on OTP 21 on OTP 22. Can you try to upgrade to Elixir 1.10.3-otp-22? How have you installed erlang and elixir?

**Comment by egeersoz** [comment]
I have this exact same issue.

```
Started ElixirLS v0.7.0
Elixir version: "1.11.2 (compiled with Erlang/OTP 21)"
Erlang version: "21"
ElixirLS compiled with Elixir 1.8.2 and erlang 21
MIX_ENV: test
```

```
Generated my_app app
[Info  - 2:27:32 PM] Compile took 106031 milliseconds
[Info  - 2:27:32 PM] [ElixirLS Dialyzer] Checking for stale beam files
[Info  - 2:27:32 PM] [ElixirLS WorkspaceSymbols] Indexing...
[Info  - 2:27:32 PM] [ElixirLS WorkspaceSymbols] Module discovery complete
[Info  - 2:27:34 PM] [ElixirLS WorkspaceSymbols] 458 callbacks added to index
[Info  - 2:27:36 PM] [ElixirLS Dialyzer] Found 1582 changed files in 3938 milliseconds
[Info  - 2:27:41 PM] [ElixirLS WorkspaceSymbols] 1682 modules added to index
[Info  - 2:27:42 PM] [ElixirLS WorkspaceSymbols] 922 types added to index

14:27:43.762 [error] Task #PID<0.6473.0> started from #PID<0.6472.0> terminating
** (MatchError) no match of right hand side value: false
    (elixir 1.11.2) src/elixir_erl_var.erl:14: :elixir_erl_var.translate/4
    (stdlib 3.7) lists.erl:1354: :lists.mapfoldl/3
    (elixir 1.11.2) src/elixir_erl_clauses.erl:20: :elixir_erl_clauses.match/3
    (elixir 1.11.2) src/elixir_erl_clauses.erl:28: :elixir_erl_clauses.clause/6
    (elixir 1.11.2) src/elixir_erl.erl:214: :elixir_erl.translate_clause/3
    (elixir 1.11.2) src/elixir_erl.erl:204: :elixir_erl."-translate_definition/4-lc$^0/1-0-"/2
    (elixir 1.11.2) src/elixir_erl.erl:204: :elixir_erl.translate_definition/4
    (elixir 1.11.2) src/elixir_erl.erl:167: :elixir_erl.split_definition/11
    (elixir 1.11.2) src/elixir_erl.erl:137: :elixir_erl.dynamic_form/1
    (elixir 1.11.2) src/elixir_erl.erl:18: :elixir_erl.debug_info/4
    (dialyzer 3.3.1) dialyzer_utils.erl:116: :dialyzer_utils.get_core_from_beam/2
    (language_server 0.7.0) lib/language_server/dialyzer/utils.ex:7: ElixirLS.LanguageServer.Dialyzer.Utils.dialyzable?/1
    (language_server 0.7.0) lib/language_server/dialyzer/utils.ex:36: ElixirLS.LanguageServer.Dialyzer.Utils.expand_references/3
    (language_server 0.7.0) lib/language_server/dialyzer/manifest.ex:136: ElixirLS.LanguageServer.Dialyzer.Manifest.build_elixir_plt/0
    (language_server 0.7.0) lib/language_server/dialyzer/manifest.ex:14: anonymous fn/1 in ElixirLS.LanguageServer.Dialyzer.Manifest.build_new_manifest/0
    (elixir 1.11.2) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (stdlib 3.7) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Function: #Function<2.129723316/0 in ElixirLS.LanguageServer.Dialyzer.Manifest.build_new_manifest/0>
    Args: []
 ```

These errors are repeated in ElixirLS.log indefinitely. It results in erl.exe maxing out a CPU core, and causes VSCode to become unresponsive for a few seconds every couple of minutes. I end up having to uncheck "Run ElixirLS's rapid Dialyzer when code is saved" option and restart VSCode.

The issue started happening when I upgraded my Elixir from 1.9.2 to 1.11.2. Nothing else changed.

**Comment by lukaszsamson** [comment]
Please verify that your elixir install is correct and free from leftovers from previous versions. See this upstream bug https://github.com/elixir-lang/elixir/issues/9932

Please reopen if you can prepare a sample project reproducing this error
