### ISSUE TITLE
toPipe crashed a server

### ISSUE THREAD

**Issue by fuelen** [elixir-lsp/elixir-ls#570]
### Environment

* Elixir & Erlang versions (elixir --version): 1.12 (OTP 23)
* Editor or IDE name (e.g. Emacs/VSCode): neovim
* Editor Plugin/LSP Client name: built-in

test file:
```elixir
test = 1
%{
  q:
    if(is_nil(test),
      do: max(test, is_nil(test)),
      else: []
    )
}
```

```
[ DEBUG ] 2021-07-09T01:00:55+0300 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:895 ]	"LSP[elixirls]"	"client.request"	1	"workspace/executeCommand"	{  arguments = { "toPipe", "file:///test.ex", 4, 13 },  command = "manipulatePipes:toPipe"}	<function 1>	3
[ DEBUG ] 2021-07-09T01:00:55+0300 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:395 ]	"rpc.send.payload"	{  id = 2,  jsonrpc = "2.0",  method = "workspace/executeCommand",  params = {    arguments = { "toPipe", "file:///test.ex", 4, 13 },    command = "manipulatePipes:toPipe"  }}
[ DEBUG ] 2021-07-09T01:00:55+0300 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:496 ]	"decoded"	{  jsonrpc = "2.0",  method = "window/logMessage",  params = {    message = '\n01:00:55.243 [error] GenServer ElixirLS.LanguageServer.Server terminating\n** (CaseClauseError) no case clause matching: {:error, :function_call_not_found}\n    (language_server 0.7.0) lib/language_server/server.ex:113: ElixirLS.LanguageServer.Server.handle_call/3\n    (stdlib 3.14.2.1) gen_server.erl:715: :gen_server.try_handle_call/4\n    (stdlib 3.14.2.1) gen_server.erl:744: :gen_server.handle_msg/6\n    (stdlib 3.14.2.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3\nLast message (from #PID<0.337.0>): {:request_finished, 2, {:error, :function_call_not_found}}\nState: %ElixirLS.LanguageServer.Server{analysis_ready?: false, awaiting_contracts: [], build_diagnostics: [], build_ref: #Reference<0.1148119946.4016570373.98385>, build_running?: false, client_capabilities: %{"callHierarchy" => %{"dynamicRegistration" => false}, "textDocument" => %{"codeAction" => %{"codeActionLiteralSupport" => %{"codeActionKind" => %{"valueSet" => ["", "Empty", "QuickFix", "Refactor", "RefactorExtract", "RefactorInline", "RefactorRewrite", "Source", "SourceOrganizeImports", "quickfix", "refactor", "refactor.extract", "refactor.inline", "refactor.rewrite", "source", "source.organizeImports"]}}, "dynamicRegistration" => false}, "completion" => %{"completionItem" => %{"commitCharactersSupport" => false, "deprecatedSupport" => false, "documentationFormat" => ["markdown", "plaintext"], "preselectSupport" => false, "snippetSupport" => false}, "completionItemKind" => %{"valueSet" => [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]}, "contextSupport" => false, "dynamicRegistration" => false}, "declaration" => %{"linkSupport" => true}, "definition" => %{"linkSupport" => true}, "documentHighlight" => %{"dynamicRegistration" => false}, "documentSymbol" => %{"dynamicRegistration" => false, "hierarchicalDocumentSymbolSupport" => true, "symbolKind" => %{"valueSet" => [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26]}}, "hover" => %{"contentFormat" => ["markdown", "plaintext"], "dynamicRegistration" => false}, "implementation" => %{"linkSupport" => true}, "publishDiagnostics" => %{"relatedInformation" => true, "tagSupport" => %{"valueSet" => [1, 2]}}, "references" => %{"dynamicRegistration" => false}, "rename" => %{"dynamicRegistration" => false, "prepareSupport" => true}, "signatureHelp" => %{"dynamicRegistration" => false, "signatureInformation" => %{"documentationFormat" => ["markdown", "plaintext"]}}, "synchronization" => %{"didSave" => true, "dynamicRegistration" => false, "willSave" => false, "willSaveWaitUntil" => false}, "typeDefinition" => %{"linkSupport" => true}}, "window" => %{"showDocument" => %{"support" => false}, "showMessage" => %{"messageActionItem" => %{"additionalPropertiesSupport" => false}}, "workDoneProgress" => true}, "workspace" => %{"applyEdit" => true, "configuration" => true, "symbol" => %{"dynamicRegistration" => false, "hierarchicalWorkspaceSymbolSupport" => true, "symbolKind" => %{"valueSet" => [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26]}}, "workspaceEdit" => %{"resourceOperations" => ["rename", "create", "delete"]}, "workspaceFolders" => true}}, dialyzer_diagnostics: [], dialyzer_sup: nil, load_all_modules?: false, needs_build?: false, no_mixfile_warned?: false, project_dir: "/", received_shutdown?: false, requests: %{2 => #PID<0.337.0>}, root_uri: "file:///", server_instance_id: "GNrIvutgNoF8t8QQcwPTaOkfe9ZgL9K3", settings: %{"dialyzerEnabled" => false}, source_files: %{"file:///test.ex" => %ElixirLS.LanguageServer.SourceFile{dirty?: false, text: "test = 1\\n%{\\n  q:\\n    if(is_nil(test),\\n      do: max(test, is_nil(test)),\\n      else: []\\n    )\\n}\\n", version: 0}}, supports_dynamic: false}\nClient #PID<0.337.0> is alive\n\n    (stdlib 3.14.2.1) gen.erl:208: :gen.do_call/4\n    (elixir 1.12.2) lib/gen_server.ex:1021: GenServer.call/3',    type = 4  }}
[ DEBUG ] 2021-07-09T01:00:55+0300 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:680 ]	"notification"	"window/logMessage"	{  message = '\n01:00:55.243 [error] GenServer ElixirLS.LanguageServer.Server terminating\n** (CaseClauseError) no case clause matching: {:error, :function_call_not_found}\n    (language_server 0.7.0) lib/language_server/server.ex:113: ElixirLS.LanguageServer.Server.handle_call/3\n    (stdlib 3.14.2.1) gen_server.erl:715: :gen_server.try_handle_call/4\n    (stdlib 3.14.2.1) gen_server.erl:744: :gen_server.handle_msg/6\n    (stdlib 3.14.2.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3\nLast message (from #PID<0.337.0>): {:request_finished, 2, {:error, :function_call_not_found}}\nState: %ElixirLS.LanguageServer.Server{analysis_ready?: false, awaiting_contracts: [], build_diagnostics: [], build_ref: #Reference<0.1148119946.4016570373.98385>, build_running?: false, client_capabilities: %{"callHierarchy" => %{"dynamicRegistration" => false}, "textDocument" => %{"codeAction" => %{"codeActionLiteralSupport" => %{"codeActionKind" => %{"valueSet" => ["", "Empty", "QuickFix", "Refactor", "RefactorExtract", "RefactorInline", "RefactorRewrite", "Source", "SourceOrganizeImports", "quickfix", "refactor", "refactor.extract", "refactor.inline", "refactor.rewrite", "source", "source.organizeImports"]}}, "dynamicRegistration" => false}, "completion" => %{"completionItem" => %{"commitCharactersSupport" => false, "deprecatedSupport" => false, "documentationFormat" => ["markdown", "plaintext"], "preselectSupport" => false, "snippetSupport" => false}, "completionItemKind" => %{"valueSet" => [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]}, "contextSupport" => false, "dynamicRegistration" => false}, "declaration" => %{"linkSupport" => true}, "definition" => %{"linkSupport" => true}, "documentHighlight" => %{"dynamicRegistration" => false}, "documentSymbol" => %{"dynamicRegistration" => false, "hierarchicalDocumentSymbolSupport" => true, "symbolKind" => %{"valueSet" => [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26]}}, "hover" => %{"contentFormat" => ["markdown", "plaintext"], "dynamicRegistration" => false}, "implementation" => %{"linkSupport" => true}, "publishDiagnostics" => %{"relatedInformation" => true, "tagSupport" => %{"valueSet" => [1, 2]}}, "references" => %{"dynamicRegistration" => false}, "rename" => %{"dynamicRegistration" => false, "prepareSupport" => true}, "signatureHelp" => %{"dynamicRegistration" => false, "signatureInformation" => %{"documentationFormat" => ["markdown", "plaintext"]}}, "synchronization" => %{"didSave" => true, "dynamicRegistration" => false, "willSave" => false, "willSaveWaitUntil" => false}, "typeDefinition" => %{"linkSupport" => true}}, "window" => %{"showDocument" => %{"support" => false}, "showMessage" => %{"messageActionItem" => %{"additionalPropertiesSupport" => false}}, "workDoneProgress" => true}, "workspace" => %{"applyEdit" => true, "configuration" => true, "symbol" => %{"dynamicRegistration" => false, "hierarchicalWorkspaceSymbolSupport" => true, "symbolKind" => %{"valueSet" => [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26]}}, "workspaceEdit" => %{"resourceOperations" => ["rename", "create", "delete"]}, "workspaceFolders" => true}}, dialyzer_diagnostics: [], dialyzer_sup: nil, load_all_modules?: false, needs_build?: false, no_mixfile_warned?: false, project_dir: "/", received_shutdown?: false, requests: %{2 => #PID<0.337.0>}, root_uri: "file:///", server_instance_id: "GNrIvutgNoF8t8QQcwPTaOkfe9ZgL9K3", settings: %{"dialyzerEnabled" => false}, source_files: %{"file:///test.ex" => %ElixirLS.LanguageServer.SourceFile{dirty?: false, text: "test = 1\\n%{\\n  q:\\n    if(is_nil(test),\\n      do: max(test, is_nil(test)),\\n      else: []\\n    )\\n}\\n", version: 0}}, supports_dynamic: false}\nClient #PID<0.337.0> is alive\n\n    (stdlib 3.14.2.1) gen.erl:208: :gen.do_call/4\n    (elixir 1.12.2) lib/gen_server.ex:1021: GenServer.call/3',  type = 4}
[ DEBUG ] 2021-07-09T01:00:55+0300 ] /usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:434 ]	"default_handler"	"window/logMessage"	{  client_id = 1,  params = {    message = '\n01:00:55.243 [error] GenServer ElixirLS.LanguageServer.Server terminating\n** (CaseClauseError) no case clause matching: {:error, :function_call_not_found}\n    (language_server 0.7.0) lib/language_server/server.ex:113: ElixirLS.LanguageServer.Server.handle_call/3\n    (stdlib 3.14.2.1) gen_server.erl:715: :gen_server.try_handle_call/4\n    (stdlib 3.14.2.1) gen_server.erl:744: :gen_server.handle_msg/6\n    (stdlib 3.14.2.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3\nLast message (from #PID<0.337.0>): {:request_finished, 2, {:error, :function_call_not_found}}\nState: %ElixirLS.LanguageServer.Server{analysis_ready?: false, awaiting_contracts: [], build_diagnostics: [], build_ref: #Reference<0.1148119946.4016570373.98385>, build_running?: false, client_capabilities: %{"callHierarchy" => %{"dynamicRegistration" => false}, "textDocument" => %{"codeAction" => %{"codeActionLiteralSupport" => %{"codeActionKind" => %{"valueSet" => ["", "Empty", "QuickFix", "Refactor", "RefactorExtract", "RefactorInline", "RefactorRewrite", "Source", "SourceOrganizeImports", "quickfix", "refactor", "refactor.extract", "refactor.inline", "refactor.rewrite", "source", "source.organizeImports"]}}, "dynamicRegistration" => false}, "completion" => %{"completionItem" => %{"commitCharactersSupport" => false, "deprecatedSupport" => false, "documentationFormat" => ["markdown", "plaintext"], "preselectSupport" => false, "snippetSupport" => false}, "completionItemKind" => %{"valueSet" => [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]}, "contextSupport" => false, "dynamicRegistration" => false}, "declaration" => %{"linkSupport" => true}, "definition" => %{"linkSupport" => true}, "documentHighlight" => %{"dynamicRegistration" => false}, "documentSymbol" => %{"dynamicRegistration" => false, "hierarchicalDocumentSymbolSupport" => true, "symbolKind" => %{"valueSet" => [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26]}}, "hover" => %{"contentFormat" => ["markdown", "plaintext"], "dynamicRegistration" => false}, "implementation" => %{"linkSupport" => true}, "publishDiagnostics" => %{"relatedInformation" => true, "tagSupport" => %{"valueSet" => [1, 2]}}, "references" => %{"dynamicRegistration" => false}, "rename" => %{"dynamicRegistration" => false, "prepareSupport" => true}, "signatureHelp" => %{"dynamicRegistration" => false, "signatureInformation" => %{"documentationFormat" => ["markdown", "plaintext"]}}, "synchronization" => %{"didSave" => true, "dynamicRegistration" => false, "willSave" => false, "willSaveWaitUntil" => false}, "typeDefinition" => %{"linkSupport" => true}}, "window" => %{"showDocument" => %{"support" => false}, "showMessage" => %{"messageActionItem" => %{"additionalPropertiesSupport" => false}}, "workDoneProgress" => true}, "workspace" => %{"applyEdit" => true, "configuration" => true, "symbol" => %{"dynamicRegistration" => false, "hierarchicalWorkspaceSymbolSupport" => true, "symbolKind" => %{"valueSet" => [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26]}}, "workspaceEdit" => %{"resourceOperations" => ["rename", "create", "delete"]}, "workspaceFolders" => true}}, dialyzer_diagnostics: [], dialyzer_sup: nil, load_all_modules?: false, needs_build?: false, no_mixfile_warned?: false, project_dir: "/", received_shutdown?: false, requests: %{2 => #PID<0.337.0>}, root_uri: "file:///", server_instance_id: "GNrIvutgNoF8t8QQcwPTaOkfe9ZgL9K3", settings: %{"dialyzerEnabled" => false}, source_files: %{"file:///test.ex" => %ElixirLS.LanguageServer.SourceFile{dirty?: false, text: "test = 1\\n%{\\n  q:\\n    if(is_nil(test),\\n      do: max(test, is_nil(test)),\\n      else: []\\n    )\\n}\\n", version: 0}}, supports_dynamic: false}\nClient #PID<0.337.0> is alive\n\n    (stdlib 3.14.2.1) gen.erl:208: :gen.do_call/4\n    (elixir 1.12.2) lib/gen_server.ex:1021: GenServer.call/3',    type = 4  }}
[ DEBUG ] 2021-07-09T01:00:55+0300 ] /usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:408 ]	'\n01:00:55.243 [error] GenServer ElixirLS.LanguageServer.Server terminating\n** (CaseClauseError) no case clause matching: {:error, :function_call_not_found}\n    (language_server 0.7.0) lib/language_server/server.ex:113: ElixirLS.LanguageServer.Server.handle_call/3\n    (stdlib 3.14.2.1) gen_server.erl:715: :gen_server.try_handle_call/4\n    (stdlib 3.14.2.1) gen_server.erl:744: :gen_server.handle_msg/6\n    (stdlib 3.14.2.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3\nLast message (from #PID<0.337.0>): {:request_finished, 2, {:error, :function_call_not_found}}\nState: %ElixirLS.LanguageServer.Server{analysis_ready?: false, awaiting_contracts: [], build_diagnostics: [], build_ref: #Reference<0.1148119946.4016570373.98385>, build_running?: false, client_capabilities: %{"callHierarchy" => %{"dynamicRegistration" => false}, "textDocument" => %{"codeAction" => %{"codeActionLiteralSupport" => %{"codeActionKind" => %{"valueSet" => ["", "Empty", "QuickFix", "Refactor", "RefactorExtract", "RefactorInline", "RefactorRewrite", "Source", "SourceOrganizeImports", "quickfix", "refactor", "refactor.extract", "refactor.inline", "refactor.rewrite", "source", "source.organizeImports"]}}, "dynamicRegistration" => false}, "completion" => %{"completionItem" => %{"commitCharactersSupport" => false, "deprecatedSupport" => false, "documentationFormat" => ["markdown", "plaintext"], "preselectSupport" => false, "snippetSupport" => false}, "completionItemKind" => %{"valueSet" => [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]}, "contextSupport" => false, "dynamicRegistration" => false}, "declaration" => %{"linkSupport" => true}, "definition" => %{"linkSupport" => true}, "documentHighlight" => %{"dynamicRegistration" => false}, "documentSymbol" => %{"dynamicRegistration" => false, "hierarchicalDocumentSymbolSupport" => true, "symbolKind" => %{"valueSet" => [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26]}}, "hover" => %{"contentFormat" => ["markdown", "plaintext"], "dynamicRegistration" => false}, "implementation" => %{"linkSupport" => true}, "publishDiagnostics" => %{"relatedInformation" => true, "tagSupport" => %{"valueSet" => [1, 2]}}, "references" => %{"dynamicRegistration" => false}, "rename" => %{"dynamicRegistration" => false, "prepareSupport" => true}, "signatureHelp" => %{"dynamicRegistration" => false, "signatureInformation" => %{"documentationFormat" => ["markdown", "plaintext"]}}, "synchronization" => %{"didSave" => true, "dynamicRegistration" => false, "willSave" => false, "willSaveWaitUntil" => false}, "typeDefinition" => %{"linkSupport" => true}}, "window" => %{"showDocument" => %{"support" => false}, "showMessage" => %{"messageActionItem" => %{"additionalPropertiesSupport" => false}}, "workDoneProgress" => true}, "workspace" => %{"applyEdit" => true, "configuration" => true, "symbol" => %{"dynamicRegistration" => false, "hierarchicalWorkspaceSymbolSupport" => true, "symbolKind" => %{"valueSet" => [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26]}}, "workspaceEdit" => %{"resourceOperations" => ["rename", "create", "delete"]}, "workspaceFolders" => true}}, dialyzer_diagnostics: [], dialyzer_sup: nil, load_all_modules?: false, needs_build?: false, no_mixfile_warned?: false, project_dir: "/", received_shutdown?: false, requests: %{2 => #PID<0.337.0>}, root_uri: "file:///", server_instance_id: "GNrIvutgNoF8t8QQcwPTaOkfe9ZgL9K3", settings: %{"dialyzerEnabled" => false}, source_files: %{"file:///test.ex" => %ElixirLS.LanguageServer.SourceFile{dirty?: false, text: "test = 1\\n%{\\n  q:\\n    if(is_nil(test),\\n      do: max(test, is_nil(test)),\\n      else: []\\n    )\\n}\\n", version: 0}}, supports_dynamic: false}\nClient #PID<0.337.0> is alive\n\n    (stdlib 3.14.2.1) gen.erl:208: :gen.do_call/4\n    (elixir 1.12.2) lib/gen_server.ex:1021: GenServer.call/3'
[ DEBUG ] 2021-07-09T01:00:55+0300 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:496 ]	"decoded"	{  jsonrpc = "2.0",  method = "window/showMessage",  params = {    message = "ElixirLS has crashed. See Output panel.",    type = 1  }}
```

**Comment by lukaszsamson** [comment]
@polvalente Are you interesting in fixing this?

**Comment by polvalente** [comment]
> @polvalente Are you interesting in fixing this?

Sure! I'll take a look into it soon :)
