### ISSUE TITLE
cannot find make on apple silicone

### ISSUE THREAD

**Issue by vacarsu** [elixir-lsp/elixir-ls#621]
### Environment

* Elixir & Erlang versions (elixir --version): 
   Erlang/OTP 24 [erts-12.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1]
   Elixir 1.12.3 (compiled with Erlang/OTP 24)
* Operating system: MacOS
* Editor or IDE name (e.g. Emacs/VSCode): VSCode

ElixirLS for VSCode outputs the following
```
Could not compile with "make" (exit status: 2).
You need to have gcc and make installed. Try running the
commands "gcc --version" and / or "make --version". If these programs
are not installed, you will be prompted to install them.

    (mix 1.12.3) lib/mix.ex:455: Mix.raise/2
    (elixir_make 0.6.3) lib/mix/tasks/compile.make.ex:154: Mix.Tasks.Compile.ElixirMake.run/1
    (mix 1.12.3) lib/mix/task.ex:394: anonymous fn/3 in Mix.Task.run_task/3
    (mix 1.12.3) lib/mix/tasks/compile.all.ex:92: Mix.Tasks.Compile.All.run_compiler/2
    (mix 1.12.3) lib/mix/tasks/compile.all.ex:72: Mix.Tasks.Compile.All.compile/4
    (mix 1.12.3) lib/mix/tasks/compile.all.ex:59: Mix.Tasks.Compile.All.with_logger_app/2
    (mix 1.12.3) lib/mix/tasks/compile.all.ex:36: Mix.Tasks.Compile.All.run/1
    (mix 1.12.3) lib/mix/task.ex:394: anonymous fn/3 in Mix.Task.run_task/3
```
`make --version`

```
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for i386-apple-darwin11.3.0
```

**Comment by lukaszsamson** [comment]
Elixir-LS is not using make. Please report it to ElixirMake project

**Comment by vacarsu** [comment]
My application is compiling fine though, only ElixirLS is outputting this error?
