### ISSUE TITLE
Test code always craches the language server.

### ISSUE THREAD

**Issue by MaSven** [elixir-lsp/elixir-ls#631]
### Environment

* Elixir & Erlang versions (elixir --version):  
Erlang/OTP 24 [erts-12.1.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

Elixir 1.12.3 (compiled with Erlang/OTP 24)
* Operating system: 
Opensuse TW
* Editor or IDE name (e.g. Emacs/VSCode): 
Emacs
* Editor Plugin/LSP Client name:
emacs-lsp
### Troubleshooting

- [ x] Restart your editor (which will restart ElixirLS) sometimes fixes issues
- [ x] Stop your editor, remove the entire `.elixir_ls` directory, then restart your editor

### Logs

```
16:42:20.559 [error] Process #PID<0.131.0> raised an exception
** (MatchError) no match of right hand side value: nil
    (language_server 0.8.1) lib/language_server/providers/code_lens/test/describe_block.ex:23: ElixirLS.LanguageServer.Providers.CodeLens.Test.DescribeBlock.get_name/2
    (language_server 0.8.1) lib/language_server/providers/code_lens/test/describe_block.ex:10: ElixirLS.LanguageServer.Providers.CodeLens.Test.DescribeBlock.find_block_info/4
    (language_server 0.8.1) lib/language_server/providers/code_lens/test.ex:104: anonymous fn/5 in ElixirLS.LanguageServer.Providers.CodeLens.Test.find_describe_blocks/3
    (elixir 1.12.3) lib/enum.ex:2385: Enum."-reduce/3-lists^foldl/2-0-"/3
    (language_server 0.8.1) lib/language_server/providers/code_lens/test.ex:103: ElixirLS.LanguageServer.Providers.CodeLens.Test.find_describe_blocks/3
    (language_server 0.8.1) lib/language_server/providers/code_lens/test.ex:34: ElixirLS.LanguageServer.Providers.CodeLens.Test.code_lens/3
    (language_server 0.8.1) lib/language_server/server.ex:894: ElixirLS.LanguageServer.Server.get_test_code_lenses/5
    (language_server 0.8.1) lib/language_server/server.ex:725: anonymous fn/3 in ElixirLS.LanguageServer.Server.handle_request/2

16:42:20.560 [error] Process #PID<0.2562.0> raised an exception
** (MatchError) no match of right hand side value: nil
    (language_server 0.8.1) lib/language_server/providers/code_lens/test/describe_block.ex:23: ElixirLS.LanguageServer.Providers.CodeLens.Test.DescribeBlock.get_name/2
    (language_server 0.8.1) lib/language_server/providers/code_lens/test/describe_block.ex:10: ElixirLS.LanguageServer.Providers.CodeLens.Test.DescribeBlock.find_block_info/4
    (language_server 0.8.1) lib/language_server/providers/code_lens/test.ex:104: anonymous fn/5 in ElixirLS.LanguageServer.Providers.CodeLens.Test.find_describe_blocks/3
    (elixir 1.12.3) lib/enum.ex:2385: Enum."-reduce/3-lists^foldl/2-0-"/3
    (language_server 0.8.1) lib/language_server/providers/code_lens/test.ex:103: ElixirLS.LanguageServer.Providers.CodeLens.Test.find_describe_blocks/3
    (language_server 0.8.1) lib/language_server/providers/code_lens/test.ex:34: ElixirLS.LanguageServer.Providers.CodeLens.Test.code_lens/3
    (language_server 0.8.1) lib/language_server/server.ex:894: ElixirLS.LanguageServer.Server.get_test_code_lenses/5
    (language_server 0.8.1) lib/language_server/server.ex:725: anonymous fn/3 in ElixirLS.LanguageServer.Server.handle_request/2
```

You can find the project in github.com/MaSven/ex_simple_graph

**Comment by lukaszsamson** [comment]
Please provide more details on how to reproduce it

**Comment by MaSven** [comment]
I can't reproduce it. I will close this issue. But it was something here https://github.com/MaSven/ex_simple_graph/blob/e65cc71990955716c30ace83ee46f0f5d63b8566/test/simple_graph/node_test.exs?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L8 that triggered it.

**Comment by jtrees** [comment]
I run into a similar issue. I get some kind of exception whenever I'm editing a test file.

Here's an example:

```
** (ArgumentError) argument error
    :erlang.atom_to_binary({:unquote, [], [{:name, [counter: -576460752303423223], ExUnit.Callbacks}]}, :utf8)
    (elixir_sense 2.0.0) lib/elixir_sense/providers/suggestion/complete.ex:510: anonymous fn/4 in ElixirSense.Providers.Suggestion.Complete.match_module_funs/4
    (elixir 1.12.3) lib/enum.ex:2385: Enum."-reduce/3-lists^foldl/2-0-"/3
    (elixir_sense 2.0.0) lib/elixir_sense/providers/suggestion/complete.ex:509: ElixirSense.Providers.Suggestion.Complete.match_module_funs/4
    (elixir_sense 2.0.0) lib/elixir_sense/providers/suggestion/complete.ex:264: ElixirSense.Providers.Suggestion.Complete.match_local/2
    (elixir_sense 2.0.0) lib/elixir_sense/providers/suggestion/complete.ex:249: ElixirSense.Providers.Suggestion.Complete.expand_local_or_var/2
    (elixir_sense 2.0.0) lib/elixir_sense/providers/suggestion/reducers/common.ex:72: ElixirSense.Providers.Suggestion.Reducers.Common.populate/5
    (elixir 1.12.3) lib/enum.ex:4286: Enumerable.List.reduce/3
```

Since it happens on a proprietary project I'm doing for a client, I cannot share any code though.

**Comment by lukaszsamson** [comment]
If you can’t provide a repro you can always send a PR to elixir_sense fixing tour specific issue
