### ISSUE TITLE
elixir-ls won't start with emacs and tramp mode

### ISSUE THREAD

**Issue by mogorman** [elixir-lsp/elixir-ls#714]
### Environment

* Elixir & Erlang versions (elixir --version): Elixir version: "1.13.4 (compiled with Erlang/OTP 24)"
* Elixir Language Server version: ElixirLS v0.10.0
* Operating system: nixos 22.05.20220719.e732e1f
* Editor or IDE name (e.g. Emacs/VSCode): Emacs 29.0.50
* Editor Plugin/LSP Client name and version: lsp-mode 8.0

### Current behavior
elixir-ls works locally on my emacs setup but when I try to use it remotely over tramp I think there is a bug with the content length. Every time elixir-ls tries to start it fails with a json decoding error. So I wasn't sure if this is a bug in emacs-lsp or elixir-ls
the emacs config is just
```
 (lsp-register-client
 (make-lsp-client :new-connection (lsp-tramp-connection "/home/mog/.nix-profile/bin/elixir-ls")
                  :major-modes '(elixir-mode)
                  :remote? t
                  :server-id 'elixir-ls-remote))
 (setq lsp-log-io t)
```

```
Found the following clients for /ssh:mog@madrox:/home/mog/abcde/lib/abcde/almanac.ex: (server-id elixir-ls-remote, priority 0)
The following clients were selected based on priority: (server-id elixir-ls-remote, priority 0)
Started ElixirLS v0.10.0
Elixir version: "1.13.4 (compiled with Erlang/OTP 24)"
Erlang version: "24"
ElixirLS compiled with Elixir 1.13.4 and erlang 24
warning: Unable to read from device: %JasonVendored.DecodeError{data: "\n\n{\"jsonrpc\":\"2.0\",\"method\":\"initialize\",\"params\":{\"processId\":null,\"rootPath\":\"/home/mog/abcde\",\"clientInfo\":{\"name\":\"emacs\",\"version\":\"GNU Emacs 29.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.30, cairo version 1.16.0)\"},\"rootUri\":\"file:///home/mog/abcde\",\"capabilities\":{\"workspace\":{\"workspaceEdit\":{\"documentChanges\":true,\"resourceOperations\":[\"create\",\"rename\",\"delete\"]},\"applyEdit\":true,\"symbol\":{\"symbolKind\":{\"valueSet\":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]}},\"executeCommand\":{\"dynamicRegistration\":false},\"didChangeWatchedFiles\":{\"dynamicRegistration\":true},\"workspaceFolders\":true,\"configuration\":true,\"codeLens\":{\"refreshSupport\":true},\"fileOperations\":{\"didCreate\":false,\"willCreate\":false,\"didRename\":true,\"willRename\":true,\"didDelete\":false,\"willDelete\":false}},\"textDocument\":{\"declaration\":{\"linkSupport\":true},\"definition\":{\"linkSupport\":true},\"implementation\":{\"linkSupport\":true},\"typeDefinition\":{\"linkSupport\":true},\"synchronization\":{\"willSave\":true,\"didSave\":true,\"willSaveWaitUntil\":true},\"documentSymbol\":{\"symbolKind\":{\"valueSet\":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]},\"hierarchicalDocumentSymbolSupport\":true},\"formatting\":{\"dynamicRegistration\":true},\"rangeFormatting\":{\"dynamicRegistration\":true},\"rename\":{\"dynamicRegistration\":true,\"prepareSupport\":true},\"codeAction\":{\"dynamicRegistration\":true,\"isPreferredSupport\":true,\"codeActionLiteralSupport\":{\"codeActionKind\":{\"valueSet\":[\"\",\"quickfix\",\"refactor\",\"refactor.extract\",\"refactor.inline\",\"refactor.rewrite\",\"source\",\"source.organizeImports\"]}},\"resolveSupport\":{\"properties\":[\"edit\",\"command\"]},\"dataSupport\":true},\"completion\":{\"completionItem\":{\"snippetSupport\":true,\"documentationFormat\":[\"markdown\",\"plaintext\"],\"resolveAdditionalTextEditsSupport\":true,\"insertReplaceSupport\":true,\"deprecatedSupport\":true,\"resolveSupport\":{\"properties\":[\"documentation\",\"detail\",\"additionalTextEdits\",\"command\"]},\"insertTextModeSupport\":{\"valueSet\":[1,2]}},\"contextSupport\":true},\"signatureHelp\":{\"signatureInformation\":{\"parameterInformation\":{\"labelOffsetSupport\":true}}},\"documentLink\":{\"dynamicRegistration\":true,\"tooltipSupport\":true},\"hover\":{\"contentFormat\":[\"markdown\",\"plaintext\"]},\"callHierarchy\":{\"dynamicRegistration\":false},\"publishDiagnostics\":{\"relatedInformation\":true,\"tagSupport\":{\"valueSet\":[1,2]},\"versionSupport\":true},\"linkedEditingRange\":{\"dynamicRegistration\":true}},\"window\":{\"workDoneProgress\":true,\"showMessage\":null,\"showDocument\":{\"support\":true}}},\"initializationOptions\":null,\"workDoneToken\":\"1\"},\"id\":6", position: 2585, token: nil}
  (elixir 1.13.4) lib/stream.ex:1525: Stream.do_resource/5
  (elixir 1.13.4) lib/stream.ex:1719: Enumerable.Stream.do_each/4
  (elixir 1.13.4) lib/stream.ex:649: Stream.run/1
  (stdlib 3.17) erl_eval.erl:685: :erl_eval.do_apply/6
  (elixir 1.13.4) src/elixir.erl:296: :elixir.recur_eval/3
  (elixir 1.13.4) src/elixir.erl:274: :elixir.eval_forms/3
```

```
[Trace - 08:27:35 AM] Sending request 'initialize - (6)'.
Params: {
  "processId": null,
  "rootPath": "/home/mog/abcde",
  "clientInfo": {
    "name": "emacs",
    "version": "GNU Emacs 29.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.30, cairo version 1.16.0)"
  },
  "rootUri": "file:///home/mog/abcde",
  "capabilities": {
    "workspace": {
      "workspaceEdit": {
        "documentChanges": true,
        "resourceOperations": [
          "create",
          "rename",
          "delete"
        ]
      },
      "applyEdit": true,
      "symbol": {
        "symbolKind": {
          "valueSet": [
            1,
            2,
            3,
            4,
            5,
            6,
            7,
            8,
            9,
            10,
            11,
            12,
            13,
            14,
            15,
            16,
            17,
            18,
            19,
            20,
            21,
            22,
            23,
            24,
            25,
            26
          ]
        }
      },
      "executeCommand": {
        "dynamicRegistration": false
      },
      "didChangeWatchedFiles": {
        "dynamicRegistration": true
      },
      "workspaceFolders": true,
      "configuration": true,
      "codeLens": {
        "refreshSupport": true
      },
      "fileOperations": {
        "didCreate": false,
        "willCreate": false,
        "didRename": true,
        "willRename": true,
        "didDelete": false,
        "willDelete": false
      }
    },
    "textDocument": {
      "declaration": {
        "linkSupport": true
      },
      "definition": {
        "linkSupport": true
      },
      "implementation": {
        "linkSupport": true
      },
      "typeDefinition": {
        "linkSupport": true
      },
      "synchronization": {
        "willSave": true,
        "didSave": true,
        "willSaveWaitUntil": true
      },
      "documentSymbol": {
        "symbolKind": {
          "valueSet": [
            1,
            2,
            3,
            4,
            5,
            6,
            7,
            8,
            9,
            10,
            11,
            12,
            13,
            14,
            15,
            16,
            17,
            18,
            19,
            20,
            21,
            22,
            23,
            24,
            25,
            26
          ]
        },
        "hierarchicalDocumentSymbolSupport": true
      },
      "formatting": {
        "dynamicRegistration": true
      },
      "rangeFormatting": {
        "dynamicRegistration": true
      },
      "rename": {
        "dynamicRegistration": true,
        "prepareSupport": true
      },
      "codeAction": {
        "dynamicRegistration": true,
        "isPreferredSupport": true,
        "codeActionLiteralSupport": {
          "codeActionKind": {
            "valueSet": [
              "",
              "quickfix",
              "refactor",
              "refactor.extract",
              "refactor.inline",
              "refactor.rewrite",
              "source",
              "source.organizeImports"
            ]
          }
        },
        "resolveSupport": {
          "properties": [
            "edit",
            "command"
          ]
        },
        "dataSupport": true
      },
      "completion": {
        "completionItem": {
          "snippetSupport": true,
          "documentationFormat": [
            "markdown",
            "plaintext"
          ],
          "resolveAdditionalTextEditsSupport": true,
          "insertReplaceSupport": true,
          "deprecatedSupport": true,
          "resolveSupport": {
            "properties": [
              "documentation",
              "detail",
              "additionalTextEdits",
              "command"
            ]
          },
          "insertTextModeSupport": {
            "valueSet": [
              1,
              2
            ]
          }
        },
        "contextSupport": true
      },
      "signatureHelp": {
        "signatureInformation": {
          "parameterInformation": {
            "labelOffsetSupport": true
          }
        }
      },
      "documentLink": {
        "dynamicRegistration": true,
        "tooltipSupport": true
      },
      "hover": {
        "contentFormat": [
          "markdown",
          "plaintext"
        ]
      },
      "callHierarchy": {
        "dynamicRegistration": false
      },
      "publishDiagnostics": {
        "relatedInformation": true,
        "tagSupport": {
          "valueSet": [
            1,
            2
          ]
        },
        "versionSupport": true
      },
      "linkedEditingRange": {
        "dynamicRegistration": true
      }
    },
    "window": {
      "workDoneProgress": true,
      "showMessage": null,
      "showDocument": {
        "support": true
      }
    }
  },
  "initializationOptions": null,
  "workDoneToken": "1"
}


[Trace - 08:27:37 AM] Received notification 'window/logMessage'.
Params: {
  "message": "Started ElixirLS v0.10.0",
  "type": 4
}


[Trace - 08:27:37 AM] Received notification 'window/logMessage'.
Params: {
  "message": "Elixir version: \"1.13.4 (compiled with Erlang/OTP 24)\"",
  "type": 4
}


[Trace - 08:27:37 AM] Received notification 'window/logMessage'.
Params: {
  "message": "Erlang version: \"24\"",
  "type": 4
}


[Trace - 08:27:37 AM] Received notification 'window/logMessage'.
Params: {
  "message": "ElixirLS compiled with Elixir 1.13.4 and erlang 24",
  "type": 4
}


[Trace - 08:27:37 AM] Received notification 'window/logMessage'.
Params: {
  "message": "warning: Unable to read from device: %JasonVendored.DecodeError{data: \"\\n\\n{\\\"jsonrpc\\\":\\\"2.0\\\",\\\"method\\\":\\\"initialize\\\",\\\"params\\\":{\\\"processId\\\":null,\\\"rootPath\\\":\\\"/home/mog/abcde\\\",\\\"clientInfo\\\":{\\\"name\\\":\\\"emacs\\\",\\\"version\\\":\\\"GNU Emacs 29.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.30, cairo version 1.16.0)\\\"},\\\"rootUri\\\":\\\"file:///home/mog/abcde\\\",\\\"capabilities\\\":{\\\"workspace\\\":{\\\"workspaceEdit\\\":{\\\"documentChanges\\\":true,\\\"resourceOperations\\\":[\\\"create\\\",\\\"rename\\\",\\\"delete\\\"]},\\\"applyEdit\\\":true,\\\"symbol\\\":{\\\"symbolKind\\\":{\\\"valueSet\\\":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]}},\\\"executeCommand\\\":{\\\"dynamicRegistration\\\":false},\\\"didChangeWatchedFiles\\\":{\\\"dynamicRegistration\\\":true},\\\"workspaceFolders\\\":true,\\\"configuration\\\":true,\\\"codeLens\\\":{\\\"refreshSupport\\\":true},\\\"fileOperations\\\":{\\\"didCreate\\\":false,\\\"willCreate\\\":false,\\\"didRename\\\":true,\\\"willRename\\\":true,\\\"didDelete\\\":false,\\\"willDelete\\\":false}},\\\"textDocument\\\":{\\\"declaration\\\":{\\\"linkSupport\\\":true},\\\"definition\\\":{\\\"linkSupport\\\":true},\\\"implementation\\\":{\\\"linkSupport\\\":true},\\\"typeDefinition\\\":{\\\"linkSupport\\\":true},\\\"synchronization\\\":{\\\"willSave\\\":true,\\\"didSave\\\":true,\\\"willSaveWaitUntil\\\":true},\\\"documentSymbol\\\":{\\\"symbolKind\\\":{\\\"valueSet\\\":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]},\\\"hierarchicalDocumentSymbolSupport\\\":true},\\\"formatting\\\":{\\\"dynamicRegistration\\\":true},\\\"rangeFormatting\\\":{\\\"dynamicRegistration\\\":true},\\\"rename\\\":{\\\"dynamicRegistration\\\":true,\\\"prepareSupport\\\":true},\\\"codeAction\\\":{\\\"dynamicRegistration\\\":true,\\\"isPreferredSupport\\\":true,\\\"codeActionLiteralSupport\\\":{\\\"codeActionKind\\\":{\\\"valueSet\\\":[\\\"\\\",\\\"quickfix\\\",\\\"refactor\\\",\\\"refactor.extract\\\",\\\"refactor.inline\\\",\\\"refactor.rewrite\\\",\\\"source\\\",\\\"source.organizeImports\\\"]}},\\\"resolveSupport\\\":{\\\"properties\\\":[\\\"edit\\\",\\\"command\\\"]},\\\"dataSupport\\\":true},\\\"completion\\\":{\\\"completionItem\\\":{\\\"snippetSupport\\\":true,\\\"documentationFormat\\\":[\\\"markdown\\\",\\\"plaintext\\\"],\\\"resolveAdditionalTextEditsSupport\\\":true,\\\"insertReplaceSupport\\\":true,\\\"deprecatedSupport\\\":true,\\\"resolveSupport\\\":{\\\"properties\\\":[\\\"documentation\\\",\\\"detail\\\",\\\"additionalTextEdits\\\",\\\"command\\\"]},\\\"insertTextModeSupport\\\":{\\\"valueSet\\\":[1,2]}},\\\"contextSupport\\\":true},\\\"signatureHelp\\\":{\\\"signatureInformation\\\":{\\\"parameterInformation\\\":{\\\"labelOffsetSupport\\\":true}}},\\\"documentLink\\\":{\\\"dynamicRegistration\\\":true,\\\"tooltipSupport\\\":true},\\\"hover\\\":{\\\"contentFormat\\\":[\\\"markdown\\\",\\\"plaintext\\\"]},\\\"callHierarchy\\\":{\\\"dynamicRegistration\\\":false},\\\"publishDiagnostics\\\":{\\\"relatedInformation\\\":true,\\\"tagSupport\\\":{\\\"valueSet\\\":[1,2]},\\\"versionSupport\\\":true},\\\"linkedEditingRange\\\":{\\\"dynamicRegistration\\\":true}},\\\"window\\\":{\\\"workDoneProgress\\\":true,\\\"showMessage\\\":null,\\\"showDocument\\\":{\\\"support\\\":true}}},\\\"initializationOptions\\\":null,\\\"workDoneToken\\\":\\\"1\\\"},\\\"id\\\":6\", position: 2585, token: nil}\n  (elixir 1.13.4) lib/stream.ex:1525: Stream.do_resource/5\n  (elixir 1.13.4) lib/stream.ex:1719: Enumerable.Stream.do_each/4\n  (elixir 1.13.4) lib/stream.ex:649: Stream.run/1\n  (stdlib 3.17) erl_eval.erl:685: :erl_eval.do_apply/6\n  (elixir 1.13.4) src/elixir.erl:296: :elixir.recur_eval/3\n  (elixir 1.13.4) src/elixir.erl:274: :elixir.eval_forms/3\n",
  "type": 2
}
### Expected behavior
I would expect elixir-ls to work in emacs over tramp
<!--
A short description on how you expect the language server/debug adapter to behave.
-->

**Comment by lukaszsamson** [comment]
It looks like a content length or alignment problem. Notice ‘/n/n’ bytes at the front. Are you sure your client is sending valid protocol messages? Maybe it’s inserting some newlines. Closing as we generally we do not support faulty clients.
