### ISSUE TITLE
Error upon upgrading to version 1.14.0

### ISSUE THREAD

**Issue by enkr1** [elixir-lsp/elixir-ls#727]
I am totally clueless about this issue just hoping someone who understands can point out what is going wrong. It happens to me after upgrading the version. 

![image](https://user-images.githubusercontent.com/64194467/190382866-46df492b-2028-4df6-8efa-13723d43388b.png)

I could not resolve this "warning" (as it is not breaking the codes) even though I tried to:
- `rm -rf deps/` -> `mix deps.get`
- `rm -rf .elixir_ls/`
- `mix clean && mix deps.get`

```bash
** (ArgumentError) errors were found at the given arguments:

  * 1st argument: the table identifier does not refer to an existing ETS table

    (stdlib 4.0.1) :ets.member(Mix.Compilers.ApplicationTracer, Kernel)
    (mix 1.14.0) lib/mix/compilers/application_tracer.ex:89: Mix.Compilers.ApplicationTracer.trace/2
    (elixir 1.14.0) src/elixir_env.erl:30: :elixir_env."-trace/2-lc$^0/1-0-"/3
    (elixir 1.14.0) src/elixir_env.erl:30: :elixir_env.trace/2
    (elixir 1.14.0) src/elixir_dispatch.erl:185: :elixir_dispatch.do_expand_import/7
    (elixir 1.14.0) src/elixir_dispatch.erl:119: :elixir_dispatch.dispatch_import/6
```

**Comment by enkr1** [comment]
Update: 

The solution is: 
```bash
# Run these:
rm -rf deps/
mix deps.get
rm -rf .elixir_ls/

# Then you restart your vsc.
```

**Comment by enkr1** [comment]
Update: 
> It still happens after the solution above, but this is the current error logs:

```bash

09:43:18.859 [error] Process #PID<0.12212.0> raised an exception
** (UndefinedFunctionError) function :ranch_proxy_header.module_info/1 is undefined (module :ranch_proxy_header is not available)
    (ranch 1.8.0) :ranch_proxy_header.module_info(:compile)
    (language_server 0.11.0) lib/language_server/dialyzer.ex:440: ElixirLS.LanguageServer.Dialyzer.resolve_module_file/2
    (language_server 0.11.0) lib/language_server/dialyzer.ex:422: anonymous fn/2 in ElixirLS.LanguageServer.Dialyzer.add_warnings/2
    (elixir 1.14.0) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
    (language_server 0.11.0) lib/language_server/dialyzer.ex:417: ElixirLS.LanguageServer.Dialyzer.add_warnings/2
    (language_server 0.11.0) lib/language_server/dialyzer.ex:387: anonymous fn/7 in ElixirLS.LanguageServer.Dialyzer.compile/2
    (stdlib 4.0.1) timer.erl:235: :timer.tc/1
    (language_server 0.11.0) lib/language_server/dialyzer.ex:324: ElixirLS.LanguageServer.Dialyzer.compile/2
    ```

**Comment by lukaszsamson** [comment]
Can you share a project that reproduces your errors?
