### ISSUE TITLE
ElixirLS compilation of dependencies using rust packages fails aka "Build failed for unknown reason"

### ISSUE THREAD

**Issue by noslav** [elixir-lsp/elixir-ls#758]
### Environment

* Elixir & Erlang versions (elixir --version): 
Erlang/OTP 25 [erts-13.0] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns] [dtrace]
Elixir 1.13.4 (compiled with Erlang/OTP 25)
* Elixir Language Server version: 
Started ElixirLS v0.11.0
[Trace - 8:14:40 PM] Received notification 'window/logMessage'.
Params: {
    "message": "Elixir version: \"1.13.4 (compiled with Erlang/OTP 25)\"",
    "type": 4
}
* Operating system:  macos 12.2, darwin/amd64
* Editor or IDE name (e.g. Emacs/VSCode): 
    "clientInfo": {
        "name": "Visual Studio Code",
        "version": "1.72.2"
    },
* Editor Plugin/LSP Client name and version:

### Current behavior
On calling in the terminal
```elixir
mix deps.get 
mix deps.compile 
```
I get to a point where it compiles a dependency that needs rust packages..
```
==> ex_secp256k1
Compiling 2 files (.ex)
    Updating crates.io index
Compiling lib/ex_secp256k1/impl.ex (it's taking more than 10s)                                                                                                
       Fetch [=============>           ]  57.34%, (61723/143663) resolving deltas    
       ..

Compiling lib/ex_secp256k1/impl.ex (it's taking more than 10s)                                                                                                
  Downloaded rand_core v0.6.4
  Downloaded proc-macro2 v1.0.47
  Downloaded serde v1.0.147
  Downloaded base64 v0.13.1
  Downloaded unicode-ident v1.0.5
  Downloaded unicode-segmentation v1.10.0
  Downloaded syn v1.0.103
  Downloaded libc v0.2.137
  Downloaded getrandom v0.2.8
  Downloaded serde_derive v1.0.147
  Downloaded 10 crates (1.3 MB) in 2.44s
Compiling crate exsecp256k1 in release mode (native/exsecp256k1)
```
This however does not happen on the `elixirls` end, it simply fails -

```
[Warn  - 8:16:33 PM] could not compile dependency :ex_secp256k1, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile ex_secp256k1", update it with "mix deps.update ex_secp256k1" or clean it with "mix deps.clean ex_secp256k1"
[Trace - 8:16:33 PM] Received notification 'textDocument/publishDiagnostics'.
Params: {
    "diagnostics": [
        {
            "message": "Build failed for unknown reason. See output log.",
            "range": {
                "end": {
                    "character": 0,
                    "line": 0
                },
                "start": {
                    "character": 0,
                    "line": 0
                }
            },
            "severity": 1,
            "source": "ElixirLS"
        }
    ],
    "uri": "file:///Users/pranay/Documents/covalent/elixir-projects/rudder/mix.exs"
}
```

### Expected behavior

Should compile with rust toolchain which can be installed with

`curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh && source "$HOME/.cargo/env"`

**Comment by lukaszsamson** [comment]
@noslav Can you share a simple project that reproduces it? I work with projects using rust deps and they build fine

**Comment by noslav** [comment]
Hi @lukaszsamson  thanks for getting back (apologies for the delay on my end was OOO) -  git@github.com:izelnakri/eth.git please try this project for which I get the same issues.
please find the logs here 

```


[33mCompiling on macOS requires special link args in order to compile
correctly.

Rustler is currently working around this issue in the compiler task.
This will be removed in v1.0.0 in favor of a user supplied .cargo/config
file.

To remove this warning, please create /Users/pranay/Documents/covalent/elixir-projects/eth/deps/ex_keccak/native/exkeccak/.cargo/config
with the following content:

      [target.x86_64-apple-darwin]
      rustflags = [
          "-C", "link-arg=-undefined",
          "-C", "link-arg=dynamic_lookup",
      ]

See https://developer.apple.com/library/archive/documentation/DeveloperTools/Conceptual/MachOTopics/1-Articles/executing_files.html
for more details.

[39m
[Trace - 1:24:39 PM] Received notification 'window/logMessage'.
Params: {
    "message": "\n== Compilation error in file lib/ex_keccak.ex ==\n** (ErlangError) Erlang error: :enoent\n    (elixir 1.13.4) lib/system.ex:1044: System.cmd(\"cargo\", [\"rustc\", \"--release\", \"--\", \"-C\", \"link-arg=-undefined\", \"-C\", \"link-arg=dynamic_lookup\"], [cd: \"/Users/pranay/Documents/covalent/elixir-projects/eth/deps/ex_keccak/native/exkeccak\", stderr_to_stdout: true, env: [{\"CARGO_TARGET_DIR\", \"/Users/pranay/Documents/covalent/elixir-projects/eth/.elixir_ls/build/dev_dev/lib/ex_keccak/native/exkeccak\"}], into: %IO.Stream{device: :standard_io, line_or_bytes: :line, raw: false}])\n    (rustler 0.22.0) lib/rustler/compiler.ex:27: Rustler.Compiler.compile_crate/2\n    lib/ex_keccak.ex:2: (module)",
    "type": 4
}



== Compilation error in file lib/ex_keccak.ex ==
** (ErlangError) Erlang error: :enoent
    (elixir 1.13.4) lib/system.ex:1044: System.cmd("cargo", ["rustc", "--release", "--", "-C", "link-arg=-undefined", "-C", "link-arg=dynamic_lookup"], [cd: "/Users/pranay/Documents/covalent/elixir-projects/eth/deps/ex_keccak/native/exkeccak", stderr_to_stdout: true, env: [{"CARGO_TARGET_DIR", "/Users/pranay/Documents/covalent/elixir-projects/eth/.elixir_ls/build/dev_dev/lib/ex_keccak/native/exkeccak"}], into: %IO.Stream{device: :standard_io, line_or_bytes: :line, raw: false}])
    (rustler 0.22.0) lib/rustler/compiler.ex:27: Rustler.Compiler.compile_crate/2
    lib/ex_keccak.ex:2: (module)
[Trace - 1:24:39 PM] Received notification 'window/logMessage'.
Params: {
    "message": "could not compile dependency :ex_keccak, \"mix compile\" failed. Errors may have been logged above. You can recompile this dependency with \"mix deps.compile ex_keccak\", update it with \"mix deps.update ex_keccak\" or clean it with \"mix deps.clean ex_keccak\"",
    "type": 2
}


[Warn  - 1:24:39 PM] could not compile dependency :ex_keccak, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile ex_keccak", update it with "mix deps.update ex_keccak" or clean it with "mix deps.clean ex_keccak"
[Trace - 1:24:39 PM] Received notification 'textDocument/publishDiagnostics'.
Params: {
    "diagnostics": [
        {
            "message": "Build failed for unknown reason. See output log.",
            "range": {
                "end": {
                    "character": 0,
                    "line": 0
                },
                "start": {
                    "character": 0,
                    "line": 0
                }
            },
            "severity": 1,
            "source": "ElixirLS"
        }
    ],
    "uri": "file:///Users/pranay/Documents/covalent/elixir-projects/eth/mix.exs"
}
```

**Comment by noslav** [comment]
@lukaszsamson I looked elsewhere https://github.com/JakeBecker/elixir-ls/issues/71#issuecomment-407174183 and setting this vscode plugin settings `"elixirLS.fetchDeps": false`, & running `rm -rf deps _build .elixir_ls && mix deps.get` and then opening the repo in vscode allows me to reach this step 

```
[Info  - 1:52:51 PM] [ElixirLS Dialyzer] Analyzing 1019 modules: [:idna_table, Avrora.Utils.Registrar, Poison.Encoder.Map, Phoenix.Endpoint, FileSystem.Backends.FSWindows, Phoenix.Param.Any, WebSockex.HandshakeError, Plug.CSRFProtection.InvalidCSRFTokenError, Rudder.Network.EthereumMainnet, Rudder.Avro.Client.Storage.File, Credo.SourceFile, Plug.Static, :cow_hpack, Plug.Debugger, Avrora.Codec.Plain, Credo.Check.Params, Credo.CLI.Command.List.ListCommand.PrintResultsAndSummary, Jason.Encoder.Float, Mint.TunnelProxy, :snappyer, Jason.Decoder.Unescape, Phoenix.PubSub.Supervisor, Avrora.Storage.Registry, Credo.Check.Warning.BoolOperationOnSameValues, Jason.Decoder, String.Chars.Rudder.SHA256, Dialyxir, :hackney_connections, Toml.Builder, Collectable, Credo.Check.Design.DuplicatedCode, Credo.Code.Sigils, Credo.CLI.Command.Suggest.Output.Oneline, Credo.ConfigFile, Credo.Check.Consistency.TabsOrSpaces.Collector, Rudder.Avro.Client.Config, Redix.Connection, HPAX.Table, HTTPoison.AsyncEnd, Dialyxir.Formatter.Github, Dialyxir.Formatter.IgnoreFile, Credo.CLI.Command.Info.InfoCommand.PrintInfo, Credo.Check.Warning.UnusedTupleOperation, Credo.Check.Warning.MixEnv, :cowboy_clock, Credo.Check.Warning.UnusedFileOperation, Mint.HTTP2.Frame, HTTPoison.Handlers.Multipart, Poison.Decoder, Credo.Check.Refactor.NegatedIsNil, ...]
```
 Think this hack fixes it for now but switching branches makes it reappear. A more permanent solution would of course be appreciated.
