### ISSUE TITLE
ex_cldr warning appears to be causing ElixirLS to reboot-loop

### ISSUE THREAD

**Issue by jarrodmoldrich** [elixir-lsp/elixir-ls#769]
### Environment

Erlang/OTP 25 [erts-13.1.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]
Elixir 1.13.4 (compiled with Erlang/OTP 25)
ElixirLS v0.12.0
MacOS
VSCode - ElixirLS: Elixir support and debugger v0.12.0

### Current behavior

ex_cldr warning appears to be causing ElixirLS to reboot-loop.  Took me a lot of time to deduce the problem, so I'm hoping this finds a larger issue that saves other people some time.

```
==> public
Compiling 40 files (.ex)
[Warn  - 4:27:13 PM] warning: Using the global configuration is deprecated.  Global configuration only supports the [:json_library, :default_locale, :default_backend, :cacertfile, :data_dir, :force_locale_download] keys. The keys [:locales] should be configured in a backend module or via the :otp_app configuration of a backend module.  See the readme for further information.

Generating Public.Cldr for 3 locales named ["ar", "en", "und"] with a default locale named "en"
Generated public app

...

==> public_web
Compiling 54 files (.ex)
Generated public_web app
[Info  - 4:27:25 PM] Compile took 80140 milliseconds
[Info  - 4:27:25 PM] [ElixirLS Dialyzer] Checking for stale beam files
[Error - 4:27:25 PM] GenServer ElixirLS.LanguageServer.Server terminating
** (FunctionClauseError) no function clause matching in IO.chardata_to_string/1
    (elixir 1.13.4) lib/io.ex:627: IO.chardata_to_string(nil)
    (elixir 1.13.4) lib/path.ex:689: Path.expand_home/1
    (elixir 1.13.4) lib/path.ex:162: Path.expand/1
    (language_server 0.12.0) lib/language_server/source_file/path.ex:47: ElixirLS.LanguageServer.SourceFile.Path.to_uri/1
    (language_server 0.12.0) lib/language_server/server.ex:1085: anonymous fn/4 in ElixirLS.LanguageServer.Server.publish_diagnostics/3
    (elixir 1.13.4) lib/enum.ex:2396: Enum."-reduce/3-lists^foldl/2-0-"/3
    (language_server 0.12.0) lib/language_server/server.ex:1084: ElixirLS.LanguageServer.Server.publish_diagnostics/3
    (language_server 0.12.0) lib/language_server/server.ex:1008: ElixirLS.LanguageServer.Server.handle_build_result/3
Last message: {:"$gen_cast", {:build_finished, {:ok, [%Mix.Task.Compiler.Diagnostic{compiler_name: "Elixir", details: nil, file: nil, message: "Using the global configuration is deprecated.  Global configuration only supports the [:json_library, :default_locale, :default_backend, :cacertfile, :data_dir, :force_locale_download] keys. The keys [:locales] should be configured in a backend module or via the :otp_app configuration of a backend module.  See the readme for further information.", position: 0, severity: :warning}]}}}
State: %ElixirLS.LanguageServer.Server{analysis_ready?: false, awaiting_contracts: [], build_diagnostics: [], build_ref: #Reference<0.1874104614.347340804.250653>, build_running?: true, client_capabilities: %{"general" => %{"markdown" => %{"parser" => "marked", "version" => "1.1.0"}, "positionEncodings" => ["utf-16"], "regularExpressions" => %{"engine" => "ECMAScript", "version" => "ES2020"}, "staleRequestSupport" => %{"cancel" => true, "retryOnContentModified" => ["textDocument/semanticTokens/full", "textDocument/semanticTokens/range", "textDocument/semanticTokens/full/delta"]}}, "notebookDocument" => %{"synchronization" => %{"dynamicRegistration" => true, "executionSummarySupport" => true}}, "textDocument" => %{"callHierarchy" => %{"dynamicRegistration" => true}, "codeAction" => %{"codeActionLiteralSupport" => %{"codeActionKind" => %{"valueSet" => ["", "quickfix", "refactor", "refactor.extract", "refactor.inline", "refactor.rewrite", "source", "source.organizeImports"]}}, "dataSupport" => true, "disabledSupport" => true, "dynamicRegistration" => true, "honorsChangeAnnotations" => false, "isPreferredSupport" => true, "resolveSupport" => %{"properties" => ["edit"]}}, "codeLens" => %{"dynamicRegistration" => true}, "colorProvider" => %{"dynamicRegistration" => true}, "completion" => %{"completionItem" => %{"commitCharactersSupport" => true, "deprecatedSupport" => true, "documentationFormat" => ["markdown", "plaintext"], "insertReplaceSupport" => true, "insertTextModeSupport" => %{"valueSet" => [1, 2]}, "labelDetailsSupport" => true, "preselectSupport" => true, "resolveSupport" => %{"properties" => ["documentation", "detail", "additionalTextEdits"]}, "snippetSupport" => true, "tagSupport" => %{"valueSet" => [1]}}, "completionItemKind" => %{"valueSet" => [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]}, "completionList" => %{"itemDefaults" => ["commitCharacters", "editRange", "insertTextFormat", "insertTextMode"]}, "contextSupport" => true, "dynamicRegistration" => true, "insertTextMode" => 2}, "declaration" => %{"dynamicRegistration" => true, "linkSupport" => true}, "definition" => %{"dynamicRegistration" => true, "linkSupport" => true}, "diagnostic" => %{"dynamicRegistration" => true, "relatedDocumentSupport" => false}, "documentHighlight" => %{"dynamicRegistration" => true}, "documentLink" => %{"dynamicRegistration" => true, "tooltipSupport" => true}, "documentSymbol" => %{"dynamicRegistration" => true, "hierarchicalDocumentSymbolSupport" => true, "labelSupport" => true, "symbolKind" => %{"valueSet" => [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, ...]}, "tagSupport" => %{"valueSet" => [1]}}, "foldingRange" => %{"dynamicRegistration" => true, "foldingRange" => %{"collapsedText" => false}, "foldingRangeKind" => %{"valueSet" => ["comment", "imports", "region"]}, "lineFoldingOnly" => true, "rangeLimit" => 5000}, "formatting" => %{"dynamicRegistration" => true}, "hover" => %{"contentFormat" => ["markdown", "plaintext"], "dynamicRegistration" => true}, "implementation" => %{"dynamicRegistration" => true, "linkSupport" => true}, "inlayHint" => %{"dynamicRegistration" => true, "resolveSupport" => %{"properties" => ["tooltip", "textEdits", "label.tooltip", "label.location", "label.command"]}}, "inlineValue" => %{"dynamicRegistration" => true}, "linkedEditingRange" => %{"dynamicRegistration" => true}, "onTypeFormatting" => %{"dynamicRegistration" => true}, "publishDiagnostics" => %{"codeDescriptionSupport" => true, "dataSupport" => true, "relatedInformation" => true, "tagSupport" => %{"valueSet" => [1, 2]}, "versionSupport" => false}, "rangeFormatting" => %{"dynamicRegistration" => true}, "references" => %{"dynamicRegistration" => true}, "rename" => %{"dynamicRegistration" => true, "honorsChangeAnnotations" => true, "prepareSupport" => true, "prepareSupportDefaultBehavior" => 1}, "selectionRange" => %{"dynamicRegistration" => true}, "semanticTokens" => %{"augmentsSyntaxTokens" => true, "dynamicRegistration" => true, "formats" => ["relative"], "multilineTokenSupport" => false, "overlappingTokenSupport" => false, "requests" => %{"full" => %{"delta" => true}, "range" => true}, "serverCancelSupport" => true, "tokenModifiers" => ["declaration", "definition", "readonly", "static", "deprecated", "abstract", "async", "modification", ...], "tokenTypes" => ["namespace", "type", "class", "enum", "interface", "struct", "typeParameter", ...]}, "signatureHelp" => %{"contextSupport" => true, "dynamicRegistration" => true, "signatureInformation" => %{"activeParameterSupport" => true, "documentationFormat" => ["markdown", "plaintext"], "parameterInformation" => %{"labelOffsetSupport" => true}}}, "synchronization" => %{"didSave" => true, "dynamicRegistration" => true, "willSave" => true, "willSaveWaitUntil" => true}, "typeDefinition" => %{"dynamicRegistration" => true, "linkSupport" => true}, "typeHierarchy" => %{"dynamicRegistration" => true}}, "window" => %{"showDocument" => %{"support" => true}, "showMessage" => %{"messageActionItem" => %{"additionalPropertiesSupport" => true}}, "workDoneProgress" => true}, "workspace" => %{"applyEdit" => true, "codeLens" => %{"refreshSupport" => true}, "configuration" => true, "diagnostics" => %{"refreshSupport" => true}, "didChangeConfiguration" => %{"dynamicRegistration" => true}, "didChangeWatchedFiles" => %{"dynamicRegistration" => true, "relativePatternSupport" => true}, "executeCommand" => %{"dynamicRegistration" => true}, "fileOperations" => %{"didCreate" => true, "didDelete" => true, "didRename" => true, "dynamicRegistration" => true, "willCreate" => true, "willDelete" => true, "willRename" => true}, "inlayHint" => %{"refreshSupport" => true}, "inlineValue" => %{"refreshSupport" => true}, "semanticTokens" => %{"refreshSupport" => true}, "symbol" => %{"dynamicRegistration" => true, "resolveSupport" => %{"properties" => ["location.range"]}, "symbolKind" => %{"valueSet" => [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, ...]}, "tagSupport" => %{"valueSet" => [1]}}, "workspaceEdit" => %{"changeAnnotationSupport" => %{"groupsOnLabel" => true}, "documentChanges" => true, "failureHandling" => "textOnlyTransactional", "normalizesLineEndings" => true, "resourceOperations" => ["create", "rename", "delete"]}}}, dialyzer_diagnostics: [], dialyzer_sup: #PID<0.132.0>, mix_project?: true, needs_build?: false, no_mixfile_warned?: false, project_dir: "/Users/admin/dev/moldrich/whenbrush/services", received_shutdown?: false, requests: %{}, root_uri: "file:///Users/admin/dev/moldrich/whenbrush/services", server_instance_id: "vqIn329nOhKNrNzmI9lp (truncated)
[Info  - 4:27:28 PM] Connection to server got closed. Server will restart.
[Info  - 4:27:29 PM] Started ElixirLS v0.12.0
...
```

*Preconditions:*

1. Have an app with `{:ex_cldr, "~> 2.20"}` as a dependency (I haven't tried a newer version)

*Reproduction Steps:*

1. Add a bad global config such as including `locales` which is unsupported in config files:
        ```
        config :ex_cldr,
          locales: ["en", "es"]
        ```
3. Delete `.elixir_ls` directory
4. Restart VSCode
5. Observe ElixirLS compiling project
6. Observe `FunctionClauseError`

### Expected behavior

ElixirLS finishes processing and delivers the warning to the IDE

**Comment by lukaszsamson** [comment]
@jarrodmoldrich I can't reproduce it. I created a new app, added `{:ex_cldr, "~> 2.20"}` as dep (which installed 2.34), added `config :ex_cldr, locales: ["en", "es"]` but there are no warnings generated. Even when I explicitely downgraded to 2.20 still no warnings nor crashes.
Please post a simple project that reproduces it. I'd like to know where that `nil` path is coming from.

**Comment by jarrodmoldrich** [comment]
Thank you for looking at this! I'll try to find a time in the next couple of weeks to isolate this further.

**Comment by jarrodmoldrich** [comment]
Hi @lukaszsamson , I'd been suffering this issue for months, but now that I try to reproduce it, it does not.  I'll close this for now.
