### ISSUE TITLE
MatchError when :dialyzer.format_warning/1 returns an error

### ISSUE THREAD

**Issue by Moronisauner** [elixir-lsp/elixir-ls#84]
https://github.com/elixir-lsp/elixir-ls/blob/bb85efc657148b33c69457380dfe0c6a573efd43/apps/language_server/lib/language_server/dialyzer.ex#L461

The log:
```
** (MatchError) no match of right hand side value: {:error, {1, :erl_parse, ['syntax error before: ', '\'?\'']}}
    dialyzer.erl:626: anonymous fn/1 in :dialyzer.sig/2
    dialyzer.erl:541: :dialyzer.call_or_apply_to_string/6
    dialyzer.erl:322: :dialyzer.message_to_string/2
    dialyzer.erl:297: :dialyzer.format_warning/2
    (language_server) lib/language_server/dialyzer.ex:461: ElixirLS.LanguageServer.Dialyzer.dialyzer_raw_warning_message/1
    (language_server) lib/language_server/dialyzer.ex:421: anonymous fn/4 in ElixirLS.LanguageServer.Dialyzer.to_diagnostics/3
    (elixir) lib/enum.ex:1940: Enum."-reduce/3-lists^foldl/2-0-"/3
    (stdlib) maps.erl:232: :maps.fold_1/3
Last message (from #PID<0.2866.0>): {:analysis_finished, :ok, {:plt, #Reference<0.428144727.440533000.7688>, #Reference<0.428144727.440533000.7690>, #Reference<0.428144727.440533000.7689>, #Reference<0.428144727.440533000.7691>, #Reference<0.428144727.440533000.7692>},
```

**Comment by axelson** [comment]
Do you know what file it was parsing when you received this error?

**Comment by Moronisauner** [comment]
I was using the vscode extension when this error occurred. I don't know what file specifically was parsing.

**Comment by Moronisauner** [comment]
I deleted the `.elixir_ls`  folder and the error disappeared. :flushed:

**Comment by lukaszsamson** [comment]
Closing as OP is no longer able to reproduce.
