### ISSUE TITLE
Finding references crashes on live_view components

### ISSUE THREAD

**Issue by tcoopman** [elixir-lsp/elixir-ls#842]
### Precheck

This looks similar to: https://github.com/elixir-lsp/elixir-ls/issues/761 but that issue is already fixed an closed. 

### Environment

* Elixir & Erlang versions (elixir --version): Erlang/OTP 25 [erts-13.1.5] [source] [64-bit] [smp:32:32] [ds:32:32:10] [async-threads:1] [jit:ns]
* Elixir Language Server version: 0.13.0
* Operating system: linux
* Editor or IDE name (e.g. Emacs/VSCode): Helix

### Current behavior

On doing go to reference, the elixir-ls crashes with:

```
2023-03-10T13:42:25.376 helix_lsp::transport [ERROR] <- ServerError(-32000): an exception was raised:
    ** (ArithmeticError) bad argument in arithmetic expression
        (language_server 0.13.0) lib/language_server/source_file.ex:334: ElixirLS.LanguageServer.SourceFile.elixir_position_to_lsp/2
        (language_server 0.13.0) lib/language_server/providers/references.ex:34: ElixirLS.LanguageServer.Providers.References.build_reference/3
        (elixir 1.14.3) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
        (kernel 8.5.3) global.erl:477: :global.trans/4
        (language_server 0.13.0) lib/language_server/server.ex:595: anonymous fn/5 in ElixirLS.LanguageServer.Server.handle_request/2
        (language_server 0.13.0) lib/language_server/server.ex:798: anonymous fn/3 in ElixirLS.LanguageServer.Server.handle_request_async/2
```

The module where it fails (but it fails in other components as well):

```elixir
defmodule DomainModellingWeb.Components.ExerciseNavigation do
  use DomainModellingWeb, :component

  attr(:sections, :list)
  attr(:scenarios, :list)

  def nav(assigns) do
    ~H"""
    <div class="lg:sticky bg-neutral-200">
      <nav aria-labelledby="on-this-page-title">
        <h2 id="on-this-page-title" class="font-display text-sm font-medium text-neutral-900 mt-12">
          Scenarios
        </h2>
        <ol role="list" class="mt-4 space-y-3 text-sm">
          <li :for={scenario <- @scenarios} key={scenario.title}>
            <h3>
              <a
                href={"##{scenario.title}"}
                class={[
                  scenario.status == "initial" && "text-neutral-600",
                  scenario.status == "failure" && "text-error-600",
                  scenario.status == "success" && "text-success-600",
                  "font-normal hover:text-neutral-700"
                ]}
              >
                <%= scenario.title %>
              </a>
            </h3>
          </li>
        </ol>
      </nav>
    </div>
    """
  end
end

```

**Comment by lukaszsamson** [comment]
Is this the module being referenced or referencing? On what function do you invoke the provider?

**Comment by tcoopman** [comment]
I call it on the module name itself. The nav function component is used in the project
