### ISSUE TITLE
No attribute completions

### ISSUE THREAD

**Issue by lukaszsamson** [elixir-lsp/elixir-ls#857]
No completions after `@` in the following snipped
```
defmodule My do
def start_link(id) do
    GenServer.start_link(__MODULE__, id, name: via_tuple(id))
  end

  @
  def init(id) do
    {:ok,
     %Some.Mod{
       id: id,
       events: [],
       version: 0
     }}
  end
end

**Comment by samwightt** [comment]
Hmmm this is odd. If you remove the `start_link` function it works as expected (`@impl true` will autocomplete). But if you leave the `start_link` function defined, it doesn't work for some reason.

**Comment by lukaszsamson** [comment]
The reason is crash in metadata parser
```
[Warn  - 17:08:36] ** (ErlangError) Erlang error: "CaseClauseError during metadata build pre:\nno case clause matching: [{:init, [line: 7, column: 9], [{:id, [line: 7, column: 14], nil}]}, [do: {:ok, {:%, [line: 9, column: 8], [{:__aliases__, [line: 9, column: 9], [:Some, :Mod]}, {:%{}, [line: 9, column: 17], [id: {:id, [line: 10, column: 14], nil}, events: [], version: 0]}]}}]]\nast node: {:@, [line: 6, column: 5], [{:def, [line: 7, column: 5], [{:init, [line: 7, column: 9], [{:id, [line: 7, column: 14], nil}]}, [do: {:ok, {:%, [line: 9, column: 8], [{:__aliases__, [line: 9, column: 9], [:Some, :Mod]}, {:%{}, [line: 9, column: 17], [id: {:id, [line: 10, column: 14], nil}, events: [], version: 0]}]}}]]}]}"
    (elixir_sense 2.0.0) lib/elixir_sense/core/metadata_builder.ex:671: ElixirSense.Core.MetadataBuilder.pre/2
    (elixir_sense 2.0.0) lib/elixir_sense/core/metadata_builder.ex:62: anonymous fn/4 in ElixirSense.Core.MetadataBuilder.safe_call/2
    (elixir 1.15.0-rc.1) lib/macro.ex:688: anonymous fn/4 in Macro.do_traverse_args/4
    (stdlib 4.3.1) lists.erl:1462: :lists.mapfoldl_1/3
    (stdlib 4.3.1) lists.erl:1463: :lists.mapfoldl_1/3
    (elixir 1.15.0-rc.1) lib/macro.ex:653: Macro.do_traverse/4
    (elixir 1.15.0-rc.1) lib/macro.ex:668: Macro.do_traverse/4
    (stdlib 4.3.1) lists.erl:1462: :lists.mapfoldl_1/3
```
