### ISSUE TITLE
Compilation errors are not showing up

### ISSUE THREAD

**Issue by axelson** [elixir-lsp/elixir-ls#90]
It looks like on the current master branch, compilation errors are not being appropriately reported. This blocks the next release of the extension.

**Comment by lukaszsamson** [comment]
This also happens on the latest release (0.28).
<img width="466" alt="Screenshot 2020-01-17 at 11 30 51" src="https://user-images.githubusercontent.com/1078186/72605336-deea8380-391c-11ea-8658-952765ce3d78.png">

It seems there was a breaking change somewhere. I was able to locate a crash in vscode that seems to be caused by a message from elixir-ls
```
ERR e.message.replace is not a function: TypeError: e.message.replace is not a function
    at i (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1619:933)
    at Object.e.makeKey (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1620:416)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2860:210
    at Array.map (<anonymous>)
    at t.MarkersModel.setResourceMarkers (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2860:180)
    at p.onMarkerChanged (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2976:304)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2976:237
    at c.fire (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:114:893)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:110:964
```
<img width="945" alt="Screenshot 2020-01-17 at 11 28 45" src="https://user-images.githubusercontent.com/1078186/72605542-46a0ce80-391d-11ea-9f7a-1211ed123f27.png">
Clearly, there's a Javascript array but the marker code is expecting a string.
