### ISSUE TITLE
Launch script can fail

### ISSUE THREAD

**Issue by lukaszsamson** [elixir-lsp/elixir-ls#944]
```
** (ArgumentError) could not call Module.put_attribute/3 because the module ElixirLS.Shell.Quiet is already compiled
    (elixir 1.14.4) lib/module.ex:2504: Module.assert_not_readonly!/2
    (elixir 1.14.4) lib/module.ex:2201: Module.__put_attribute__/5
```
Reported in https://elixirforum.com/t/elixirls-extension-not-working-support-needed-using-asdf-brew-elixir/57030

**Comment by lukaszsamson** [comment]
Can you check what this returns?
```
elixir -e "ElixirLS.Shell.Quiet.module_info()"
```
Normally it returns something like
```
** (UndefinedFunctionError) function ElixirLS.Shell.Quiet.module_info/0 is undefined (module ElixirLS.Shell.Quiet is not available)
    ElixirLS.Shell.Quiet.module_info()
    nofile:1: (file)
    (stdlib 4.3.1.1) erl_eval.erl:748: :erl_eval.do_apply/7
    (elixir 1.15.2) lib/code.ex:543: Code.validated_eval_string/3
```

**Comment by nathankg** [comment]
Yes, I think it printed nearly that!

```
nathangupta@Nathans-MacBook-Pro checkmate_api % elixir -e "ElixirLS.Shell.Quiet.module_info()"
** (UndefinedFunctionError) function ElixirLS.Shell.Quiet.module_info/0 is undefined (module ElixirLS.Shell.Quiet is not available)
    ElixirLS.Shell.Quiet.module_info()
    nofile:1: (file)
    (stdlib 4.3) erl_eval.erl:748: :erl_eval.do_apply/7
    (elixir 1.14.4) lib/code.ex:425: Code.validated_eval_string/3
```

**Comment by pro100andrey** [comment]
Hi all, same issue

```
Running /Users/_user_/.vscode/extensions/jakebecker.elixir-ls-0.16.0/elixir-ls-release/launch.sh
Preffered shell is zsh, relaunching
Looking for ASDF install
ASDF install found in /usr/local/opt/asdf/libexec/asdf.sh, sourcing
** (ArgumentError) could not call Module.put_attribute/3 because the module ElixirLS.Shell.Quiet is already compiled
    (elixir 1.15.5) lib/module.ex:2310: Module.assert_not_readonly!/2
    (elixir 1.15.5) lib/module.ex:2007: Module.__put_attribute__/5
    /Users/_user_/.vscode/extensions/jakebecker.elixir-ls-0.16.0/elixir-ls-release/installer.exs:60: (module)
    /Users/_user_/.vscode/extensions/jakebecker.elixir-ls-0.16.0/elixir-ls-release/installer.exs:59: (file)
[Error - 13:05:29] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 13:05:29] Connection to server got closed. Server will restart.
true
[Error - 13:05:29] ElixirLS - server client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097
```

```
➜ ~ asdf list

elixir
 *1.15.5-otp-25
erlang
 *25.3.2.5
```


```
➜ ~ code --version

1.81.1
6c3e3dba23e8fadc360aed75ce363ba185c49794
x64
```

```
➜ ~ sw_vers

ProductName:		macOS
ProductVersion:		13.5.1
BuildVersion:		22G90
```

**Comment by lukaszsamson** [comment]
Closing as there is no way to reproduce this
