### ISSUE TITLE
VERSION not found

### ISSUE THREAD

**Issue by quolpr** [elixir-lsp/elixir-ls#969]
I used nvim lsp with nvim-lspconfig. But it is actually doesn't matter. I made clone of latest version:

```
git clone https://github.com/elixir-lsp/elixir-ls.git ~/.elixir-ls
git checkout v0.16.0
```
And get this error when try to start server:

```
➜  git:(dev) ✗ /Users/quolpr/.elixir-ls/scripts/language_server.sh

Running /Users/quolpr/.elixir-ls/scripts/launch.sh
Preffered shell is zsh, relaunching
Looking for ASDF install
ASDF install found in /Users/quolpr/.asdf/asdf.sh, sourcing
Mix.install failed with ** (File.Error) could not read file "/Users/quolpr/.elixir-ls/scripts/VERSION": no such file or directory
    (elixir 1.15.4) lib/file.ex:358: File.read!/1
    /Users/quolpr/.elixir-ls/scripts/installer.exs:508: ElixirLS.Installer.get_release/0
    /Users/quolpr/.elixir-ls/scripts/installer.exs:522: ElixirLS.Installer.install/1
    /Users/quolpr/.elixir-ls/scripts/installer.exs:543: ElixirLS.Installer.install_with_retry/0
    /Users/quolpr/.elixir-ls/scripts/quiet_install.exs:14: (file)
    (elixir 1.15.4) src/elixir_compiler.erl:67: :elixir_compiler.dispatch/4
    (elixir 1.15.4) src/elixir_compiler.erl:52: :elixir_compiler.compile/3
    (elixir 1.15.4) src/elixir_compiler.erl:39: :elixir_compiler.maybe_fast_compile/3

Retrying Mix.install with force: true
** (File.Error) could not read file "/Users/quolpr/.elixir-ls/scripts/VERSION": no such file or directory
    (elixir 1.15.4) lib/file.ex:358: File.read!/1
    /Users/quolpr/.elixir-ls/scripts/installer.exs:508: ElixirLS.Installer.get_release/0
    /Users/quolpr/.elixir-ls/scripts/installer.exs:522: ElixirLS.Installer.install/1
    /Users/quolpr/.elixir-ls/scripts/quiet_install.exs:14: (file)

```

**Comment by lukaszsamson** [comment]
Please follow official install instructions https://github.com/elixir-lsp/elixir-ls#mixinstall-based-release
If you want to use a released version you need to create a release (which will write the `VERSION` file to the output dir).
If you want to use your local copy for development of ElixirLS, you need to run with `ELS_LOCAL=1`.
