### ISSUE TITLE
Sourceror dependency conflicting with user code

### ISSUE THREAD

**Issue by Zurga** [elixir-lsp/elixir-ls#977]
### Environment

* Elixir & Erlang versions (elixir --version): 
```
Erlang/OTP 25 [erts-13.2.2] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit:ns]

Elixir 1.14.4 (compiled with Erlang/OTP 25)
```
* Elixir Language Server version: v0.14.6
* Operating system: nixos
* Editor or IDE name (e.g. Emacs/VSCode): helix
* Editor Plugin/LSP Client name and version:elixir-ls

### Current behavior

When the dependency on Sourceror was updated (from 0.11.2 to 0.13.0) in my project, the langauge server failed to compile my code. It seems like the dependencies for elixir-ls and my project should not be mixed together since elixir-ls is using `0.11.2`.

I have the following logs:
```
2023-09-02T21:59:02.881 helix_term::application [INFO] window/logMessage: LogMessageParams { typ: Warning, message: "warning: redefining module Sourceror (current version loaded from /nix/store/fd8zdyn7wf656n98xz1a32h00y6xdcxm-elixir-ls-0.14.6/lib/sourceror-0.11.2.ez/sourceror-0.11.2/ebin/Elixir.Sourceror.beam)\n  lib/sourceror.ex:1\n" }
2023-09-02T21:59:02.881 helix_term::application [DEBUG] received editor event: LanguageServerMessage((0, Notification(Notification { jsonrpc: Some(V2), method: "window/logMessage", params: Map({"message": String("warning: redefining module Sourceror.Zipper (current version loaded from /nix/store/fd8zdyn7wf656n98xz1a32h00y6xdcxm-elixir-ls-0.14.6/lib/sourceror-0.11.2.ez/sourceror-0.11.2/ebin/Elixir.Sourceror.Zipper.beam)\n  lib/sourceror/zipper.ex:1\n"), "type": Number(2)}) })))
2023-09-02T21:59:02.881 helix_term::application [INFO] window/logMessage: LogMessageParams { typ: Warning, message: "warning: redefining module Sourceror.Zipper (current version loaded from /nix/store/fd8zdyn7wf656n98xz1a32h00y6xdcxm-elixir-ls-0.14.6/lib/sourceror-0.11.2.ez/sourceror-0.11.2/ebin/Elixir.Sourceror.Zipper.beam)\n  lib/sourceror/zipper.ex:1\n" }
2023-09-02T21:59:02.979 helix_lsp::transport [INFO] <- {"jsonrpc":"2.0","method":"window/logMessage","params":{"message":"\n== Compilation error in file lib/sourceror/zipper/inspect.ex ==\n** (CompileError) lib/sourceror/zipper/inspect.ex:132: Sourceror.Zipper.__struct__/0 is undefined, cannot expand struct Sourceror.Zipper. Make sure the struct name is correct. If the struct name exists and is correct but it still cannot be found, you likely have cyclic module usage in your code\n    (sourceror 0.11.2) expanding struct: Sourceror.Zipper.__struct__/0\n    lib/sourceror/zipper/inspect.ex:132: Sourceror.Zipper.Inspect.get_prefix/2","type":4}}
2023-09-02T21:59:02.979 helix_term::application [DEBUG] received editor event: LanguageServerMessage((0, Notification(Notification { jsonrpc: Some(V2), method: "window/logMessage", params: Map({"message": String("\n== Compilation error in file lib/sourceror/zipper/inspect.ex ==\n** (CompileError) lib/sourceror/zipper/inspect.ex:132: Sourceror.Zipper.__struct__/0 is undefined, cannot expand struct Sourceror.Zipper. Make sure the struct name is correct. If the struct name exists and is correct but it still cannot be found, you likely have cyclic module usage in your code\n    (sourceror 0.11.2) expanding struct: Sourceror.Zipper.__struct__/0\n    lib/sourceror/zipper/inspect.ex:132: Sourceror.Zipper.Inspect.get_prefix/2"), "type": Number(4)}) })))
2023-09-02T21:59:02.979 helix_term::application [INFO] window/logMessage: LogMessageParams { typ: Log, message: "\n== Compilation error in file lib/sourceror/zipper/inspect.ex ==\n** (CompileError) lib/sourceror/zipper/inspect.ex:132: Sourceror.Zipper.__struct__/0 is undefined, cannot expand struct Sourceror.Zipper. Make sure the struct name is correct. If the struct name exists and is correct but it still cannot be found, you likely have cyclic module usage in your code\n    (sourceror 0.11.2) expanding struct: Sourceror.Zipper.__struct__/0\n    lib/sourceror/zipper/inspect.ex:132: Sourceror.Zipper.Inspect.get_prefix/2" }
```

### Expected behavior

I expect that I can use whichever version of Sourceror in my project and that the dependency in elixir-ls does not conflict in any way.

**Comment by lukaszsamson** [comment]
The only reasonable options here is to either vendor Sourceror as we do with Jason and Dialyxir or remove the dependency altogether

**Comment by Zurga** [comment]
I see that my issue is duplicated and there has already been discussion about this and about removing sourceror. I will therefore close my issue. Thanks for the quick reply and great work on Elixir-LS!
