### ISSUE TITLE
Metadata build crashes on Absinthe schema

### ISSUE THREAD

**Issue by lukaszsamson** [elixir-lsp/elixir-ls#999]
elixir_sense is unable to expand `__using__` macro
```
[Warn  - 9:23:43 AM] ** (ErlangError) Erlang error: "ArgumentError during metadata build pre:\ncould not call Module.register_attribute/3 because the module BlogWeb.Schema.AccountTypes is already compiled\nast node: {:use, [end_of_expression: [newlines: 0, line: 2, column: 31], line: 2, column: 3], [{:__aliases__, [last: [line: 2, column: 23], line: 2, column: 7], [:Absinthe, :Schema, :Notation]}]}"
    (elixir 1.14.5) lib/module.ex:2504: Module.assert_not_readonly!/2
    (elixir 1.14.5) lib/module.ex:1626: Module.register_attribute/3
    (absinthe 1.7.5) expanding macro: Absinthe.Schema.Notation.__using__/1
    nofile: BlogWeb.Schema.AccountTypes (module)
```

**Comment by lukaszsamson** [comment]
This issue is now stale. The metadata builder engine in elixir_sense has been replaced
